//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSDictionary, NSString;

@interface ABTestItem : NSObject <PBCoding>
{
    BOOL bNoReport;
    unsigned int uiSeq;
    unsigned int uiBeginTime;
    unsigned int uiEndTime;
    unsigned int uiPriorityLevel;
    unsigned int uiLocalId;
    NSString *nsLayerId;
    NSString *nsExpId;
    NSDictionary *dicExpArgs;
    NSString *nsBizId;
}

+ (void)initialize;
+ (void)_initPBTableOfABTestItem;
@property(nonatomic) unsigned int uiLocalId; // @synthesize uiLocalId;
@property(nonatomic) unsigned int uiPriorityLevel; // @synthesize uiPriorityLevel;
@property(retain, nonatomic) NSString *nsBizId; // @synthesize nsBizId;
@property(nonatomic) BOOL bNoReport; // @synthesize bNoReport;
@property(nonatomic) unsigned int uiEndTime; // @synthesize uiEndTime;
@property(nonatomic) unsigned int uiBeginTime; // @synthesize uiBeginTime;
@property(nonatomic) unsigned int uiSeq; // @synthesize uiSeq;
@property(retain, nonatomic) NSDictionary *dicExpArgs; // @synthesize dicExpArgs;
@property(retain, nonatomic) NSString *nsExpId; // @synthesize nsExpId;
@property(retain, nonatomic) NSString *nsLayerId; // @synthesize nsLayerId;
- (void).cxx_destruct;
- (unsigned int)getPriorityLevel;
- (BOOL)abtestRunning;
- (const map_24f1cf24 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

