//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IContactMgrExt.h"
#import "IMMSessionMgrExt.h"
#import "IMessageExt.h"
#import "MMService.h"

@class BrandSessionHolder, NSMutableArray, NSRecursiveLock, NSString;

@interface BrandSessionMgr : MMService <IMMSessionMgrExt, IContactMgrExt, IMessageExt, MMService>
{
    BOOL _m_hasUpdateHolderContact;
    NSRecursiveLock *_m_lock;
    NSMutableArray *_m_arrBrandInfo;
    BrandSessionHolder *_m_holder;
}

+ (void)LazyRegisterExtension;
@property(retain, nonatomic) BrandSessionHolder *m_holder; // @synthesize m_holder=_m_holder;
@property(nonatomic) BOOL m_hasUpdateHolderContact; // @synthesize m_hasUpdateHolderContact=_m_hasUpdateHolderContact;
@property(retain, nonatomic) NSMutableArray *m_arrBrandInfo; // @synthesize m_arrBrandInfo=_m_arrBrandInfo;
@property(retain, nonatomic) NSRecursiveLock *m_lock; // @synthesize m_lock=_m_lock;
- (void).cxx_destruct;
- (unsigned int)getMaxEnterTime;
- (void)CreateNewSessionWithContact:(id)arg1;
- (void)CreateNewSessionWithUserName:(id)arg1;
- (void)deleteSessionOfUserName:(id)arg1 isDelMsg:(BOOL)arg2;
- (void)deleteMessage:(id)arg1;
- (void)updateBrandSessionArray:(id)arg1;
- (void)updateBrandSession:(id)arg1;
- (BOOL)saveBrandSession:(id)arg1;
- (void)deleteBrandHolderSession;
- (BOOL)hasNewArrival;
- (id)getBrandHolderLastMsg;
- (BOOL)isNeedProcessContact:(id)arg1;
- (void)updateBrandHolderSessionInfo;
- (void)addBrandSessionHolderContact;
- (void)sortBrandSession;
- (void)loadBrandSessionHolderCache;
- (void)loadAllBrandSessions;
- (void)ClearAllBrandSessions;
- (void)ClearBrandSessionHolderUnreadCount;
- (void)deleteSessionWithoutDeleteMessage:(id)arg1;
- (void)DeleteSessionByUI:(id)arg1;
- (unsigned long long)GetSessionIndexByUserName:(id)arg1;
- (id)GetSessionByUserName:(id)arg1;
- (id)GetSessionAtIndex:(unsigned long long)arg1;
- (unsigned long long)GetSessionCount;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;
- (void)processOnDeleteContacts:(id)arg1;
- (void)processOnModifyContacts:(id)arg1;
- (void)changeSessionUnreadCount:(id)arg1;
- (void)processOnDelAllMsg:(id)arg1;
- (void)processOnModMsg:(id)arg1 msgData:(id)arg2;
- (BOOL)isNeedCallNewMsgArrival:(id)arg1;
- (void)processOnAddMsgListForSession:(id)arg1 NotifyUsrName:(id)arg2;
- (void)onUnReadCountChange:(id)arg1;
- (void)onDelMsg:(id)arg1 msgData:(id)arg2;
- (void)onDelAllMsg:(id)arg1;
- (void)onModMsg:(id)arg1 msgData:(id)arg2;
- (void)onAddMsgListForSession:(id)arg1 NotifyUsrName:(id)arg2;
- (void)onDeleteContacts:(id)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)AskSessionByUserName:(id)arg1 isHandled:(char *)arg2;
- (void)OnSyncSessionListFinished;
- (void)onSessionLoadedFromDB;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

