//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PBCoding.h"

@class NSString;

@interface BrandSessionHolder : NSObject <PBCoding>
{
    BOOL m_hasNewArrival;
    unsigned int m_lastTime;
}

+ (id)LoadBrandSessionHolder;
+ (void)initialize;
+ (void)_initPBTableOfBrandSessionHolder;
@property(nonatomic) unsigned int m_lastTime; // @synthesize m_lastTime;
@property(nonatomic) BOOL m_hasNewArrival; // @synthesize m_hasNewArrival;
- (BOOL)saveData;
- (const map_24f1cf24 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

