//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface BufferId : PBGeneratedMessage
{
    unsigned int hasMasterBufId:1;
    unsigned int hasSlaveBufId:1;
    unsigned long long masterBufId;
    unsigned long long slaveBufId;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetSlaveBufId:) unsigned long long slaveBufId; // @synthesize slaveBufId;
@property(readonly, nonatomic) BOOL hasSlaveBufId; // @synthesize hasSlaveBufId;
@property(nonatomic, setter=SetMasterBufId:) unsigned long long masterBufId; // @synthesize masterBufId;
@property(readonly, nonatomic) BOOL hasMasterBufId; // @synthesize hasMasterBufId;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

