//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface CardDataInfo : PBGeneratedMessage
{
    unsigned int hasCardId:1;
    NSString *cardId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetCardId:) NSString *cardId; // @synthesize cardId;
@property(readonly, nonatomic) BOOL hasCardId; // @synthesize hasCardId;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

