//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSMutableArray;

@interface CliReportKVReq : PBGeneratedMessage
{
    unsigned int hasGeneralVersion:1;
    unsigned int hasSpecialVersion:1;
    unsigned int hasWhiteOrBlackUinVersion:1;
    unsigned int hasRandomEncryKey:1;
    unsigned int generalVersion;
    unsigned int specialVersion;
    unsigned int whiteOrBlackUinVersion;
    NSMutableArray *mutableDataPkgList;
    NSData *randomEncryKey;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetRandomEncryKey:) NSData *randomEncryKey; // @synthesize randomEncryKey;
@property(readonly, nonatomic) BOOL hasRandomEncryKey; // @synthesize hasRandomEncryKey;
@property(retain, nonatomic) NSMutableArray *mutableDataPkgList; // @synthesize mutableDataPkgList;
@property(nonatomic, setter=SetWhiteOrBlackUinVersion:) unsigned int whiteOrBlackUinVersion; // @synthesize whiteOrBlackUinVersion;
@property(readonly, nonatomic) BOOL hasWhiteOrBlackUinVersion; // @synthesize hasWhiteOrBlackUinVersion;
@property(nonatomic, setter=SetSpecialVersion:) unsigned int specialVersion; // @synthesize specialVersion;
@property(readonly, nonatomic) BOOL hasSpecialVersion; // @synthesize hasSpecialVersion;
@property(nonatomic, setter=SetGeneralVersion:) unsigned int generalVersion; // @synthesize generalVersion;
@property(readonly, nonatomic) BOOL hasGeneralVersion; // @synthesize hasGeneralVersion;
- (void).cxx_destruct;
- (void)addDataPkg:(id)arg1;
- (void)addDataPkgFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *dataPkg; // @dynamic dataPkg;
- (id)dataPkgList;
- (id)init;

@end

