//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSMutableArray;

@interface CustomDrawingTabView : NSView
{
    NSMutableArray *_tabCells;
    long long _selectedIndex;
    CDUnknownBlockType _tabDatasourceTabCount;
    CDUnknownBlockType _tabDatasourceTabItemRect;
    CDUnknownBlockType _tabItemDrawingBlock;
    CDUnknownBlockType _tabDataSourceTabItemClick;
    CDUnknownBlockType _backgroundDrawingBalock;
}

@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(copy, nonatomic) CDUnknownBlockType backgroundDrawingBalock; // @synthesize backgroundDrawingBalock=_backgroundDrawingBalock;
@property(copy, nonatomic) CDUnknownBlockType tabDataSourceTabItemClick; // @synthesize tabDataSourceTabItemClick=_tabDataSourceTabItemClick;
@property(copy, nonatomic) CDUnknownBlockType tabItemDrawingBlock; // @synthesize tabItemDrawingBlock=_tabItemDrawingBlock;
@property(copy, nonatomic) CDUnknownBlockType tabDatasourceTabItemRect; // @synthesize tabDatasourceTabItemRect=_tabDatasourceTabItemRect;
@property(copy, nonatomic) CDUnknownBlockType tabDatasourceTabCount; // @synthesize tabDatasourceTabCount=_tabDatasourceTabCount;
- (void).cxx_destruct;
- (id)cellAtIndex:(unsigned long long)arg1;
- (void)updateContent;
- (void)drawRect:(struct CGRect)arg1;
- (void)mouseUp:(id)arg1;
- (void)setFrame:(struct CGRect)arg1;

@end

