//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSButton;

@interface DebugMiscOptionsController : NSWindowController
{
    BOOL _needsRestart;
    NSButton *_showMessageLayoutCheckbox;
    NSButton *_keepMeLoggedInCheckbox;
    NSButton *_keepHistoryCheckbox;
    NSButton *_placeholdersCheckbox;
    NSButton *_restartButton;
    NSButton *_dumpMonitorCheckbox;
}

@property BOOL needsRestart; // @synthesize needsRestart=_needsRestart;
@property __weak NSButton *dumpMonitorCheckbox; // @synthesize dumpMonitorCheckbox=_dumpMonitorCheckbox;
@property(retain, nonatomic) NSButton *restartButton; // @synthesize restartButton=_restartButton;
@property(retain, nonatomic) NSButton *placeholdersCheckbox; // @synthesize placeholdersCheckbox=_placeholdersCheckbox;
@property(retain, nonatomic) NSButton *keepHistoryCheckbox; // @synthesize keepHistoryCheckbox=_keepHistoryCheckbox;
@property(retain, nonatomic) NSButton *keepMeLoggedInCheckbox; // @synthesize keepMeLoggedInCheckbox=_keepMeLoggedInCheckbox;
@property(retain, nonatomic) NSButton *showMessageLayoutCheckbox; // @synthesize showMessageLayoutCheckbox=_showMessageLayoutCheckbox;
- (void).cxx_destruct;
- (void)changMonitorState:(id)arg1;
- (void)uploadAllDumpReport:(id)arg1;
- (void)testCrashReport:(id)arg1;
- (void)clearAvatarCache:(id)arg1;
- (void)sendUnlockMessage:(id)arg1;
- (void)sendActiveMessage:(id)arg1;
- (void)restartNow:(id)arg1;
- (void)changePlaceholderDialogs:(id)arg1;
- (void)changeKeepLoggedIn:(id)arg1;
- (void)changeKeepHistory:(id)arg1;
- (void)changeShowMessageLayout:(id)arg1;
- (void)windowDidLoad;

@end

