//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface DisturbTimeSpan : PBGeneratedMessage
{
    unsigned int hasBeginTime:1;
    unsigned int hasEndTime:1;
    unsigned int beginTime;
    unsigned int endTime;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetEndTime:) unsigned int endTime; // @synthesize endTime;
@property(readonly, nonatomic) BOOL hasEndTime; // @synthesize hasEndTime;
@property(nonatomic, setter=SetBeginTime:) unsigned int beginTime; // @synthesize beginTime;
@property(readonly, nonatomic) BOOL hasBeginTime; // @synthesize hasBeginTime;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

