//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

#import "VoipOpenglesContextDelegate.h"

@class NSString, VoipOpenglesContext;

@interface EAGLView_v2 : NSView <VoipOpenglesContextDelegate>
{
    BOOL m_acceptNV12;
    BOOL m_mirrored;
    NSView *m_defaultView;
    VoipOpenglesContext *m_openglesContext;
    id <NSObject> targetor;
    SEL selector;
}

+ (Class)layerClass;
@property(nonatomic) BOOL m_mirrored; // @synthesize m_mirrored;
@property(nonatomic) BOOL m_acceptNV12; // @synthesize m_acceptNV12;
@property(nonatomic) SEL selector; // @synthesize selector;
@property(retain, nonatomic) id <NSObject> targetor; // @synthesize targetor;
@property(retain, nonatomic) VoipOpenglesContext *m_openglesContext; // @synthesize m_openglesContext;
@property(retain, nonatomic) NSView *m_defaultView; // @synthesize m_defaultView;
- (void).cxx_destruct;
- (void)randerDefaultView:(id)arg1;
- (void)changeFrame:(struct CGRect)arg1;
- (void)resetMirror:(BOOL)arg1;
- (void)setDegrees:(float)arg1;
- (void)applyRotation:(float)arg1;
- (void)dealloc;
- (void)renderImage3:(char **)arg1 Width:(unsigned int)arg2 Height:(unsigned int)arg3;
- (void)renderImage2:(char *)arg1 Width:(unsigned int)arg2 Height:(unsigned int)arg3;
- (void)renderImage:(char *)arg1 Width:(unsigned int)arg2 Height:(unsigned int)arg3;
- (void)addSingleTapTarget:(id)arg1 action:(SEL)arg2;
- (void)stopRender;
- (void)restartRender;
- (void)setupELGS:(BOOL)arg1 IsMirrored:(BOOL)arg2;
- (void)setupELGS;
- (id)initWithView:(id)arg1 AcceptNV12:(BOOL)arg2 IsMirrored:(BOOL)arg3;
- (id)initWithView:(id)arg1 AcceptNV12:(BOOL)arg2;
- (id)initWithView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)whenEnterBackground;
- (void)whenDidActive;
- (id)renderView;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesCancelled:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (BOOL)checkTouchPoint:(struct CGPoint)arg1 IfInView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

