//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface EmojiInfo : PBGeneratedMessage
{
    unsigned int hasMd5:1;
    unsigned int hasUrl:1;
    unsigned int hasThumbUrl:1;
    unsigned int hasDesignerId:1;
    unsigned int hasEncryptUrl:1;
    unsigned int hasAesKey:1;
    unsigned int hasProductId:1;
    NSString *md5;
    NSString *url;
    NSString *thumbUrl;
    NSString *designerId;
    NSString *encryptUrl;
    NSString *aesKey;
    NSString *productId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetProductId:) NSString *productId; // @synthesize productId;
@property(readonly, nonatomic) BOOL hasProductId; // @synthesize hasProductId;
@property(retain, nonatomic, setter=SetAesKey:) NSString *aesKey; // @synthesize aesKey;
@property(readonly, nonatomic) BOOL hasAesKey; // @synthesize hasAesKey;
@property(retain, nonatomic, setter=SetEncryptUrl:) NSString *encryptUrl; // @synthesize encryptUrl;
@property(readonly, nonatomic) BOOL hasEncryptUrl; // @synthesize hasEncryptUrl;
@property(retain, nonatomic, setter=SetDesignerId:) NSString *designerId; // @synthesize designerId;
@property(readonly, nonatomic) BOOL hasDesignerId; // @synthesize hasDesignerId;
@property(retain, nonatomic, setter=SetThumbUrl:) NSString *thumbUrl; // @synthesize thumbUrl;
@property(readonly, nonatomic) BOOL hasThumbUrl; // @synthesize hasThumbUrl;
@property(retain, nonatomic, setter=SetUrl:) NSString *url; // @synthesize url;
@property(readonly, nonatomic) BOOL hasUrl; // @synthesize hasUrl;
@property(retain, nonatomic, setter=SetMd5:) NSString *md5; // @synthesize md5;
@property(readonly, nonatomic) BOOL hasMd5; // @synthesize hasMd5;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

