//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface EmoticonUploadCGI : NSObject
{
    BOOL _isUploading;
    id <EmoticonUploadCGIDelegate> _delegate;
}

@property(nonatomic) BOOL isUploading; // @synthesize isUploading=_isUploading;
@property(nonatomic) __weak id <EmoticonUploadCGIDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)stopUploadEmoticon;
- (BOOL)startUploadEmoticon;
- (id)initWithMD5:(id)arg1;

@end

