//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface EnemyGameInfo : PBGeneratedMessage
{
    unsigned int hasType:1;
    unsigned int hasScore:1;
    unsigned int type;
    unsigned int score;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetScore:) unsigned int score; // @synthesize score;
@property(readonly, nonatomic) BOOL hasScore; // @synthesize hasScore;
@property(nonatomic, setter=SetType:) unsigned int type; // @synthesize type;
@property(readonly, nonatomic) BOOL hasType; // @synthesize hasType;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

