//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface Express : PBGeneratedMessage
{
    unsigned int hasName:1;
    unsigned int hasPrice:1;
    unsigned int hasPriceType:1;
    unsigned int hasId:1;
    unsigned int id_;
    unsigned int price;
    NSString *name;
    NSString *priceType;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetId:) unsigned int id; // @synthesize id=id_;
@property(readonly, nonatomic) BOOL hasId; // @synthesize hasId;
@property(retain, nonatomic, setter=SetPriceType:) NSString *priceType; // @synthesize priceType;
@property(readonly, nonatomic) BOOL hasPriceType; // @synthesize hasPriceType;
@property(nonatomic, setter=SetPrice:) unsigned int price; // @synthesize price;
@property(readonly, nonatomic) BOOL hasPrice; // @synthesize hasPrice;
@property(retain, nonatomic, setter=SetName:) NSString *name; // @synthesize name;
@property(readonly, nonatomic) BOOL hasName; // @synthesize hasName;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

