//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface ExtDeviceLoginConfirmErrorRet : PBGeneratedMessage
{
    unsigned int hasIconType:1;
    unsigned int hasContentStr:1;
    unsigned int hasTitleStr:1;
    unsigned int hasButtonStr:1;
    unsigned int iconType;
    NSString *contentStr;
    NSString *titleStr;
    NSString *buttonStr;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetButtonStr:) NSString *buttonStr; // @synthesize buttonStr;
@property(readonly, nonatomic) BOOL hasButtonStr; // @synthesize hasButtonStr;
@property(retain, nonatomic, setter=SetTitleStr:) NSString *titleStr; // @synthesize titleStr;
@property(readonly, nonatomic) BOOL hasTitleStr; // @synthesize hasTitleStr;
@property(retain, nonatomic, setter=SetContentStr:) NSString *contentStr; // @synthesize contentStr;
@property(readonly, nonatomic) BOOL hasContentStr; // @synthesize hasContentStr;
@property(nonatomic, setter=SetIconType:) unsigned int iconType; // @synthesize iconType;
@property(readonly, nonatomic) BOOL hasIconType; // @synthesize hasIconType;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

