//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@interface FavoritesPasteboardData : NSObject <NSCoding>
{
    unsigned int _localID;
}

@property(nonatomic) unsigned int localID; // @synthesize localID=_localID;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithItem:(id)arg1;
- (id)initWithCoder:(id)arg1;

@end

