//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMCGIRequester, NSMutableArray, NSObject<FavoritesBatchGetMgrDelegate>, NSObject<OS_dispatch_queue>, WCFavoritesDB;

@interface FavoritesBatchGetMgr : NSObject
{
    MMCGIRequester *_requester;
    WCFavoritesDB *_favItemDB;
    NSMutableArray *_batchGetFavIDs;
    NSObject<OS_dispatch_queue> *queue_addNewList;
    unsigned int _failCount;
    BOOL _isGetting;
    BOOL _requested;
    NSObject<FavoritesBatchGetMgrDelegate> *_delegate;
}

@property(nonatomic) __weak NSObject<FavoritesBatchGetMgrDelegate> *delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_checkInvalidNoteItemSyncFromSvr:(id)arg1;
- (BOOL)_checkConflict:(id)arg1 vs:(id)arg2;
- (void)_handleBatchGetFavItemResp:(id)arg1;
- (void)asyncDoAddNewItemList:(id)arg1;
- (void)_tryStartBatchGet;
- (void)addBatchGetFavoritesFavIds:(id)arg1;
- (void)dealloc;
- (id)initWithDB:(id)arg1;

@end

