//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FavoritesItemDataField, NSString;

@interface FavThumbRequestParam : NSObject
{
    unsigned int _favID;
    unsigned long long _thumbnailStyle;
    FavoritesItemDataField *_dataField;
    NSString *_imageHttpUrl;
}

@property(nonatomic) unsigned int favID; // @synthesize favID=_favID;
@property(retain, nonatomic) NSString *imageHttpUrl; // @synthesize imageHttpUrl=_imageHttpUrl;
@property(retain, nonatomic) FavoritesItemDataField *dataField; // @synthesize dataField=_dataField;
@property(nonatomic) unsigned long long thumbnailStyle; // @synthesize thumbnailStyle=_thumbnailStyle;
- (void).cxx_destruct;
- (BOOL)isFavThumbRequestContainThumbImage;
- (id)initWithFavItemDataField:(id)arg1 andThumbnailStyle:(unsigned long long)arg2;
- (id)initWithFavItem:(id)arg1 andThumbnailStyle:(unsigned long long)arg2;

@end

