//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse;

@interface GameGiftResp : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasLifeNum:1;
    unsigned int hasCheckLeftTime:1;
    unsigned int lifeNum;
    unsigned int checkLeftTime;
    BaseResponse *baseResponse;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetCheckLeftTime:) unsigned int checkLeftTime; // @synthesize checkLeftTime;
@property(readonly, nonatomic) BOOL hasCheckLeftTime; // @synthesize hasCheckLeftTime;
@property(nonatomic, setter=SetLifeNum:) unsigned int lifeNum; // @synthesize lifeNum;
@property(readonly, nonatomic) BOOL hasLifeNum; // @synthesize hasLifeNum;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

