//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSMutableArray, NSString;

@interface GameStartReq : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasAppId:1;
    unsigned int hasLocalLifeNum:1;
    unsigned int hasToken:1;
    unsigned int hasNeedClearWishList:1;
    unsigned int hasGameConsumePropsCount:1;
    unsigned int localLifeNum;
    unsigned int needClearWishList;
    int gameConsumePropsCount;
    BaseRequest *baseRequest;
    NSString *appId;
    NSString *token;
    NSMutableArray *mutableGameConsumePropsListList;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *mutableGameConsumePropsListList; // @synthesize mutableGameConsumePropsListList;
@property(nonatomic, setter=SetGameConsumePropsCount:) int gameConsumePropsCount; // @synthesize gameConsumePropsCount;
@property(readonly, nonatomic) BOOL hasGameConsumePropsCount; // @synthesize hasGameConsumePropsCount;
@property(nonatomic, setter=SetNeedClearWishList:) unsigned int needClearWishList; // @synthesize needClearWishList;
@property(readonly, nonatomic) BOOL hasNeedClearWishList; // @synthesize hasNeedClearWishList;
@property(retain, nonatomic, setter=SetToken:) NSString *token; // @synthesize token;
@property(readonly, nonatomic) BOOL hasToken; // @synthesize hasToken;
@property(nonatomic, setter=SetLocalLifeNum:) unsigned int localLifeNum; // @synthesize localLifeNum;
@property(readonly, nonatomic) BOOL hasLocalLifeNum; // @synthesize hasLocalLifeNum;
@property(retain, nonatomic, setter=SetAppId:) NSString *appId; // @synthesize appId;
@property(readonly, nonatomic) BOOL hasAppId; // @synthesize hasAppId;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (void)addGameConsumePropsList:(id)arg1;
- (void)addGameConsumePropsListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *gameConsumePropsList; // @dynamic gameConsumePropsList;
- (id)gameConsumePropsListList;
- (id)init;

@end

