//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray;

@interface GetBoundHardDevicesResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasCount:1;
    unsigned int hasVersion:1;
    unsigned int hasContinueFlag:1;
    unsigned int count;
    unsigned int version;
    unsigned int continueFlag;
    BaseResponse *baseResponse;
    NSMutableArray *mutableDeviceListList;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetContinueFlag:) unsigned int continueFlag; // @synthesize continueFlag;
@property(readonly, nonatomic) BOOL hasContinueFlag; // @synthesize hasContinueFlag;
@property(nonatomic, setter=SetVersion:) unsigned int version; // @synthesize version;
@property(readonly, nonatomic) BOOL hasVersion; // @synthesize hasVersion;
@property(retain, nonatomic) NSMutableArray *mutableDeviceListList; // @synthesize mutableDeviceListList;
@property(nonatomic, setter=SetCount:) unsigned int count; // @synthesize count;
@property(readonly, nonatomic) BOOL hasCount; // @synthesize hasCount;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addDeviceList:(id)arg1;
- (void)addDeviceListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *deviceList; // @dynamic deviceList;
- (id)deviceListList;
- (id)init;

@end

