//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray, NSString, SKBuiltinBuffer_t;

@interface GetConnectInfoResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasId:1;
    NSString *id_;
    unsigned int hasKey:1;
    unsigned int hasHello:1;
    unsigned int hasOk:1;
    unsigned int hasType:1;
    unsigned int hasAddrCount:1;
    unsigned int hasResource:1;
    unsigned int hasPcname:1;
    unsigned int hasPcacctName:1;
    unsigned int hasEncryFlag:1;
    unsigned int hasScene:1;
    unsigned int hasDataSize:1;
    unsigned int hasWifiName:1;
    unsigned int type;
    unsigned int addrCount;
    unsigned int encryFlag;
    unsigned int scene;
    BaseResponse *baseResponse;
    SKBuiltinBuffer_t *key;
    NSString *hello;
    NSString *ok;
    NSMutableArray *mutableAddrListList;
    NSString *resource;
    NSString *pcname;
    NSString *pcacctName;
    unsigned long long dataSize;
    NSString *wifiName;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetWifiName:) NSString *wifiName; // @synthesize wifiName;
@property(readonly, nonatomic) BOOL hasWifiName; // @synthesize hasWifiName;
@property(nonatomic, setter=SetDataSize:) unsigned long long dataSize; // @synthesize dataSize;
@property(readonly, nonatomic) BOOL hasDataSize; // @synthesize hasDataSize;
@property(nonatomic, setter=SetScene:) unsigned int scene; // @synthesize scene;
@property(readonly, nonatomic) BOOL hasScene; // @synthesize hasScene;
@property(nonatomic, setter=SetEncryFlag:) unsigned int encryFlag; // @synthesize encryFlag;
@property(readonly, nonatomic) BOOL hasEncryFlag; // @synthesize hasEncryFlag;
@property(retain, nonatomic, setter=SetPcacctName:) NSString *pcacctName; // @synthesize pcacctName;
@property(readonly, nonatomic) BOOL hasPcacctName; // @synthesize hasPcacctName;
@property(retain, nonatomic, setter=SetPcname:) NSString *pcname; // @synthesize pcname;
@property(readonly, nonatomic) BOOL hasPcname; // @synthesize hasPcname;
@property(retain, nonatomic, setter=SetResource:) NSString *resource; // @synthesize resource;
@property(readonly, nonatomic) BOOL hasResource; // @synthesize hasResource;
@property(retain, nonatomic) NSMutableArray *mutableAddrListList; // @synthesize mutableAddrListList;
@property(nonatomic, setter=SetAddrCount:) unsigned int addrCount; // @synthesize addrCount;
@property(readonly, nonatomic) BOOL hasAddrCount; // @synthesize hasAddrCount;
@property(nonatomic, setter=SetType:) unsigned int type; // @synthesize type;
@property(readonly, nonatomic) BOOL hasType; // @synthesize hasType;
@property(retain, nonatomic, setter=SetOk:) NSString *ok; // @synthesize ok;
@property(readonly, nonatomic) BOOL hasOk; // @synthesize hasOk;
@property(retain, nonatomic, setter=SetHello:) NSString *hello; // @synthesize hello;
@property(readonly, nonatomic) BOOL hasHello; // @synthesize hasHello;
@property(retain, nonatomic, setter=SetKey:) SKBuiltinBuffer_t *key; // @synthesize key;
@property(readonly, nonatomic) BOOL hasKey; // @synthesize hasKey;
@property(retain, nonatomic, setter=SetId:) NSString *id; // @synthesize id=id_;
@property(readonly, nonatomic) BOOL hasId; // @synthesize hasId;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addAddrList:(id)arg1;
- (void)addAddrListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *addrList; // @dynamic addrList;
- (id)addrListList;
- (id)init;

@end

