//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray, YYBStruct;

@interface GetGameRankListResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasCount:1;
    unsigned int hasFriendsCount:1;
    unsigned int hasHasReportScore:1;
    unsigned int hasSyyb:1;
    unsigned int count;
    unsigned int friendsCount;
    unsigned int hasReportScore;
    BaseResponse *baseResponse;
    NSMutableArray *mutableRankListList;
    YYBStruct *syyb;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetSyyb:) YYBStruct *syyb; // @synthesize syyb;
@property(readonly, nonatomic) BOOL hasSyyb; // @synthesize hasSyyb;
@property(nonatomic, setter=SetHasReportScore:) unsigned int hasReportScore; // @synthesize hasReportScore;
@property(readonly, nonatomic) BOOL hasHasReportScore; // @synthesize hasHasReportScore;
@property(nonatomic, setter=SetFriendsCount:) unsigned int friendsCount; // @synthesize friendsCount;
@property(readonly, nonatomic) BOOL hasFriendsCount; // @synthesize hasFriendsCount;
@property(retain, nonatomic) NSMutableArray *mutableRankListList; // @synthesize mutableRankListList;
@property(nonatomic, setter=SetCount:) unsigned int count; // @synthesize count;
@property(readonly, nonatomic) BOOL hasCount; // @synthesize hasCount;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addRankList:(id)arg1;
- (void)addRankListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *rankList; // @dynamic rankList;
- (id)rankListList;
- (id)init;

@end

