//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSString;

@interface GetNBSDetailResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasDetailInfo:1;
    unsigned int hasCardInfo:1;
    BaseResponse *baseResponse;
    NSString *detailInfo;
    NSString *cardInfo;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetCardInfo:) NSString *cardInfo; // @synthesize cardInfo;
@property(readonly, nonatomic) BOOL hasCardInfo; // @synthesize hasCardInfo;
@property(retain, nonatomic, setter=SetDetailInfo:) NSString *detailInfo; // @synthesize detailInfo;
@property(readonly, nonatomic) BOOL hasDetailInfo; // @synthesize hasDetailInfo;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

