//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, SKBuiltinString_t;

@interface HandleImgMsgResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasMsgId:1;
    unsigned int hasClientImgId:1;
    unsigned int hasFromUserName:1;
    unsigned int hasToUserName:1;
    unsigned int hasImgLen:1;
    unsigned int hasCreateTime:1;
    unsigned int hasNewMsgId:1;
    unsigned int msgId;
    unsigned int imgLen;
    unsigned int createTime;
    BaseResponse *baseResponse;
    SKBuiltinString_t *clientImgId;
    SKBuiltinString_t *fromUserName;
    SKBuiltinString_t *toUserName;
    unsigned long long newMsgId;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetNewMsgId:) unsigned long long newMsgId; // @synthesize newMsgId;
@property(readonly, nonatomic) BOOL hasNewMsgId; // @synthesize hasNewMsgId;
@property(nonatomic, setter=SetCreateTime:) unsigned int createTime; // @synthesize createTime;
@property(readonly, nonatomic) BOOL hasCreateTime; // @synthesize hasCreateTime;
@property(nonatomic, setter=SetImgLen:) unsigned int imgLen; // @synthesize imgLen;
@property(readonly, nonatomic) BOOL hasImgLen; // @synthesize hasImgLen;
@property(retain, nonatomic, setter=SetToUserName:) SKBuiltinString_t *toUserName; // @synthesize toUserName;
@property(readonly, nonatomic) BOOL hasToUserName; // @synthesize hasToUserName;
@property(retain, nonatomic, setter=SetFromUserName:) SKBuiltinString_t *fromUserName; // @synthesize fromUserName;
@property(readonly, nonatomic) BOOL hasFromUserName; // @synthesize hasFromUserName;
@property(retain, nonatomic, setter=SetClientImgId:) SKBuiltinString_t *clientImgId; // @synthesize clientImgId;
@property(readonly, nonatomic) BOOL hasClientImgId; // @synthesize hasClientImgId;
@property(nonatomic, setter=SetMsgId:) unsigned int msgId; // @synthesize msgId;
@property(readonly, nonatomic) BOOL hasMsgId; // @synthesize hasMsgId;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

