//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface HeadImageTask : NSObject
{
    BOOL _m_isHD;
    BOOL _m_isForce;
    int _m_scene;
    NSString *_m_userName;
    NSString *_m_url;
    unsigned long long _m_retryTimes;
    unsigned long long _m_failTime;
    NSData *_m_imageData;
}

@property(retain, nonatomic) NSData *m_imageData; // @synthesize m_imageData=_m_imageData;
@property(nonatomic) unsigned long long m_failTime; // @synthesize m_failTime=_m_failTime;
@property(nonatomic) unsigned long long m_retryTimes; // @synthesize m_retryTimes=_m_retryTimes;
@property(nonatomic) BOOL m_isForce; // @synthesize m_isForce=_m_isForce;
@property(nonatomic) BOOL m_isHD; // @synthesize m_isHD=_m_isHD;
@property(nonatomic) int m_scene; // @synthesize m_scene=_m_scene;
@property(retain, nonatomic) NSString *m_url; // @synthesize m_url=_m_url;
@property(retain, nonatomic) NSString *m_userName; // @synthesize m_userName=_m_userName;
- (void).cxx_destruct;
- (BOOL)isValid;
- (id)description;
- (BOOL)isEqual:(id)arg1;
- (id)init;

@end

