//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HexString : NSObject
{
}

+ (void)HexStringToUnsignedChar:(id)arg1 output:(char **)arg2 outputLength:(unsigned int *)arg3;
+ (id)UnSignedCharToHexString:(char *)arg1 withSize:(unsigned int)arg2;

@end

