//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface IBeaconNotification : PBGeneratedMessage
{
    unsigned int hasResult:1;
    unsigned int hasTips:1;
    unsigned int hasMessage:1;
    int result;
    NSString *tips;
    NSString *message;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetMessage:) NSString *message; // @synthesize message;
@property(readonly, nonatomic) BOOL hasMessage; // @synthesize hasMessage;
@property(retain, nonatomic, setter=SetTips:) NSString *tips; // @synthesize tips;
@property(readonly, nonatomic) BOOL hasTips; // @synthesize hasTips;
@property(nonatomic, setter=SetResult:) int result; // @synthesize result;
@property(readonly, nonatomic) BOOL hasResult; // @synthesize hasResult;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

