//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface INWindowButtonGroup : NSObject
{
    NSString *_identifier;
    long long _numberOfCaptures;
}

+ (id)groupWithIdentifier:(id)arg1;
@property(nonatomic) long long numberOfCaptures; // @synthesize numberOfCaptures=_numberOfCaptures;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (void)resetMouseCaptures;
- (BOOL)shouldDisplayRollOver;
- (void)didReleaseMousePointer;
- (void)didCaptureMousePointer;
- (id)initWithIdentifier:(id)arg1;

@end

