//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JNWCollectionView;

@interface JNWCollectionViewData : NSObject
{
    CDStruct_4b25f01b *_sectionData;
    long long _numberOfSections;
    JNWCollectionView *_collectionView;
    struct CGSize _encompassingSize;
}

@property(nonatomic) __weak JNWCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) struct CGSize encompassingSize; // @synthesize encompassingSize=_encompassingSize;
@property(nonatomic) long long numberOfSections; // @synthesize numberOfSections=_numberOfSections;
- (void).cxx_destruct;
- (struct CGSize)encompassingSizeWithLayout:(id)arg1;
- (void)recalculateAndPrepareLayout:(BOOL)arg1;
- (long long)numberOfItemsInSection:(long long)arg1;
- (id)initWithCollectionView:(id)arg1;
@property(readonly, nonatomic) CDStruct_4b25f01b *sections;

@end

