//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface KeyVal : PBGeneratedMessage
{
    unsigned int hasKey:1;
    unsigned int hasVal:1;
    unsigned int key;
    unsigned int val;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetVal:) unsigned int val; // @synthesize val;
@property(readonly, nonatomic) BOOL hasVal; // @synthesize hasVal;
@property(nonatomic, setter=SetKey:) unsigned int key; // @synthesize key;
@property(readonly, nonatomic) BOOL hasKey; // @synthesize hasKey;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

