//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData;

@interface KvGetStrategyReq : PBGeneratedMessage
{
    unsigned int hasGenstgver:1;
    unsigned int hasClistgver:1;
    unsigned int hasUinstgver:1;
    unsigned int hasEncryptkey:1;
    unsigned int genstgver;
    unsigned int clistgver;
    unsigned int uinstgver;
    NSData *encryptkey;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetEncryptkey:) NSData *encryptkey; // @synthesize encryptkey;
@property(readonly, nonatomic) BOOL hasEncryptkey; // @synthesize hasEncryptkey;
@property(nonatomic, setter=SetUinstgver:) unsigned int uinstgver; // @synthesize uinstgver;
@property(readonly, nonatomic) BOOL hasUinstgver; // @synthesize hasUinstgver;
@property(nonatomic, setter=SetClistgver:) unsigned int clistgver; // @synthesize clistgver;
@property(readonly, nonatomic) BOOL hasClistgver; // @synthesize hasClistgver;
@property(nonatomic, setter=SetGenstgver:) unsigned int genstgver; // @synthesize genstgver;
@property(readonly, nonatomic) BOOL hasGenstgver; // @synthesize hasGenstgver;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

