//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class LbsLife, NSMutableArray, NSString;

@interface LbsLifeDetail : PBGeneratedMessage
{
    unsigned int hasLife:1;
    unsigned int hasCicount:1;
    unsigned int hasThumbUrl:1;
    unsigned int hasPhotoLink:1;
    unsigned int hasActionCount:1;
    unsigned int cicount;
    unsigned int actionCount;
    LbsLife *life;
    NSMutableArray *mutableCilistList;
    NSString *thumbUrl;
    NSString *photoLink;
    NSMutableArray *mutableActionListList;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *mutableActionListList; // @synthesize mutableActionListList;
@property(nonatomic, setter=SetActionCount:) unsigned int actionCount; // @synthesize actionCount;
@property(readonly, nonatomic) BOOL hasActionCount; // @synthesize hasActionCount;
@property(retain, nonatomic, setter=SetPhotoLink:) NSString *photoLink; // @synthesize photoLink;
@property(readonly, nonatomic) BOOL hasPhotoLink; // @synthesize hasPhotoLink;
@property(retain, nonatomic, setter=SetThumbUrl:) NSString *thumbUrl; // @synthesize thumbUrl;
@property(readonly, nonatomic) BOOL hasThumbUrl; // @synthesize hasThumbUrl;
@property(retain, nonatomic) NSMutableArray *mutableCilistList; // @synthesize mutableCilistList;
@property(nonatomic, setter=SetCicount:) unsigned int cicount; // @synthesize cicount;
@property(readonly, nonatomic) BOOL hasCicount; // @synthesize hasCicount;
@property(retain, nonatomic, setter=SetLife:) LbsLife *life; // @synthesize life;
@property(readonly, nonatomic) BOOL hasLife; // @synthesize hasLife;
- (void).cxx_destruct;
- (void)addActionList:(id)arg1;
- (void)addActionListFromArray:(id)arg1;
- (void)addCilist:(id)arg1;
- (void)addCilistFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *actionList; // @dynamic actionList;
- (id)actionListList;
@property(retain, nonatomic) NSMutableArray *cilist; // @dynamic cilist;
- (id)cilistList;
- (id)init;

@end

