//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData;

@interface LifeDataItem : PBGeneratedMessage
{
    unsigned int hasEventtype:1;
    unsigned int hasData:1;
    NSData *data_;
    unsigned int eventtype;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetData:) NSData *data; // @synthesize data=data_;
@property(readonly, nonatomic) BOOL hasData; // @synthesize hasData;
@property(nonatomic, setter=SetEventtype:) unsigned int eventtype; // @synthesize eventtype;
@property(readonly, nonatomic) BOOL hasEventtype; // @synthesize hasEventtype;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

