//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface LifeCardInfo : PBGeneratedMessage
{
    unsigned int hasCardTpId:1;
    unsigned int hasCardExt:1;
    NSString *cardTpId;
    NSString *cardExt;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetCardExt:) NSString *cardExt; // @synthesize cardExt;
@property(readonly, nonatomic) BOOL hasCardExt; // @synthesize hasCardExt;
@property(retain, nonatomic, setter=SetCardTpId:) NSString *cardTpId; // @synthesize cardTpId;
@property(readonly, nonatomic) BOOL hasCardTpId; // @synthesize hasCardTpId;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

