//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMCGIDelegate.h"

@class MMTimer, NSString;

@interface LogoutCGI : NSObject <MMCGIDelegate>
{
    BOOL _alreadyCallback;
    id <LogoutCGIExt> _delegate;
    MMTimer *_timer;
    CDUnknownBlockType _callbackBlock;
}

@property(copy, nonatomic) CDUnknownBlockType callbackBlock; // @synthesize callbackBlock=_callbackBlock;
@property(nonatomic) BOOL alreadyCallback; // @synthesize alreadyCallback=_alreadyCallback;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) id <LogoutCGIExt> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)onTimeout;
- (void)logoutCallback:(BOOL)arg1;
- (void)stopTimer;
- (void)startTimer;
- (void)sendLogoutCGIWithCompletion:(CDUnknownBlockType)arg1;
- (void)ClearData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

