//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSString, SKBuiltinBuffer_t;

@interface MassSendRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasToList:1;
    unsigned int hasToListMd5:1;
    unsigned int hasClientId:1;
    unsigned int hasMsgType:1;
    unsigned int hasMediaTime:1;
    unsigned int hasDataBuffer:1;
    unsigned int hasDataStartPos:1;
    unsigned int hasDataTotalLen:1;
    unsigned int hasThumbTotalLen:1;
    unsigned int hasThumbStartPos:1;
    unsigned int hasThumbData:1;
    unsigned int hasCameraType:1;
    unsigned int hasVideoSource:1;
    unsigned int hasToListCount:1;
    unsigned int hasIsSendAgain:1;
    unsigned int hasCompressType:1;
    unsigned int hasVoiceFormat:1;
    unsigned int hasVideoUrl:1;
    unsigned int hasThumbUrl:1;
    unsigned int hasThumbWidth:1;
    unsigned int hasThumbHeight:1;
    unsigned int hasThumbAeskey:1;
    unsigned int hasVideoAeskey:1;
    unsigned int hasMd5:1;
    unsigned int msgType;
    unsigned int mediaTime;
    unsigned int dataStartPos;
    unsigned int dataTotalLen;
    unsigned int thumbTotalLen;
    unsigned int thumbStartPos;
    unsigned int cameraType;
    unsigned int videoSource;
    unsigned int toListCount;
    unsigned int isSendAgain;
    unsigned int compressType;
    unsigned int voiceFormat;
    unsigned int thumbWidth;
    unsigned int thumbHeight;
    BaseRequest *baseRequest;
    NSString *toList;
    NSString *toListMd5;
    NSString *clientId;
    SKBuiltinBuffer_t *dataBuffer;
    SKBuiltinBuffer_t *thumbData;
    NSString *videoUrl;
    NSString *thumbUrl;
    NSString *thumbAeskey;
    NSString *videoAeskey;
    NSString *md5;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetMd5:) NSString *md5; // @synthesize md5;
@property(readonly, nonatomic) BOOL hasMd5; // @synthesize hasMd5;
@property(retain, nonatomic, setter=SetVideoAeskey:) NSString *videoAeskey; // @synthesize videoAeskey;
@property(readonly, nonatomic) BOOL hasVideoAeskey; // @synthesize hasVideoAeskey;
@property(retain, nonatomic, setter=SetThumbAeskey:) NSString *thumbAeskey; // @synthesize thumbAeskey;
@property(readonly, nonatomic) BOOL hasThumbAeskey; // @synthesize hasThumbAeskey;
@property(nonatomic, setter=SetThumbHeight:) unsigned int thumbHeight; // @synthesize thumbHeight;
@property(readonly, nonatomic) BOOL hasThumbHeight; // @synthesize hasThumbHeight;
@property(nonatomic, setter=SetThumbWidth:) unsigned int thumbWidth; // @synthesize thumbWidth;
@property(readonly, nonatomic) BOOL hasThumbWidth; // @synthesize hasThumbWidth;
@property(retain, nonatomic, setter=SetThumbUrl:) NSString *thumbUrl; // @synthesize thumbUrl;
@property(readonly, nonatomic) BOOL hasThumbUrl; // @synthesize hasThumbUrl;
@property(retain, nonatomic, setter=SetVideoUrl:) NSString *videoUrl; // @synthesize videoUrl;
@property(readonly, nonatomic) BOOL hasVideoUrl; // @synthesize hasVideoUrl;
@property(nonatomic, setter=SetVoiceFormat:) unsigned int voiceFormat; // @synthesize voiceFormat;
@property(readonly, nonatomic) BOOL hasVoiceFormat; // @synthesize hasVoiceFormat;
@property(nonatomic, setter=SetCompressType:) unsigned int compressType; // @synthesize compressType;
@property(readonly, nonatomic) BOOL hasCompressType; // @synthesize hasCompressType;
@property(nonatomic, setter=SetIsSendAgain:) unsigned int isSendAgain; // @synthesize isSendAgain;
@property(readonly, nonatomic) BOOL hasIsSendAgain; // @synthesize hasIsSendAgain;
@property(nonatomic, setter=SetToListCount:) unsigned int toListCount; // @synthesize toListCount;
@property(readonly, nonatomic) BOOL hasToListCount; // @synthesize hasToListCount;
@property(nonatomic, setter=SetVideoSource:) unsigned int videoSource; // @synthesize videoSource;
@property(readonly, nonatomic) BOOL hasVideoSource; // @synthesize hasVideoSource;
@property(nonatomic, setter=SetCameraType:) unsigned int cameraType; // @synthesize cameraType;
@property(readonly, nonatomic) BOOL hasCameraType; // @synthesize hasCameraType;
@property(retain, nonatomic, setter=SetThumbData:) SKBuiltinBuffer_t *thumbData; // @synthesize thumbData;
@property(readonly, nonatomic) BOOL hasThumbData; // @synthesize hasThumbData;
@property(nonatomic, setter=SetThumbStartPos:) unsigned int thumbStartPos; // @synthesize thumbStartPos;
@property(readonly, nonatomic) BOOL hasThumbStartPos; // @synthesize hasThumbStartPos;
@property(nonatomic, setter=SetThumbTotalLen:) unsigned int thumbTotalLen; // @synthesize thumbTotalLen;
@property(readonly, nonatomic) BOOL hasThumbTotalLen; // @synthesize hasThumbTotalLen;
@property(nonatomic, setter=SetDataTotalLen:) unsigned int dataTotalLen; // @synthesize dataTotalLen;
@property(readonly, nonatomic) BOOL hasDataTotalLen; // @synthesize hasDataTotalLen;
@property(nonatomic, setter=SetDataStartPos:) unsigned int dataStartPos; // @synthesize dataStartPos;
@property(readonly, nonatomic) BOOL hasDataStartPos; // @synthesize hasDataStartPos;
@property(retain, nonatomic, setter=SetDataBuffer:) SKBuiltinBuffer_t *dataBuffer; // @synthesize dataBuffer;
@property(readonly, nonatomic) BOOL hasDataBuffer; // @synthesize hasDataBuffer;
@property(nonatomic, setter=SetMediaTime:) unsigned int mediaTime; // @synthesize mediaTime;
@property(readonly, nonatomic) BOOL hasMediaTime; // @synthesize hasMediaTime;
@property(nonatomic, setter=SetMsgType:) unsigned int msgType; // @synthesize msgType;
@property(readonly, nonatomic) BOOL hasMsgType; // @synthesize hasMsgType;
@property(retain, nonatomic, setter=SetClientId:) NSString *clientId; // @synthesize clientId;
@property(readonly, nonatomic) BOOL hasClientId; // @synthesize hasClientId;
@property(retain, nonatomic, setter=SetToListMd5:) NSString *toListMd5; // @synthesize toListMd5;
@property(readonly, nonatomic) BOOL hasToListMd5; // @synthesize hasToListMd5;
@property(retain, nonatomic, setter=SetToList:) NSString *toList; // @synthesize toList;
@property(readonly, nonatomic) BOOL hasToList; // @synthesize hasToList;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

