//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "IIPxxExt.h"
#import "INewABTestMgrExt.h"

@class MemoryRecordInfo, MemoryStatConfig, MemoryStatReporter, NSRecursiveLock, NSString;

@interface MemoryStatManager : NSObject <INewABTestMgrExt, IIPxxExt>
{
    NSString *m_rootDir;
    NSString *m_dataDir;
    NSString *m_configPath;
    NSRecursiveLock *m_lock;
    MemoryStatConfig *m_config;
    MemoryRecordInfo *m_currRecord;
    MemoryRecordInfo *m_lastRecord;
    unsigned long long m_userType;
    BOOL m_isStartTracking;
    BOOL m_isTracking;
    MemoryStatReporter *m_reporter;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)onGetIpxxMsgContent:(id)arg1;
- (void)onModifyABTestItem:(id)arg1 bizId:(id)arg2 abTestItem:(id)arg3;
- (void)doIDKeyReport:(int)arg1 value:(int)arg2;
- (void)checkABTest:(BOOL)arg1;
- (void)MemoryStatOnForeground;
- (void)MemoryStatOnBackground;
- (void)handleMemoryWarnningNotification:(id)arg1;
- (void)onSignalCrash;
- (void)startTracking;
- (void)saveConfig;
- (void)clearUnnecessaryData;
- (void)loadConfig;
- (void)getlastFOOMThreadInfos;
- (void)removeCurrentThread;
- (void)addCurrentThreadToMonitor:(id)arg1;
- (void)uploadReportWithCurrentRecord;
- (void)uploadReport:(id)arg1;
- (id)recordList;
- (void)removeAllFullReport;
- (void)uploadAllFullReport;
- (BOOL)shouldEnterUploadReport;
- (void)setMemoryStatEnabled:(BOOL)arg1;
- (BOOL)isMemoryStatEnabled;
- (void)checkAndRecord;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

