//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "crashReportConnectionDelegate.h"

@class MMCrashReportConnection, MemoryReportTask, NSMutableArray, NSString;

@interface MemoryStatReporter : NSObject <crashReportConnectionDelegate>
{
    NSString *m_reportPath;
    NSString *m_configPath;
    NSString *m_zipName;
    MemoryReportTask *m_uploadTask[2];
    NSMutableArray *m_taskList;
    BOOL m_isAllReport;
    MMCrashReportConnection *m_connection;
    struct FullReportUploadObserver *m_observer;
}

- (void).cxx_destruct;
- (void)onReportUploadCompleted:(BOOL)arg1 reportType:(int)arg2;
- (void)onUploadCrashCompleted:(BOOL)arg1 CrashWrap:(id)arg2;
- (void)doFullReport:(id)arg1;
- (void)doSummaryReport:(id)arg1;
- (void)doNextReport:(int)arg1;
- (BOOL)hasNextTask:(int)arg1;
- (id)nextTask:(int)arg1;
- (id)currUsrName;
- (void)loadTasks;
- (void)saveTasks;
- (void)uploadAllFullReport;
- (void)uploadAllSummaryReport;
- (void)removeAllFullReport;
- (BOOL)hasFullReport;
- (void)addReportTask:(unsigned long long)arg1 dataPath:(id)arg2 foomScene:(id)arg3 reportType:(int)arg4;
- (void)addFullReportTask:(unsigned long long)arg1 dataPath:(id)arg2 foomScene:(id)arg3;
- (void)addSummaryReportTask:(unsigned long long)arg1 dataPath:(id)arg2 foomScene:(id)arg3;
- (id)initWithReportPath:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

