//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class MMTextAttachmentCell;

@interface MMAttachmentReusableView : NSView
{
    MMTextAttachmentCell *_attachmentCell;
    NSView *_containerView;
}

@property(retain, nonatomic) NSView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) MMTextAttachmentCell *attachmentCell; // @synthesize attachmentCell=_attachmentCell;
- (void).cxx_destruct;
- (id)initWithIdentifier:(id)arg1;

@end

