//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMChatLogBaseCellView.h"

@class MMImageView, NSString, NSTextField;

@interface MMChatLogWebPageCellView : MMChatLogBaseCellView
{
    MMImageView *_thumbnailImageView;
    NSTextField *_webPageDescriptionTextView;
    NSTextField *_webPageLinkUrlDescriptionTextView;
    NSString *_thumbImagePath;
}

+ (double)cellHeightWithFavItemDataField:(id)arg1 parentMessage:(id)arg2 parentFavItem:(id)arg3 parentDataField:(id)arg4 constrainedToWidth:(double)arg5;
@property(retain, nonatomic) NSString *thumbImagePath; // @synthesize thumbImagePath=_thumbImagePath;
@property(retain, nonatomic) NSTextField *webPageLinkUrlDescriptionTextView; // @synthesize webPageLinkUrlDescriptionTextView=_webPageLinkUrlDescriptionTextView;
@property(retain, nonatomic) NSTextField *webPageDescriptionTextView; // @synthesize webPageDescriptionTextView=_webPageDescriptionTextView;
@property(retain, nonatomic) MMImageView *thumbnailImageView; // @synthesize thumbnailImageView=_thumbnailImageView;
- (void).cxx_destruct;
- (void)layoutThumbnail;
- (void)layoutWebPageInfo;
- (id)initWithFrame:(struct CGRect)arg1;

@end

