//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "IContactMgrExt.h"
#import "IGroupMgrExt.h"
#import "MMCollectionDelegate.h"
#import "MMMessageCellViewDelegate.h"
#import "MMPreviewPanelUIMgrDelegate.h"
#import "MMTableViewDelegate.h"
#import "MMViewerWindowDelegate.h"
#import "MessageBatchExportMgrExt.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class CAShapeLayer, MMBatchExportViewWindow, MMButton, MMChatCollectionViewController, MMChatFTSSearchLogic, MMChatManagerDataSource, MMMessageScrollView, MMMessageSendLogic, MMMessageTableItem, MMTableView, MMTextField, MMTimer, MMView, NSButton, NSImageView, NSMutableArray, NSProgressIndicator, NSString, NSTextField, NSView, WCContactData;

@interface MMChatManagerDetailViewController : NSViewController <NSTableViewDataSource, NSTableViewDelegate, MMTableViewDelegate, MMMessageCellViewDelegate, MMViewerWindowDelegate, IContactMgrExt, IGroupMgrExt, MMPreviewPanelUIMgrDelegate, MMCollectionDelegate, MessageBatchExportMgrExt>
{
    BOOL _multiSelectionMode;
    unsigned char _isGlobalSearch;
    BOOL _isLoadingHistory;
    BOOL _isFromGlobalSearch;
    BOOL _beginDragging;
    MMChatFTSSearchLogic *_ftsSearchLogic;
    CDUnknownBlockType _viewDidLoadBlock;
    CDUnknownBlockType _searchDidFinishBlock;
    CDUnknownBlockType _brandChatNameClickBlock;
    WCContactData *_chatContact;
    NSString *_nsKeyword;
    NSMutableArray *_sessionInfoArray;
    MMMessageScrollView *_messageScrollView;
    MMTableView *_messageTableView;
    MMMessageScrollView *_searchResultsScrollView;
    MMTableView *_searchResultsTableView;
    MMMessageScrollView *_currentScrollView;
    MMTableView *_currentTableView;
    NSView *_collectionView;
    MMChatCollectionViewController *_collectionViewController;
    NSProgressIndicator *_loadingProgressIndicator;
    NSView *_noRecordsView;
    NSImageView *_noRecordsImageView;
    NSTextField *_noRecordsLabel;
    NSTextField *_recordsCountLabel;
    NSView *_backView;
    MMView *_back;
    NSButton *_backButton;
    MMTextField *_backLabel;
    NSView *_tabButtonContainer;
    MMButton *_allButton;
    MMButton *_photoButton;
    MMButton *_fileButton;
    MMButton *_linkButton;
    NSView *_globalTabButtonContainer;
    MMView *_globalOpenChatView;
    MMButton *_globalOpenChatButton;
    MMTextField *_allLabel;
    MMTextField *_photoLabel;
    MMTextField *_fileLabel;
    MMTextField *_linkLabel;
    NSTextField *_globalAllLabel;
    MMTextField *_globalOpenChatLabel;
    MMView *_all;
    MMView *_photo;
    MMView *_file;
    MMView *_link;
    MMView *_multipleSelectView;
    NSView *_multipleButtonContainer;
    NSTextField *_forwardLabel;
    NSTextField *_mergeForwardLabel;
    NSTextField *_addFavoritesLabel;
    NSTextField *_saveLabel;
    NSTextField *_deleteLabel;
    MMBatchExportViewWindow *_exportViewWindow;
    MMChatManagerDataSource *_currentDataSource;
    MMChatManagerDataSource *_messageDataSource;
    MMChatManagerDataSource *_locateMsgDataSource;
    MMMessageSendLogic *_messageSendLogic;
    MMTimer *_scrollDelaytimer;
    unsigned long long _currentMode;
    unsigned long long _mediaType;
    MMTimer *_timer;
    unsigned long long _lastCalledTime;
    CAShapeLayer *_shapeLayer;
    MMMessageTableItem *_preSelectedTableItem;
    id _mouseEvent;
    NSView *_searchDetailContainerView;
    struct CGPoint _eventPoint;
    struct CGPoint _dragStartPoint;
    struct CGRect _draggedRect;
}

@property __weak NSView *searchDetailContainerView; // @synthesize searchDetailContainerView=_searchDetailContainerView;
@property(retain, nonatomic) id mouseEvent; // @synthesize mouseEvent=_mouseEvent;
@property(nonatomic) BOOL beginDragging; // @synthesize beginDragging=_beginDragging;
@property(retain, nonatomic) MMMessageTableItem *preSelectedTableItem; // @synthesize preSelectedTableItem=_preSelectedTableItem;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(nonatomic) struct CGRect draggedRect; // @synthesize draggedRect=_draggedRect;
@property(nonatomic) struct CGPoint dragStartPoint; // @synthesize dragStartPoint=_dragStartPoint;
@property(nonatomic) struct CGPoint eventPoint; // @synthesize eventPoint=_eventPoint;
@property BOOL isFromGlobalSearch; // @synthesize isFromGlobalSearch=_isFromGlobalSearch;
@property(nonatomic) unsigned long long lastCalledTime; // @synthesize lastCalledTime=_lastCalledTime;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) unsigned long long mediaType; // @synthesize mediaType=_mediaType;
@property(nonatomic) unsigned long long currentMode; // @synthesize currentMode=_currentMode;
@property BOOL isLoadingHistory; // @synthesize isLoadingHistory=_isLoadingHistory;
@property(retain, nonatomic) MMTimer *scrollDelaytimer; // @synthesize scrollDelaytimer=_scrollDelaytimer;
@property(retain, nonatomic) MMMessageSendLogic *messageSendLogic; // @synthesize messageSendLogic=_messageSendLogic;
@property(retain, nonatomic) MMChatManagerDataSource *locateMsgDataSource; // @synthesize locateMsgDataSource=_locateMsgDataSource;
@property(retain, nonatomic) MMChatManagerDataSource *messageDataSource; // @synthesize messageDataSource=_messageDataSource;
@property(retain, nonatomic) MMChatManagerDataSource *currentDataSource; // @synthesize currentDataSource=_currentDataSource;
@property(retain, nonatomic) MMBatchExportViewWindow *exportViewWindow; // @synthesize exportViewWindow=_exportViewWindow;
@property __weak NSTextField *deleteLabel; // @synthesize deleteLabel=_deleteLabel;
@property __weak NSTextField *saveLabel; // @synthesize saveLabel=_saveLabel;
@property __weak NSTextField *addFavoritesLabel; // @synthesize addFavoritesLabel=_addFavoritesLabel;
@property __weak NSTextField *mergeForwardLabel; // @synthesize mergeForwardLabel=_mergeForwardLabel;
@property __weak NSTextField *forwardLabel; // @synthesize forwardLabel=_forwardLabel;
@property __weak NSView *multipleButtonContainer; // @synthesize multipleButtonContainer=_multipleButtonContainer;
@property __weak MMView *multipleSelectView; // @synthesize multipleSelectView=_multipleSelectView;
@property __weak MMView *link; // @synthesize link=_link;
@property __weak MMView *file; // @synthesize file=_file;
@property __weak MMView *photo; // @synthesize photo=_photo;
@property __weak MMView *all; // @synthesize all=_all;
@property __weak MMTextField *globalOpenChatLabel; // @synthesize globalOpenChatLabel=_globalOpenChatLabel;
@property __weak NSTextField *globalAllLabel; // @synthesize globalAllLabel=_globalAllLabel;
@property __weak MMTextField *linkLabel; // @synthesize linkLabel=_linkLabel;
@property __weak MMTextField *fileLabel; // @synthesize fileLabel=_fileLabel;
@property __weak MMTextField *photoLabel; // @synthesize photoLabel=_photoLabel;
@property __weak MMTextField *allLabel; // @synthesize allLabel=_allLabel;
@property __weak MMButton *globalOpenChatButton; // @synthesize globalOpenChatButton=_globalOpenChatButton;
@property __weak MMView *globalOpenChatView; // @synthesize globalOpenChatView=_globalOpenChatView;
@property __weak NSView *globalTabButtonContainer; // @synthesize globalTabButtonContainer=_globalTabButtonContainer;
@property __weak MMButton *linkButton; // @synthesize linkButton=_linkButton;
@property __weak MMButton *fileButton; // @synthesize fileButton=_fileButton;
@property __weak MMButton *photoButton; // @synthesize photoButton=_photoButton;
@property __weak MMButton *allButton; // @synthesize allButton=_allButton;
@property __weak NSView *tabButtonContainer; // @synthesize tabButtonContainer=_tabButtonContainer;
@property __weak MMTextField *backLabel; // @synthesize backLabel=_backLabel;
@property __weak NSButton *backButton; // @synthesize backButton=_backButton;
@property __weak MMView *back; // @synthesize back=_back;
@property __weak NSView *backView; // @synthesize backView=_backView;
@property(nonatomic) __weak NSTextField *recordsCountLabel; // @synthesize recordsCountLabel=_recordsCountLabel;
@property(nonatomic) __weak NSTextField *noRecordsLabel; // @synthesize noRecordsLabel=_noRecordsLabel;
@property(nonatomic) __weak NSImageView *noRecordsImageView; // @synthesize noRecordsImageView=_noRecordsImageView;
@property(nonatomic) __weak NSView *noRecordsView; // @synthesize noRecordsView=_noRecordsView;
@property(retain, nonatomic) NSProgressIndicator *loadingProgressIndicator; // @synthesize loadingProgressIndicator=_loadingProgressIndicator;
@property(retain, nonatomic) MMChatCollectionViewController *collectionViewController; // @synthesize collectionViewController=_collectionViewController;
@property(nonatomic) __weak NSView *collectionView; // @synthesize collectionView=_collectionView;
@property(retain, nonatomic) MMTableView *currentTableView; // @synthesize currentTableView=_currentTableView;
@property(retain, nonatomic) MMMessageScrollView *currentScrollView; // @synthesize currentScrollView=_currentScrollView;
@property(retain, nonatomic) MMTableView *searchResultsTableView; // @synthesize searchResultsTableView=_searchResultsTableView;
@property(retain, nonatomic) MMMessageScrollView *searchResultsScrollView; // @synthesize searchResultsScrollView=_searchResultsScrollView;
@property(retain, nonatomic) MMTableView *messageTableView; // @synthesize messageTableView=_messageTableView;
@property(retain, nonatomic) MMMessageScrollView *messageScrollView; // @synthesize messageScrollView=_messageScrollView;
@property(retain, nonatomic) NSMutableArray *sessionInfoArray; // @synthesize sessionInfoArray=_sessionInfoArray;
@property(nonatomic) unsigned char isGlobalSearch; // @synthesize isGlobalSearch=_isGlobalSearch;
@property(retain, nonatomic) NSString *nsKeyword; // @synthesize nsKeyword=_nsKeyword;
@property(retain, nonatomic) WCContactData *chatContact; // @synthesize chatContact=_chatContact;
@property(copy, nonatomic) CDUnknownBlockType brandChatNameClickBlock; // @synthesize brandChatNameClickBlock=_brandChatNameClickBlock;
@property(copy, nonatomic) CDUnknownBlockType searchDidFinishBlock; // @synthesize searchDidFinishBlock=_searchDidFinishBlock;
@property(copy, nonatomic) CDUnknownBlockType viewDidLoadBlock; // @synthesize viewDidLoadBlock=_viewDidLoadBlock;
@property(nonatomic) BOOL multiSelectionMode; // @synthesize multiSelectionMode=_multiSelectionMode;
@property(retain, nonatomic) MMChatFTSSearchLogic *ftsSearchLogic; // @synthesize ftsSearchLogic=_ftsSearchLogic;
- (void).cxx_destruct;
- (void)handleAppFontSize;
- (void)locateMsgInRealChat:(id)arg1 mesLocalID:(unsigned int)arg2;
- (BOOL)validateProposedFirstResponder:(id)arg1 forEvent:(id)arg2;
- (id)title;
- (void)loadMoreChatHistory;
- (void)doScrollViewBoundsDidChanged;
- (void)onScrollViewBoundsDidChanged:(id)arg1;
- (void)OnChangeMemberShowDisplayName:(id)arg1;
- (void)onModifyContacts:(id)arg1;
- (struct CGRect)originScreenRectForAnimationForWindow:(id)arg1;
- (void)windowDidColsed:(id)arg1;
- (struct CGRect)previewPanel:(id)arg1 sourceFrameOnScreenForPreviewItem:(id)arg2;
- (void)OnBatchExportFinishedWithTotalFileCount:(unsigned long long)arg1 failedMsgList:(id)arg2 reasons:(id)arg3;
- (void)OnBatchExportProgressWithMessage:(id)arg1 totalFileCount:(unsigned long long)arg2 finishedFileCount:(unsigned long long)arg3 shouldShowExportProgress:(BOOL)arg4;
- (id)getMultiSelectedMessageTableItems;
- (id)getMultiSelectedMessages;
- (void)layoutForMultiSelection:(BOOL)arg1;
- (void)mouseDragMultiSelectedCellView;
- (void)handleEventDuringDragging:(id)arg1;
- (void)handleEventBeforeDragging:(id)arg1;
- (BOOL)locationInsideMessageCellView:(struct CGPoint)arg1;
- (BOOL)locationInsideContentView:(struct CGPoint)arg1;
- (BOOL)dragFarEnough:(struct CGPoint)arg1 from:(struct CGPoint)arg2;
- (void)onBackClicked:(id)arg1;
- (void)onGlobalOpenChatClicked:(id)arg1;
- (void)onLinkClicked:(id)arg1;
- (void)onFileClicked:(id)arg1;
- (void)onPhotoClicked:(id)arg1;
- (void)onAllClicked:(id)arg1;
- (void)copySelectedMessageContent;
- (void)keyDown:(id)arg1;
- (void)SaveMutipleSelect;
- (void)ForwardMutipleSelect:(BOOL)arg1;
- (void)CloseMultipleSelect:(id)arg1;
- (void)DeleteByMultipleSelect:(id)arg1;
- (void)SaveByMultipleSelect:(id)arg1;
- (void)AddFavoritesByMultipleSelect:(id)arg1;
- (void)ForwardByMergeMutipleSelect:(id)arg1;
- (void)ForwardByMultipleSelect:(id)arg1;
- (void)toggleMultiSelectionView:(BOOL)arg1;
- (id)searchDataSource;
- (BOOL)isSearchingMode;
- (void)messageCellView:(id)arg1 didClickOutsideClickableArea:(id)arg2;
- (void)locateResult:(id)arg1;
- (void)messageCellViewLocateMessage:(id)arg1 mesLocalID:(unsigned int)arg2;
- (double)messageCellViewMultiSelectionLeftPadding:(id)arg1;
- (BOOL)messageCellViewIsMultiSelectionMode:(id)arg1;
- (double)messageCellViewNeedsContainerWidth;
- (void)messageCellView:(id)arg1 didClickOnAvatarWithItem:(id)arg2;
- (void)messageCellView:(id)arg1 didDoubleClickOnAvatarWithItem:(id)arg2;
- (void)messageCellViewDidStartForwardMessageCommand:(id)arg1;
- (void)messageCellViewNeedsReload:(id)arg1;
- (void)messageCellViewNeedsHeightRecalculated:(id)arg1;
- (void)messageCellView:(id)arg1 didUpdatePreviewContentWithItem:(id)arg2;
- (void)messageCellView:(id)arg1 showDetailWindowWithItem:(id)arg2;
- (void)messageCellView:(id)arg1 multiSelectWithEvent:(id)arg2;
- (void)messageCellViewDidStartMultiSelection:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (BOOL)tableView:(id)arg1 shouldSelectRow:(long long)arg2;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)clearSearch;
- (void)doSearch;
- (void)performSearch:(id)arg1;
- (void)performSearchFromGlobal:(id)arg1;
- (id)slideFromLeftAnimation;
- (id)slideFromRightAnimation;
- (id)getGlobalSearchResultForChatName:(id)arg1;
- (id)getGlobalSearchSessionsResult;
- (void)reloadData;
- (void)setTabChosen:(id)arg1 label:(id)arg2;
- (void)shouldShowRecordsCount;
- (void)shouldShowNoRecordsView;
- (void)showLinks;
- (void)showFiles;
- (void)showPhotos;
- (void)showMessages;
- (void)hideProgressIndicator;
- (void)showProgressIndicator;
- (void)setupProgressIndicator;
- (void)hideRecordsCount;
- (void)showRecordsCount:(unsigned long long)arg1;
- (void)hideNoRecordsView;
- (void)showGlobalNoRecordsView;
- (void)showNoRecordsView;
- (void)setupBackView;
- (void)setupTabButtons;
- (void)setupMultipleSelectView;
- (void)setupCollectionView;
- (void)setupSearchResultTableView;
- (void)setupTableView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

