//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSImage, NSString;

@protocol MMChatManagerCacheExt <NSObject>

@optional
- (void)hdThumbImageDidLoadWithUniqueID:(NSString *)arg1 image:(NSImage *)arg2;
- (void)thumbImageDidLoadWithUniqueID:(NSString *)arg1 image:(NSImage *)arg2;
@end

