//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTableDataSource.h"

#import "IGroupMgrExt.h"
#import "IMessageExt.h"

@class NSArray, NSDictionary, NSMutableArray, NSString;

@interface MMChatManagerDataSource : MMTableDataSource <IGroupMgrExt, IMessageExt>
{
    vector_a9c0768e messageTypes;
    BOOL _isFullyCached;
    BOOL _isSearchingResults;
    BOOL _ascendOrder;
    BOOL _isGlobalFullyCached;
    unsigned int _msgPageSize;
    unsigned int _lastMesLocalId;
    unsigned int _previousMesLocalID;
    unsigned int _followingMesLocalID;
    NSString *_chatName;
    NSMutableArray *_messages;
    NSArray *_searchKeyword;
    NSDictionary *_dicResults;
    NSDictionary *_dicGlobalResults;
    NSMutableArray *_dicSessionResults;
    NSMutableArray *_groups;
    CDUnknownBlockType _messageFilter;
    unsigned long long _grouping;
    NSMutableArray *_collection;
    CDUnknownBlockType _didRemoveMessageBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didRemoveMessageBlock; // @synthesize didRemoveMessageBlock=_didRemoveMessageBlock;
@property(nonatomic) unsigned int followingMesLocalID; // @synthesize followingMesLocalID=_followingMesLocalID;
@property(nonatomic) unsigned int previousMesLocalID; // @synthesize previousMesLocalID=_previousMesLocalID;
@property(nonatomic) BOOL isGlobalFullyCached; // @synthesize isGlobalFullyCached=_isGlobalFullyCached;
@property(retain, nonatomic) NSMutableArray *collection; // @synthesize collection=_collection;
@property(nonatomic) unsigned long long grouping; // @synthesize grouping=_grouping;
@property(copy, nonatomic) CDUnknownBlockType messageFilter; // @synthesize messageFilter=_messageFilter;
@property(retain, nonatomic) NSMutableArray *groups; // @synthesize groups=_groups;
@property(nonatomic) BOOL ascendOrder; // @synthesize ascendOrder=_ascendOrder;
@property(retain, nonatomic) NSMutableArray *dicSessionResults; // @synthesize dicSessionResults=_dicSessionResults;
@property(retain, nonatomic) NSDictionary *dicGlobalResults; // @synthesize dicGlobalResults=_dicGlobalResults;
@property(retain, nonatomic) NSDictionary *dicResults; // @synthesize dicResults=_dicResults;
@property(retain, nonatomic) NSArray *searchKeyword; // @synthesize searchKeyword=_searchKeyword;
@property(nonatomic) BOOL isSearchingResults; // @synthesize isSearchingResults=_isSearchingResults;
@property(nonatomic) BOOL isFullyCached; // @synthesize isFullyCached=_isFullyCached;
@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
@property(nonatomic) unsigned int lastMesLocalId; // @synthesize lastMesLocalId=_lastMesLocalId;
@property(nonatomic) unsigned int msgPageSize; // @synthesize msgPageSize=_msgPageSize;
@property(retain, nonatomic) NSString *chatName; // @synthesize chatName=_chatName;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onDelMsg:(id)arg1 msgData:(id)arg2;
- (void)OnChangeMemberShowDisplayName:(id)arg1;
- (long long)indexOfLocalID:(unsigned int)arg1;
- (void)loadMessageMessageUpwards;
- (void)loadMessageMessageDownwards;
- (void)loadMessagesAroundLocalID:(unsigned int)arg1;
- (id)collectionItemsWithMessages:(id)arg1;
- (unsigned long long)numberOfMessagesInAllGroups;
- (id)titleForGroup:(unsigned long long)arg1;
- (unsigned long long)numberOfMessagesInGroup:(unsigned long long)arg1;
- (id)messageAtRow:(unsigned long long)arg1 forGroup:(unsigned long long)arg2;
- (unsigned long long)numberOfGroups;
- (id)groupsWithMessages:(id)arg1;
- (void)setGrouping:(unsigned long long)arg1 messageFilter:(CDUnknownBlockType)arg2;
- (BOOL)shouldInsertTimeStampWithNewMessage:(id)arg1 lastTimeStamp:(unsigned int)arg2;
- (id)indexPathForItemLocalID:(unsigned int)arg1;
- (id)messageTableItemWithMessage:(id)arg1;
- (unsigned long long)indexOfTableItemWithUniqueId:(id)arg1;
- (unsigned long long)indexOfTableItemWithMessage:(id)arg1;
- (void)appendItemsWithMessages:(id)arg1 appendTail:(BOOL)arg2;
- (void)loadGlobalMessagesWithChatName:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadMessagesWithCompletion:(CDUnknownBlockType)arg1;
- (void)loadMessageOfNextPageWithCompletion:(CDUnknownBlockType)arg1;
- (void)loadGlobalMessageOfNextPageWithCompletion:(CDUnknownBlockType)arg1;
- (id)getCachedMessagesAtPageIndex:(unsigned int)arg1;
- (void)setupWithChatName:(id)arg1 messages:(id)arg2;
- (void)clearData;
- (void)dealloc;
- (id)initMessageTypes:(vector_a9c0768e)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

