//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMChatManagerDataSource, NSMutableArray, NSString;

@interface MMChatBaseSearchLogic : NSObject
{
    unsigned int _uiMessageType;
    unsigned int _uiMinMsgCreateTime;
    unsigned int _uiMaxMsgCreateTime;
    unsigned int _uiLimitCount;
    unsigned int _lastMesLocalId;
    NSString *_nsKeyword;
    NSString *_nsChatName;
    NSString *_nsRealFromUser;
    CDUnknownBlockType _completionBlock;
    NSMutableArray *_results;
    MMChatManagerDataSource *_resultsDataSource;
}

@property(retain, nonatomic) MMChatManagerDataSource *resultsDataSource; // @synthesize resultsDataSource=_resultsDataSource;
@property(retain, nonatomic) NSMutableArray *results; // @synthesize results=_results;
@property(nonatomic) unsigned int lastMesLocalId; // @synthesize lastMesLocalId=_lastMesLocalId;
@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(nonatomic) unsigned int uiLimitCount; // @synthesize uiLimitCount=_uiLimitCount;
@property(nonatomic) unsigned int uiMaxMsgCreateTime; // @synthesize uiMaxMsgCreateTime=_uiMaxMsgCreateTime;
@property(nonatomic) unsigned int uiMinMsgCreateTime; // @synthesize uiMinMsgCreateTime=_uiMinMsgCreateTime;
@property(nonatomic) unsigned int uiMessageType; // @synthesize uiMessageType=_uiMessageType;
@property(retain, nonatomic) NSString *nsRealFromUser; // @synthesize nsRealFromUser=_nsRealFromUser;
@property(retain, nonatomic) NSString *nsChatName; // @synthesize nsChatName=_nsChatName;
@property(retain, nonatomic) NSString *nsKeyword; // @synthesize nsKeyword=_nsKeyword;
- (void).cxx_destruct;
- (void)clearSearch;
- (void)fetchMoreResults;
- (void)doSearchWithKeyword:(id)arg1 chatName:(id)arg2 realFromUser:(id)arg3 messageType:(unsigned int)arg4 minMsgCreateTime:(unsigned int)arg5 maxMsgCreateTime:(unsigned int)arg6 limitCount:(unsigned int)arg7 completion:(CDUnknownBlockType)arg8;
- (id)init;

@end

