//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate;

@interface MMComplexContactSearchTask : NSObject
{
    BOOL _isCancelled;
    NSDate *_createDate;
}

@property BOOL isCancelled; // @synthesize isCancelled=_isCancelled;
@property(retain, nonatomic) NSDate *createDate; // @synthesize createDate=_createDate;
- (void).cxx_destruct;
- (BOOL)_isValidContact:(id)arg1;
- (void)doComplexContactSearch:(id)arg1 allSessionInfo:(id)arg2 allContacts:(id)arg3 allGroups:(id)arg4 searchScene:(unsigned long long)arg5 complete:(CDUnknownBlockType)arg6;
- (void)cancel;
- (id)init;

@end

