//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "AccountServiceExt.h"
#import "IContactMgrExt.h"
#import "IGroupMgrExt.h"
#import "MMViewerWindowDelegate.h"
#import "NSTextFieldDelegate.h"

@class MMAvatarImageView, MMCTTextView, MMDivider, MMView, NSArray, NSButton, NSData, NSImageView, NSMutableArray, NSString, NSTextField, NSView, NSVisualEffectView, NSWindow, RBLPopover, RBLPopoverBackgroundView, WCContactData;

@interface MMContactInspector : MMViewController <IContactMgrExt, IGroupMgrExt, MMViewerWindowDelegate, NSTextFieldDelegate, AccountServiceExt>
{
    NSData *m_kvRowPrototype;
    RBLPopover *m_rblPopover;
    RBLPopoverBackgroundView *m_backgroundView;
    MMView *m_whiteColorbgView;
    int _macKeyLabelWidth;
    MMAvatarImageView *_avatarView;
    MMCTTextView *_nickNameTextView;
    NSTextField *_subTitleTextField;
    NSView *_keyValueRow;
    NSView *_friendBottomButtons;
    NSView *_nonFriendBottomButtons;
    NSButton *_messageButton;
    NSButton *_addToContactButton;
    NSButton *_shareButton;
    NSImageView *_genderView;
    MMDivider *_divider;
    NSTextField *_oaNameTextField;
    MMCTTextView *_oaSignatureTextView;
    WCContactData *_contact;
    NSString *_groupChatUserName;
    NSArray *_dataRowViews;
    NSView *_bottomButtons;
    NSVisualEffectView *_visualEffectView;
    NSTextField *_remarkInputTextField;
    NSString *_originUserName;
    NSWindow *_parentWindow;
    unsigned long long _accountType;
    NSMutableArray *_keyLabelList;
    NSMutableArray *_valueLabelList;
}

+ (id)sharedInspector;
@property(retain, nonatomic) NSMutableArray *valueLabelList; // @synthesize valueLabelList=_valueLabelList;
@property(retain, nonatomic) NSMutableArray *keyLabelList; // @synthesize keyLabelList=_keyLabelList;
@property(nonatomic) int macKeyLabelWidth; // @synthesize macKeyLabelWidth=_macKeyLabelWidth;
@property(nonatomic) unsigned long long accountType; // @synthesize accountType=_accountType;
@property(nonatomic) __weak NSWindow *parentWindow; // @synthesize parentWindow=_parentWindow;
@property(retain, nonatomic) NSString *originUserName; // @synthesize originUserName=_originUserName;
@property(retain, nonatomic) NSTextField *remarkInputTextField; // @synthesize remarkInputTextField=_remarkInputTextField;
@property(retain, nonatomic) NSVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
@property(retain, nonatomic) NSView *bottomButtons; // @synthesize bottomButtons=_bottomButtons;
@property(retain, nonatomic) NSArray *dataRowViews; // @synthesize dataRowViews=_dataRowViews;
@property(retain, nonatomic) NSString *groupChatUserName; // @synthesize groupChatUserName=_groupChatUserName;
@property(retain, nonatomic) WCContactData *contact; // @synthesize contact=_contact;
@property(retain, nonatomic) MMCTTextView *oaSignatureTextView; // @synthesize oaSignatureTextView=_oaSignatureTextView;
@property(retain, nonatomic) NSTextField *oaNameTextField; // @synthesize oaNameTextField=_oaNameTextField;
@property(retain, nonatomic) MMDivider *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) NSImageView *genderView; // @synthesize genderView=_genderView;
@property(retain, nonatomic) NSButton *shareButton; // @synthesize shareButton=_shareButton;
@property(retain, nonatomic) NSButton *addToContactButton; // @synthesize addToContactButton=_addToContactButton;
@property(retain, nonatomic) NSButton *messageButton; // @synthesize messageButton=_messageButton;
@property(retain, nonatomic) NSView *nonFriendBottomButtons; // @synthesize nonFriendBottomButtons=_nonFriendBottomButtons;
@property(retain, nonatomic) NSView *friendBottomButtons; // @synthesize friendBottomButtons=_friendBottomButtons;
@property(retain, nonatomic) NSView *keyValueRow; // @synthesize keyValueRow=_keyValueRow;
@property(retain, nonatomic) NSTextField *subTitleTextField; // @synthesize subTitleTextField=_subTitleTextField;
@property(retain, nonatomic) MMCTTextView *nickNameTextView; // @synthesize nickNameTextView=_nickNameTextView;
@property(retain, nonatomic) MMAvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
- (void).cxx_destruct;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)controlTextDidChange:(id)arg1;
- (void)OnModifyGroupMemberContact:(id)arg1;
- (void)onModifyContacts:(id)arg1;
- (void)windowDidColsed;
- (struct CGRect)originScreenRectForAnimationForWindow:(id)arg1;
- (void)shareContactCard:(id)arg1;
- (void)enlargeProfilePhoto:(id)arg1;
- (void)addContactAsFriend:(id)arg1;
- (void)callContact:(id)arg1;
- (void)messageContact:(id)arg1;
- (void)adjustPopoverWindowFrame:(double)arg1;
- (void)layoutOfficialAccountProfile;
- (id)_baseTextAttributesWithSize:(double)arg1;
- (id)_formatNickNameText:(id)arg1;
- (void)layoutPersonalAccountProfile;
- (id)_newRemarkViewWithPlaceholderString:(id)arg1;
- (void)_clearKeyValueRows;
- (void)_adjustKeyValueRows;
- (id)_newRowViewWithKeyText:(id)arg1 valueText:(id)arg2;
- (void)_layoutProfile;
- (void)_populateFromContact;
- (BOOL)isShown;
- (void)hide;
- (void)toggleInView:(id)arg1 withContact:(id)arg2 inGroupChat:(id)arg3 preferredEdge:(unsigned long long)arg4 edgeInsets:(struct NSEdgeInsets)arg5;
- (void)toggleInView:(id)arg1 withContact:(id)arg2 preferredEdge:(unsigned long long)arg3 edgeInsets:(struct NSEdgeInsets)arg4;
- (void)showRelativeToRect:(struct CGRect)arg1 ofView:(id)arg2 withContact:(id)arg3 inGroupChat:(id)arg4 preferredEdge:(unsigned long long)arg5 accountType:(unsigned long long)arg6;
- (void)onUserLogout;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)viewWillAppear;
- (void)viewDidLoad;
- (void)viewDidDisappear;
- (void)destroy;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

