//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTextView.h"

#import "MMMentionViewControllerDelegate.h"
#import "NSMenuDelegate.h"
#import "NSTextStorageDelegate.h"
#import "NSTextViewDelegate.h"

@class MMEmotionPromptWindowController, MMMentionViewController, MMTimeChecker, NSMutableArray, NSString;

@interface MMComposeTextView : NSTextView <NSTextViewDelegate, MMMentionViewControllerDelegate, NSTextStorageDelegate, NSMenuDelegate>
{
    BOOL _shouldCaptureNewlineEvent;
    int _sendMsgShortCutType;
    MMEmotionPromptWindowController *_emotionPromptWindowController;
    id <MMComposeTextViewDelegate> _mmDelegate;
    CDUnknownBlockType _didClickSendBlock;
    CDUnknownBlockType _didPasteFilesBlock;
    CDUnknownBlockType _didConfirmForwardMessageBlock;
    CDUnknownBlockType _didConfirmForwardFavoritesItemBlock;
    CDUnknownBlockType _didDragContactBlock;
    CDUnknownBlockType _didHandleEscapeKeyEventBlock;
    NSMutableArray *_mentionTokenRanges;
    NSMutableArray *_mentionUserList;
    NSString *_groupChatUserName;
    MMMentionViewController *_mentionViewController;
    unsigned long long _lastCheckTime;
    MMTimeChecker *_timeChecker;
    struct _NSRange _mentionMatchedRange;
}

+ (id)preprocessTextAttributes:(id)arg1;
+ (id)getFontSizeAdjustTextAttributes;
+ (id)_textEntryParagraphStyle;
@property(retain, nonatomic) MMTimeChecker *timeChecker; // @synthesize timeChecker=_timeChecker;
@property(nonatomic) unsigned long long lastCheckTime; // @synthesize lastCheckTime=_lastCheckTime;
@property(retain, nonatomic) MMMentionViewController *mentionViewController; // @synthesize mentionViewController=_mentionViewController;
@property(retain, nonatomic) NSString *groupChatUserName; // @synthesize groupChatUserName=_groupChatUserName;
@property(retain, nonatomic) NSMutableArray *mentionUserList; // @synthesize mentionUserList=_mentionUserList;
@property(nonatomic) struct _NSRange mentionMatchedRange; // @synthesize mentionMatchedRange=_mentionMatchedRange;
@property(retain, nonatomic) NSMutableArray *mentionTokenRanges; // @synthesize mentionTokenRanges=_mentionTokenRanges;
@property(nonatomic) BOOL shouldCaptureNewlineEvent; // @synthesize shouldCaptureNewlineEvent=_shouldCaptureNewlineEvent;
@property(nonatomic) int sendMsgShortCutType; // @synthesize sendMsgShortCutType=_sendMsgShortCutType;
@property(copy, nonatomic) CDUnknownBlockType didHandleEscapeKeyEventBlock; // @synthesize didHandleEscapeKeyEventBlock=_didHandleEscapeKeyEventBlock;
@property(copy, nonatomic) CDUnknownBlockType didDragContactBlock; // @synthesize didDragContactBlock=_didDragContactBlock;
@property(copy, nonatomic) CDUnknownBlockType didConfirmForwardFavoritesItemBlock; // @synthesize didConfirmForwardFavoritesItemBlock=_didConfirmForwardFavoritesItemBlock;
@property(copy, nonatomic) CDUnknownBlockType didConfirmForwardMessageBlock; // @synthesize didConfirmForwardMessageBlock=_didConfirmForwardMessageBlock;
@property(copy, nonatomic) CDUnknownBlockType didPasteFilesBlock; // @synthesize didPasteFilesBlock=_didPasteFilesBlock;
@property(copy, nonatomic) CDUnknownBlockType didClickSendBlock; // @synthesize didClickSendBlock=_didClickSendBlock;
@property(nonatomic) __weak id <MMComposeTextViewDelegate> mmDelegate; // @synthesize mmDelegate=_mmDelegate;
@property(retain, nonatomic) MMEmotionPromptWindowController *emotionPromptWindowController; // @synthesize emotionPromptWindowController=_emotionPromptWindowController;
- (void).cxx_destruct;
- (void)shouldShowEmotionPrompt;
- (void)mentionViewController:(id)arg1 didChooseContact:(id)arg2;
- (void)_doCheckIfSelectedRangeInMentionTokenRanges;
- (void)_checkIfSelectedRangeInMentionTokenRanges;
- (void)_checkMentionString;
- (void)updateMentionDataWithGroupChatContact:(id)arg1;
- (BOOL)becomeFirstResponder;
- (BOOL)resignFirstResponder;
- (void)viewWillStartLiveResize;
- (void)handleForwardMessage:(id)arg1;
- (void)handleForwardFavorites:(id)arg1;
- (void)insertContentData:(id)arg1;
- (id)currentContentData;
- (id)mentionTextCellEscapedAttributedString:(id)arg1;
- (void)SettingsDidChangeSendMessageShortcut;
- (void)pasteFileURLWithItems:(id)arg1 names:(id)arg2 type:(id)arg3;
- (void)pasteImageWithItem:(id)arg1 type:(id)arg2;
- (unsigned char)pastePlainTextWithItem:(id)arg1 type:(id)arg2;
- (void)paste:(id)arg1;
- (void)copy:(id)arg1;
- (void)cut:(id)arg1;
- (void)doCut;
- (void)doCopy;
- (BOOL)handleInsertImageWithImage:(id)arg1;
- (BOOL)handleDropFilesPromiseType:(id)arg1;
- (id)propertyListFromPasteboard:(id)arg1 item:(id)arg2 withType:(id)arg3;
- (id)dataFromPasteboard:(id)arg1 item:(id)arg2 withType:(id)arg3;
- (BOOL)performDragOperation:(id)arg1;
- (void)handleForwardContact:(id)arg1;
- (void)handleForwardMessages:(id)arg1;
- (BOOL)sendDragOperation:(id)arg1;
- (void)draggingEnded:(id)arg1;
- (void)draggingExited:(id)arg1;
- (unsigned long long)draggingUpdated:(id)arg1;
- (BOOL)prepareForDragOperation:(id)arg1;
- (unsigned long long)draggingEntered:(id)arg1;
- (id)readablePasteboardTypes;
- (id)acceptableDragTypes;
- (void)menuActionSaveAs:(id)arg1;
- (void)menuActionCut:(id)arg1;
- (void)menuActionCopy:(id)arg1;
- (id)menuForClickedIndex:(unsigned long long)arg1;
- (id)textView:(id)arg1 menu:(id)arg2 forEvent:(id)arg3 atIndex:(unsigned long long)arg4;
- (void)textView:(id)arg1 clickedOnCell:(id)arg2 inRect:(struct CGRect)arg3 atIndex:(unsigned long long)arg4;
- (void)didChangeText;
- (BOOL)isInertingSingleCharacterWithAffectedRang:(struct _NSRange)arg1 replacementString:(id)arg2;
- (BOOL)textView:(id)arg1 clickedOnLink:(id)arg2 atIndex:(unsigned long long)arg3;
- (id)_reformatString:(id)arg1;
- (BOOL)textView:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textViewDidChangeSelection:(id)arg1;
- (void)keyDown:(id)arg1;
- (void)_sendMessage;
- (void)clearEditingContent;
- (id)getGroupChatNickNameWithContact:(id)arg1;
- (void)insertMentionWithContact:(id)arg1;
- (void)insertMentionWithContactWithoutRange:(id)arg1;
- (void)insertImageWithRefresh:(id)arg1;
- (void)insertImage:(id)arg1;
- (id)_getMentionedUserDisplayName:(id)arg1;
- (void)insertQuotedMessage:(id)arg1;
- (void)insertEmoticon:(id)arg1;
- (void)insertRichText:(id)arg1;
- (void)setTypingAttributes:(id)arg1;
- (void)handleAppFontSize;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 textStorage:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

