//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface MMComplexContactSearchCacheMgr : NSObject
{
    NSString *_directory;
    NSData *_encryptKey;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSData *encryptKey; // @synthesize encryptKey=_encryptKey;
@property(copy, nonatomic) NSString *directory; // @synthesize directory=_directory;
- (void).cxx_destruct;
- (void)cacheObject:(id)arg1 forType:(id)arg2;
- (id)cachedObjectForType:(id)arg1;
- (void)saveCachesToDisk;
- (BOOL)loadCachesFromDisk;
- (void)clearCachesInMem;

@end

