//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, NSString;

@interface MMCrashReportWrap : NSObject
{
    unsigned int _m_uiCrashVersion;
    NSString *_m_nsCrashUsrName;
    NSData *_m_dtCrashData;
}

@property(retain, nonatomic) NSData *m_dtCrashData; // @synthesize m_dtCrashData=_m_dtCrashData;
@property(nonatomic) unsigned int m_uiCrashVersion; // @synthesize m_uiCrashVersion=_m_uiCrashVersion;
@property(retain, nonatomic) NSString *m_nsCrashUsrName; // @synthesize m_nsCrashUsrName=_m_nsCrashUsrName;
- (void).cxx_destruct;
- (id)init;

@end

