//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "PBCoding.h"

@class NSArray, NSDictionary, NSString;

@interface MMEmoticonStoreItem : NSObject <PBCoding, NSCoding>
{
    unsigned int packType;
    unsigned int packFlag;
    unsigned int boughtTime;
    unsigned int version;
    unsigned int _sortOrder;
    NSString *productID;
    NSString *iconUrl;
    NSString *packName;
    NSString *packDesc;
    NSString *packAuthInfo;
    NSString *packPrice;
    NSString *packThumb;
    NSString *coverUrl;
    NSString *packCopyright;
    NSArray *packThumbList;
    NSString *timeLimit;
    NSString *introduce;
    NSString *tagUrl;
    NSString *shareDesc;
    NSString *oldRedirectUrl;
    NSString *panelUrl;
    NSString *_packFileID;
    NSString *_cdnDownloadClientID;
    NSString *_cdnDownloadPath;
    NSString *_packFileKey;
    NSArray *_packThumbPreviewList;
    unsigned long long _packFileSize;
    NSDictionary *_localizedDescriptionsForStickers;
}

+ (id)storeItemFromEmotionSummary:(id)arg1;
+ (void)initialize;
+ (void)_initPBTableOfMMEmoticonStoreItem;
@property(nonatomic) unsigned int sortOrder; // @synthesize sortOrder=_sortOrder;
@property(retain, nonatomic) NSDictionary *localizedDescriptionsForStickers; // @synthesize localizedDescriptionsForStickers=_localizedDescriptionsForStickers;
@property(nonatomic) unsigned long long packFileSize; // @synthesize packFileSize=_packFileSize;
@property(retain, nonatomic) NSArray *packThumbPreviewList; // @synthesize packThumbPreviewList=_packThumbPreviewList;
@property(copy, nonatomic) NSString *packFileKey; // @synthesize packFileKey=_packFileKey;
@property(copy, nonatomic) NSString *cdnDownloadPath; // @synthesize cdnDownloadPath=_cdnDownloadPath;
@property(copy, nonatomic) NSString *cdnDownloadClientID; // @synthesize cdnDownloadClientID=_cdnDownloadClientID;
@property(copy, nonatomic) NSString *packFileID; // @synthesize packFileID=_packFileID;
@property(copy, nonatomic) NSString *panelUrl; // @synthesize panelUrl;
@property(retain, nonatomic) NSString *oldRedirectUrl; // @synthesize oldRedirectUrl;
@property(retain, nonatomic) NSString *shareDesc; // @synthesize shareDesc;
@property(retain, nonatomic) NSString *tagUrl; // @synthesize tagUrl;
@property(retain, nonatomic) NSString *introduce; // @synthesize introduce;
@property(nonatomic) unsigned int version; // @synthesize version;
@property(retain, nonatomic) NSString *timeLimit; // @synthesize timeLimit;
@property(retain, nonatomic) NSArray *packThumbList; // @synthesize packThumbList;
@property(copy, nonatomic) NSString *packCopyright; // @synthesize packCopyright;
@property(nonatomic) unsigned int boughtTime; // @synthesize boughtTime;
@property(copy, nonatomic) NSString *coverUrl; // @synthesize coverUrl;
@property(copy, nonatomic) NSString *packThumb; // @synthesize packThumb;
@property(nonatomic) unsigned int packFlag; // @synthesize packFlag;
@property(nonatomic) unsigned int packType; // @synthesize packType;
@property(copy, nonatomic) NSString *packPrice; // @synthesize packPrice;
@property(copy, nonatomic) NSString *packAuthInfo; // @synthesize packAuthInfo;
@property(copy, nonatomic) NSString *packDesc; // @synthesize packDesc;
@property(copy, nonatomic) NSString *packName; // @synthesize packName;
@property(copy, nonatomic) NSString *iconUrl; // @synthesize iconUrl;
@property(copy, nonatomic) NSString *productID; // @synthesize productID;
- (void).cxx_destruct;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (const map_24f1cf24 *)getValueTagIndexMap;
- (id)getValueTypeTable;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

