//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewerWindow.h"

#import "AccountServiceExt.h"
#import "MMFavoritesMgrExt.h"
#import "NSSharingServiceDelegate.h"
#import "NSSharingServicePickerDelegate.h"

@class FavoritesItem, FavoritesItemDataField, MessageData, NSString;

@interface MMFavoriteItemViewerWindow : MMViewerWindow <NSSharingServicePickerDelegate, AccountServiceExt, NSSharingServiceDelegate, MMFavoritesMgrExt>
{
    FavoritesItem *_favoritesItem;
    FavoritesItemDataField *_favoritesItemDataField;
    MessageData *_parentMessage;
    FavoritesItemDataField *_parentDataField;
    long long _scene;
    NSString *_filePath;
}

+ (void)preprocessFavItemDataFieldWithFavItem:(id)arg1;
+ (Class)subclassForItem:(int)arg1;
+ (BOOL)hasViewerWindowOpenForItem:(id)arg1;
+ (id)viewerWindowForItemDataField:(id)arg1 parentDataField:(id)arg2 scene:(long long)arg3;
+ (id)viewerWindowForItemDataField:(id)arg1 parentMessage:(id)arg2 scene:(long long)arg3;
+ (id)viewerWindowForItem:(id)arg1 scene:(long long)arg2;
+ (id)viewerWindowForFilePath:(id)arg1 fileType:(int)arg2 scene:(long long)arg3;
+ (void)initialize;
@property(retain, nonatomic) NSString *filePath; // @synthesize filePath=_filePath;
@property(nonatomic) long long scene; // @synthesize scene=_scene;
@property(retain, nonatomic) FavoritesItemDataField *parentDataField; // @synthesize parentDataField=_parentDataField;
@property(retain, nonatomic) MessageData *parentMessage; // @synthesize parentMessage=_parentMessage;
@property(retain, nonatomic) FavoritesItemDataField *favoritesItemDataField; // @synthesize favoritesItemDataField=_favoritesItemDataField;
@property(retain) FavoritesItem *favoritesItem; // @synthesize favoritesItem=_favoritesItem;
- (void).cxx_destruct;
- (void)favoritesMgrDidRemoveItem:(id)arg1;
- (BOOL)useEscKeyForClose;
- (BOOL)useSpaceKeyForClose;
- (void)closeWindowAnimated:(BOOL)arg1;
- (void)onUserLogout;
- (void)onCurrentNetworkLockStateWillChange:(BOOL)arg1;
- (void)onCurrentDeviceLockStateChanged:(BOOL)arg1;
- (void)sharingServiceAction:(id)arg1;
- (id)makeContextMenu;
- (void)sharingService:(id)arg1 didShareItems:(id)arg2;
- (void)sharingService:(id)arg1 didFailToShareItems:(id)arg2 error:(id)arg3;
- (void)sharingService:(id)arg1 willShareItems:(id)arg2;
- (void)share:(id)arg1;
- (void)exportContent:(id)arg1;
- (void)performDelete;
- (void)deleteItem:(id)arg1;
- (void)forwardContentToContactsWithUserNames:(id)arg1;
- (void)forwardContent:(id)arg1;
- (id)shareSubMenuSupportActions;
- (BOOL)showInWindowsMenu;
- (id)title;
- (struct CGSize)sizeForContent;
- (void)windowDidLoad;
- (void)updateCurFavoritesItem:(id)arg1;
- (void)dealloc;
- (id)initWithFavoritesItem:(id)arg1;
- (id)initWithFavoritesItemDataField:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

