//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "AccountServiceExt.h"
#import "FavoritesBatchDelMgrDelegate.h"
#import "FavoritesBatchGetMgrDelegate.h"
#import "FavoritesSyncManagerDelegate.h"
#import "FavoritesUploadMgrDelegate.h"
#import "MMNetExt.h"
#import "MMService.h"

@class FavoritesBatchDelMgr, FavoritesBatchGetMgr, FavoritesSetting, FavoritesSyncManager, FavoritesTagMgr, FavoritesUploadMgr, NSMutableArray, NSMutableSet, NSString, WCFavoritesDB;

@interface MMFavoritesMgr : MMService <FavoritesBatchGetMgrDelegate, FavoritesSyncManagerDelegate, FavoritesBatchDelMgrDelegate, AccountServiceExt, MMNetExt, FavoritesUploadMgrDelegate, MMService>
{
    WCFavoritesDB *_favItemDB;
    FavoritesSyncManager *_syncMgr;
    FavoritesUploadMgr *_uploadMgr;
    FavoritesBatchGetMgr *_batchGetMgr;
    FavoritesTagMgr *_tagMgr;
    FavoritesBatchDelMgr *_batchDelMgr;
    NSMutableArray *_batchGetArr;
    NSMutableSet *_deletingItems;
    NSMutableSet *_modingItems;
    FavoritesSetting *_setting;
}

+ (void)clearDataFolder;
@property(retain, nonatomic) FavoritesSetting *setting; // @synthesize setting=_setting;
@property(retain, nonatomic) NSMutableSet *modingItems; // @synthesize modingItems=_modingItems;
@property(retain, nonatomic) NSMutableSet *deletingItems; // @synthesize deletingItems=_deletingItems;
@property(retain, nonatomic) NSMutableArray *batchGetArr; // @synthesize batchGetArr=_batchGetArr;
@property(retain, nonatomic) FavoritesBatchDelMgr *batchDelMgr; // @synthesize batchDelMgr=_batchDelMgr;
@property(retain, nonatomic) FavoritesTagMgr *tagMgr; // @synthesize tagMgr=_tagMgr;
@property(retain, nonatomic) FavoritesBatchGetMgr *batchGetMgr; // @synthesize batchGetMgr=_batchGetMgr;
@property(retain, nonatomic) FavoritesUploadMgr *uploadMgr; // @synthesize uploadMgr=_uploadMgr;
@property(retain, nonatomic) FavoritesSyncManager *syncMgr; // @synthesize syncMgr=_syncMgr;
@property(readonly, nonatomic) WCFavoritesDB *favItemDB; // @synthesize favItemDB=_favItemDB;
- (void).cxx_destruct;
- (void)checkInvalidNote:(id)arg1 batchgetList:(id)arg2;
- (void)getFirstPageFavoritesList:(int)arg1;
- (id)xmlForFavoriteItem:(id)arg1;
- (void)onUserLogout;
- (void)notifySyncNoteConfilct:(id)arg1;
- (void)updateFavoritesSetting;
- (void)saveFavSetting;
- (void)loadFavSetting;
- (void)onBatchDelItemSuccess;
- (void)onServerNotify:(int)arg1 cmdID:(int)arg2 notifyData:(id)arg3;
- (void)removeSavedFileForFavorteItem:(id)arg1;
- (BOOL)deleteFavoriteItemById:(unsigned int)arg1;
- (BOOL)batchDelFavoritesItem:(id)arg1;
- (BOOL)delFavoritesItems:(id)arg1;
- (BOOL)delFavoritesItem:(id)arg1;
- (void)handleModifyFavItemDescriptionOk:(id)arg1;
- (void)handleModifyFavItemTagOk:(id)arg1;
- (void)batchGetFavItem:(int)arg1;
- (void)HandleModifyFavItemResp:(id)arg1 cgiWrap:(id)arg2;
- (BOOL)updateItemInFavItemDB:(id)arg1;
- (BOOL)updateItemXml:(id)arg1;
- (void)updateSearchTableWithFavoriteItem:(id)arg1;
- (void)reIndexAllItemsIntoSearchTable;
- (void)updateItemUpdateTime:(id)arg1;
- (id)updateTagWithFavoriteItem:(id)arg1;
- (void)searchFavSourceWithKeyword:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)searchWithKeyword:(id)arg1 types:(id)arg2 senderUserName:(id)arg3 tag:(id)arg4 progress:(CDUnknownBlockType)arg5 completion:(CDUnknownBlockType)arg6;
- (void)searchWithKeyword:(id)arg1 types:(id)arg2 senderUserName:(id)arg3 tag:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (BOOL)updateItem:(id)arg1 tags:(id)arg2;
- (void)addItems:(id)arg1 toTag:(id)arg2;
- (void)addItem:(id)arg1 toTag:(id)arg2;
- (id)tagsWithItem:(id)arg1;
- (unsigned long long)countOfItemsWithTagString:(id)arg1;
- (id)itemLocalIDsWithTagString:(id)arg1;
- (id)itemsWithTagsStrings:(id)arg1;
- (id)itemsWithTagString:(id)arg1;
- (unsigned int)allTagsCount;
- (id)topTagsWithLimit:(unsigned int)arg1;
- (id)allTags;
- (id)allFavEssentialInfosInDB;
- (id)allGroupChatSenderContacts;
- (id)allItemSenderContacts;
- (id)allItemSenderUserNames;
- (id)favoritesSetting;
- (id)getFavItemWithFavID:(unsigned int)arg1 checkUpdateIfNeed:(BOOL)arg2;
- (id)getFavItemWithLocalID:(unsigned int)arg1 checkUpdateIfNeed:(BOOL)arg2;
- (unsigned long long)totalCountOfItems;
- (BOOL)getFavItemLocalIDWithFavID:(unsigned int)arg1 retLocalID:(id)arg2;
- (unsigned long long)countOfItemsWithTypes:(id)arg1;
- (unsigned long long)countOfItemsWithType:(int)arg1;
- (id)getAllFavItems;
- (id)getAllFavItemsEssentialFieldsWithTypes:(id)arg1;
- (id)getAllFavItemsEssentialFieldsWithType:(int)arg1;
- (id)getFavItemWithSourceID:(id)arg1;
- (void)checkBatchDelQueue;
- (void)checkUploadingQueueOnReachabilityChanged;
- (void)checkUploadingQueue;
- (void)onUploadFavoritesItemFinished:(id)arg1 ErrCode:(int)arg2;
- (void)onUploadFavoritesItemDidCopiedDataFiles:(id)arg1;
- (BOOL)addLocalNoteFavoriteItem:(id)arg1;
- (BOOL)updateFavoritesItem:(id)arg1 delayUpload:(BOOL)arg2;
- (BOOL)updateFavoriteItem:(id)arg1;
- (BOOL)addFavoritesItem:(id)arg1 delayUpload:(BOOL)arg2;
- (BOOL)addFavoriteItem:(id)arg1;
- (void)onRegardUpdateTimeAsAddAddItem:(id)arg1;
- (void)onBatchGetItemList:(id)arg1 ErrCode:(int)arg2;
- (void)addFavIDsToBatchGetQueue:(id)arg1;
- (void)syncMgrDidFinishSyncWithSuccess:(BOOL)arg1 addedItems:(id)arg2 deletedItemFavIds:(id)arg3 updatedItemFavIds:(id)arg4 totalCountChanged:(BOOL)arg5;
- (void)sync;
- (void)onServiceClearData;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

