//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class MMAvatarImageView, NSButton, NSString, NSTextField, NSWindow, WCContactData;

@interface MMFriendVerifyMessageWindowController : NSWindowController
{
    WCContactData *_contactData;
    NSWindow *_spawningWindow;
    NSTextField *_messageTextField;
    MMAvatarImageView *_avatarView;
    NSTextField *_titleField;
    NSTextField *_hintField;
    NSButton *_cancelButton;
    NSButton *_sendButton;
    NSString *_groupChatUserName;
    CDUnknownBlockType _completionBlock;
}

@property(copy, nonatomic) CDUnknownBlockType completionBlock; // @synthesize completionBlock=_completionBlock;
@property(retain, nonatomic) NSString *groupChatUserName; // @synthesize groupChatUserName=_groupChatUserName;
@property(nonatomic) __weak NSButton *sendButton; // @synthesize sendButton=_sendButton;
@property(nonatomic) __weak NSButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(nonatomic) __weak NSTextField *hintField; // @synthesize hintField=_hintField;
@property(nonatomic) __weak NSTextField *titleField; // @synthesize titleField=_titleField;
@property(nonatomic) __weak MMAvatarImageView *avatarView; // @synthesize avatarView=_avatarView;
@property(nonatomic) __weak NSTextField *messageTextField; // @synthesize messageTextField=_messageTextField;
@property(nonatomic) __weak NSWindow *spawningWindow; // @synthesize spawningWindow=_spawningWindow;
@property(retain, nonatomic) WCContactData *contactData; // @synthesize contactData=_contactData;
- (void).cxx_destruct;
- (void)didClickConfirm:(id)arg1;
- (void)didClickCancel:(id)arg1;
- (void)beginSheetForWindow:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)updateAvatarImage;
- (void)layoutControls;
- (void)setupWithContact:(id)arg1 groupChatUserName:(id)arg2;
- (void)windowDidLoad;
- (id)init;

@end

