//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSImageView.h"

@class NSColor, NSImage;

@interface MMImageView : NSImageView
{
    NSImage *_aspectFillImage;
    BOOL _forceWindowDraggable;
    BOOL _drawWithAspectFill;
    BOOL _draggable;
    int _vibrancyMode;
    int _highlightMode;
    double _mmCornerRadius;
    NSColor *_mmBackgrounColor;
    CDUnknownBlockType _rightMouseUpEventBlock;
    CDUnknownBlockType _magnifyWithEventBlockIsHandled;
    CDUnknownBlockType _smartMagnifyWithEventBlock;
    CDUnknownBlockType _touchesEndWithEventBlock;
    CDUnknownBlockType _mouseDownBlock;
    CDUnknownBlockType _mouseUpBlock;
}

@property(copy, nonatomic) CDUnknownBlockType mouseUpBlock; // @synthesize mouseUpBlock=_mouseUpBlock;
@property(copy, nonatomic) CDUnknownBlockType mouseDownBlock; // @synthesize mouseDownBlock=_mouseDownBlock;
@property(copy, nonatomic) CDUnknownBlockType touchesEndWithEventBlock; // @synthesize touchesEndWithEventBlock=_touchesEndWithEventBlock;
@property(copy, nonatomic) CDUnknownBlockType smartMagnifyWithEventBlock; // @synthesize smartMagnifyWithEventBlock=_smartMagnifyWithEventBlock;
@property(copy, nonatomic) CDUnknownBlockType magnifyWithEventBlockIsHandled; // @synthesize magnifyWithEventBlockIsHandled=_magnifyWithEventBlockIsHandled;
@property(copy, nonatomic) CDUnknownBlockType rightMouseUpEventBlock; // @synthesize rightMouseUpEventBlock=_rightMouseUpEventBlock;
@property(nonatomic) BOOL draggable; // @synthesize draggable=_draggable;
@property(retain, nonatomic) NSColor *mmBackgrounColor; // @synthesize mmBackgrounColor=_mmBackgrounColor;
@property(nonatomic) double mmCornerRadius; // @synthesize mmCornerRadius=_mmCornerRadius;
@property(nonatomic) BOOL drawWithAspectFill; // @synthesize drawWithAspectFill=_drawWithAspectFill;
@property(nonatomic) int highlightMode; // @synthesize highlightMode=_highlightMode;
@property(nonatomic) BOOL forceWindowDraggable; // @synthesize forceWindowDraggable=_forceWindowDraggable;
@property(nonatomic) int vibrancyMode; // @synthesize vibrancyMode=_vibrancyMode;
- (void).cxx_destruct;
- (void)touchesMovedWithEvent:(id)arg1;
- (void)touchesCancelledWithEvent:(id)arg1;
- (void)touchesEndedWithEvent:(id)arg1;
- (void)touchesBeganWithEvent:(id)arg1;
- (BOOL)acceptsTouchEvents;
- (void)smartMagnifyWithEvent:(id)arg1;
- (void)magnifyWithEvent:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (void)rightMouseUp:(id)arg1;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)_generateAspectFillImage:(id)arg1;
- (void)setImage:(id)arg1;
- (void)setHighlighted:(BOOL)arg1;
- (BOOL)allowsVibrancy;
- (BOOL)mouseDownCanMoveWindow;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;

@end

