//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMMessageCellView.h"

#import "MMCDNDownloadMgrExt.h"
#import "MMImageMessageMgrExt.h"
#import "NSPasteboardItemDataProvider.h"

@class NSImage, NSString;

@interface MMImageMessageCellView : MMMessageCellView <MMImageMessageMgrExt, MMCDNDownloadMgrExt, NSPasteboardItemDataProvider>
{
    struct CGRect _imgDrawRect;
    long long _resizeCountInDrawRect;
    BOOL _isStartDownloadManully;
    BOOL _isOriginalImage;
    NSImage *_displayedImage;
    NSString *_cdnKey;
}

+ (BOOL)isCellViewDisplayAsLongRect:(id)arg1;
+ (struct CGSize)_displaySizeForMessage:(id)arg1 constrainedToWidth:(double)arg2;
+ (struct CGSize)displaySizeForImageSize:(struct CGSize)arg1 constrainedToWidth:(double)arg2;
+ (id)defaultImageWithSize:(struct CGSize)arg1;
+ (id)defaultImage;
+ (id)downloadFailedImage;
+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
@property(nonatomic) BOOL isOriginalImage; // @synthesize isOriginalImage=_isOriginalImage;
@property(nonatomic) BOOL isStartDownloadManully; // @synthesize isStartDownloadManully=_isStartDownloadManully;
@property(retain, nonatomic) NSString *cdnKey; // @synthesize cdnKey=_cdnKey;
@property(retain, nonatomic) NSImage *displayedImage; // @synthesize displayedImage=_displayedImage;
- (void).cxx_destruct;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)allowChoose;
- (void)cdnDownloadMgrDidFailedDownloadWithMessage:(id)arg1 type:(int)arg2;
- (void)pasteboard:(id)arg1 item:(id)arg2 provideDataForType:(id)arg3;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (BOOL)makeOpenFolderMenuUnavailable;
- (BOOL)makeOpenWithMenuUnavailable;
- (BOOL)makeOpenMenuUnavailable;
- (BOOL)makeMakeMultipleSelectUnavailable;
- (BOOL)makeSaveAsUnavailable;
- (BOOL)makeAddToFavoritesUnavailable;
- (BOOL)makeForwardUnavailable;
- (BOOL)makeCopyMenuUnavailable;
- (BOOL)isFinishUploadOrDownload;
- (void)contextMenuExport;
- (void)contextMenuOpenWith:(id)arg1;
- (void)contextMenuOpenFoler;
- (id)contextMenuCustomItemsForPosition:(unsigned long long)arg1;
- (id)contextMenuCommonItemsForPosition:(unsigned long long)arg1;
- (id)validRequestorForSendType:(id)arg1 returnType:(id)arg2;
- (BOOL)allowContextMenuForEvent:(id)arg1;
- (BOOL)allowCopy;
- (BOOL)allowAddToFavorites;
- (void)writeIntoPasteboard:(id)arg1 orItem:(id)arg2 provideDataForType:(id)arg3;
- (id)draggablePasteboardTypes;
- (id)acceptablePasteTypes;
- (id)draggingImage;
- (struct CGRect)clickableArea;
- (BOOL)draggingEnabled;
- (void)failedImageDidLoadWithUniqueID:(id)arg1 image:(id)arg2;
- (void)originalImageDidLoadWithUniqueID:(id)arg1 image:(id)arg2;
- (void)thumbImageDidLoadWithUniqueID:(id)arg1 image:(id)arg2;
- (void)drawRectWithBubbleMask:(struct CGRect)arg1;
- (void)drawRectWithoutBubbleMask:(struct CGRect)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (id)previewItemURL;
- (void)resendMessage;
- (void)_tellDelegateToUpdatePreview;
- (void)_tellDelegateToResize;
- (struct CGRect)_failedImageDisplayRect;
- (void)_updateGeometry;
- (void)_newBounds;
- (void)redrawLocalView;
- (void)populateWithMessage:(id)arg1;
- (void)checkCellView:(id)arg1;
- (void)prepareForReuse;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

