//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMKeyValueRowView.h"

@interface MMKeyValueFullWidthTextRow : MMKeyValueRowView
{
}

- (void)sizeToFit;
- (id)initWithFrame:(struct CGRect)arg1 text:(id)arg2;

@end

