//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMKeyValueRowView.h"

#import "NSTokenFieldDelegate.h"

@class NSArray, NSDictionary, NSString, NSTokenField;

@interface MMKeyValueTokenRowView : MMKeyValueRowView <NSTokenFieldDelegate>
{
    NSDictionary *_normalizedCompletions;
    NSTokenField *_tokenField;
    NSString *_initialValue;
    CDUnknownBlockType _tokensDidChangedBlock;
}

@property(copy, nonatomic) CDUnknownBlockType tokensDidChangedBlock; // @synthesize tokensDidChangedBlock=_tokensDidChangedBlock;
@property(retain, nonatomic) NSString *initialValue; // @synthesize initialValue=_initialValue;
@property(retain, nonatomic) NSTokenField *tokenField; // @synthesize tokenField=_tokenField;
- (void).cxx_destruct;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)textDidEndEditing:(id)arg1;
- (void)textDidBeginEditing:(id)arg1;
- (void)setTokens:(id)arg1;
- (id)tokenField:(id)arg1 completionsForSubstring:(id)arg2 indexOfToken:(long long)arg3 indexOfSelectedItem:(long long *)arg4;
@property(retain, nonatomic) NSArray *completionsForTokens;
- (void)drawRect:(struct CGRect)arg1;
- (void)sizeToFit;
- (void)setEditable:(BOOL)arg1;
- (id)initWithFrame:(struct CGRect)arg1 key:(id)arg2 tokens:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

