//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MMLeaksMonitor : NSObject
{
    BOOL m_bIsMonitorRunning;
    BOOL m_bMonitorShouldRun;
    BOOL m_bShouldThrowsOomException;
    BOOL m_bShouldBreakWindowDraggingInfinityLoop;
    double m_dMonitorWaitInterval;
    unsigned int m_uiMinRealMemoryConsumeToReportInMB;
    unsigned int m_uiMinTotalMemoryConsumeToReportInMB;
    unsigned int m_uiMinTotalMemoryConsumeToThrowsExceptionInMB;
    unsigned int m_uiMemoryConsumeReportInterval;
    unsigned long long m_totalPhysicalMemory;
    unsigned int m_uiLastMemoryConsumeReportTime;
    int m_uiLastPageFaults;
    BOOL m_bShouldOpenReportStack;
    unsigned int m_uiMinTotalMemoryConsumeToReportStackInMB;
    unsigned int m_uiReportStackLimit;
    unsigned int m_uiLastReportStackTime;
    BOOL _isInNSAppSendEvent;
    unsigned long long _runLoopTotalCount;
}

+ (id)sharedInstance;
@property(nonatomic) unsigned long long runLoopTotalCount; // @synthesize runLoopTotalCount=_runLoopTotalCount;
@property(nonatomic) BOOL isInNSAppSendEvent; // @synthesize isInNSAppSendEvent=_isInNSAppSendEvent;
- (id)getRAMUsage;
- (unsigned long long)getRAMTotal;
- (void)LoadABTestParameters;
- (void)postMemoryWarnningIfNeed:(unsigned int)arg1 compressedMemory:(unsigned int)arg2 virtualMemory:(unsigned int)arg3 physicalMemory:(unsigned int)arg4;
- (void)checkHugeMemoryLeakCycle;
- (void)onMonitorThreadStartCallback;
- (void)startMonitor;
- (id)init;

@end

