//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCContactData;

@interface MMMessageSendLogic : NSObject
{
    WCContactData *_currnetChatContact;
    id <MMMutiplySelectAnimationDelegate> _mutiplySelectAnimationDelegate;
}

@property(nonatomic) __weak id <MMMutiplySelectAnimationDelegate> mutiplySelectAnimationDelegate; // @synthesize mutiplySelectAnimationDelegate=_mutiplySelectAnimationDelegate;
@property(retain, nonatomic) WCContactData *currnetChatContact; // @synthesize currnetChatContact=_currnetChatContact;
- (void).cxx_destruct;
- (id)filterAllowFavItem:(id)arg1;
- (id)filterAllowMergeForward:(id)arg1;
- (id)filterAllowForward:(id)arg1;
- (id)filterUndowloadMessage:(id)arg1;
- (void)AddFavoritesWithMultipleMsgList:(id)arg1;
- (void)ForwardWithMultipleMsgList:(id)arg1 toContacts:(id)arg2;
- (void)SendOneByOneWithMultipleSelectMsgList:(id)arg1 toCtontacts:(id)arg2;
- (void)ForwardMessage:(id)arg1 toContacts:(id)arg2;
- (void)SendWithMultipleSelectMsgList:(id)arg1 toContacts:(id)arg2;
- (unsigned int)videoDuration:(id)arg1;
- (void)sendVideoMessageWithFileUrl:(id)arg1;
- (void)sendImageMessageWithImageData:(id)arg1 imageInfo:(id)arg2;
- (void)sendImageMessageWithImage:(id)arg1;
- (void)sendImageMessageWithFileUrl:(id)arg1;
- (unsigned char)sendTextMessageWithString:(id)arg1 mentionedUsers:(id)arg2;
- (void)sendFileWithFilePath:(id)arg1 fileName:(id)arg2 fileSize:(long long)arg3;
- (void)sendAllKindsFileWithURL:(id)arg1 fileName:(id)arg2;
- (void)sendMultiFilesWithURLs:(id)arg1 names:(id)arg2;

@end

