//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MessageData, NSString, ReaderWrap, WCContactData;

@interface MMOAMessageItem : NSObject
{
    unsigned long long _type;
    WCContactData *_authorContact;
    NSString *_title;
    NSString *_urlString;
    NSString *_thumbnailImgUrlString;
    MessageData *_message;
    ReaderWrap *_readerWrap;
}

+ (id)authorItemWithMessageData:(id)arg1;
+ (id)itemWithMessageData:(id)arg1 readerWrap:(id)arg2;
@property(retain, nonatomic) ReaderWrap *readerWrap; // @synthesize readerWrap=_readerWrap;
@property(retain, nonatomic) MessageData *message; // @synthesize message=_message;
@property(retain, nonatomic) NSString *thumbnailImgUrlString; // @synthesize thumbnailImgUrlString=_thumbnailImgUrlString;
@property(retain, nonatomic) NSString *urlString; // @synthesize urlString=_urlString;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) WCContactData *authorContact; // @synthesize authorContact=_authorContact;
@property(nonatomic) unsigned long long type; // @synthesize type=_type;
- (void).cxx_destruct;

@end

