//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

@class MMCenteringClipView, MMNoBlurImageView, MMPreviewViewPageInfo, NSScrollView;

@interface MMPreviewPanelViewController : NSViewController
{
    NSScrollView *_scrollView;
    MMNoBlurImageView *_imageView;
    MMPreviewViewPageInfo *_pageInfo;
    MMCenteringClipView *_clipView;
}

@property(retain, nonatomic) MMCenteringClipView *clipView; // @synthesize clipView=_clipView;
@property(retain, nonatomic) MMPreviewViewPageInfo *pageInfo; // @synthesize pageInfo=_pageInfo;
@property(retain, nonatomic) MMNoBlurImageView *imageView; // @synthesize imageView=_imageView;
@property(retain, nonatomic) NSScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)delayRotateMessageHDImage:(id)arg1;
- (void)mainThreadRotateImage;
- (void)rotateNormalImage;
- (void)rotateMessageImage;
- (void)rotateImage;
- (void)standardSize;
- (void)zoomOut;
- (void)zoomIn;
- (BOOL)isHDImageSize:(struct CGSize)arg1;
- (void)setupWithChatRecordPageInfo:(id)arg1;
- (void)refreshFavHDImageOnDidEndLiveTransition;
- (void)setupWithFavPageInfo:(id)arg1;
- (void)refreshMsgHDImageOnDidEndLiveTransition;
- (void)setupWithMsgPageInfo:(id)arg1;
- (void)setupImageScaleMod;
- (void)resetPreviewStatus;
- (void)setupWithPageInfo:(id)arg1;
- (void)refreshHDImageOnDidEndLiveTransition;
- (void)viewDidDisappear;
- (void)viewDidLoad;

@end

