//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "MASPreferencesViewController.h"

@class NSButton, NSImage, NSString, NSTextField;

@interface MMPreferencesNotificationController : NSViewController <MASPreferencesViewController>
{
    NSTextField *_msgNotificationLabel;
    NSTextField *_openScreenBannerNotificationLabel;
    NSButton *_goToPreferencesButton;
    NSTextField *_openScreenBannerNotificationRemarkLabel;
    NSButton *_showPreviewButton;
    NSButton *_alertSoundButton;
}

@property(nonatomic) __weak NSButton *alertSoundButton; // @synthesize alertSoundButton=_alertSoundButton;
@property(nonatomic) __weak NSButton *showPreviewButton; // @synthesize showPreviewButton=_showPreviewButton;
@property(nonatomic) __weak NSTextField *openScreenBannerNotificationRemarkLabel; // @synthesize openScreenBannerNotificationRemarkLabel=_openScreenBannerNotificationRemarkLabel;
@property(nonatomic) __weak NSButton *goToPreferencesButton; // @synthesize goToPreferencesButton=_goToPreferencesButton;
@property(nonatomic) __weak NSTextField *openScreenBannerNotificationLabel; // @synthesize openScreenBannerNotificationLabel=_openScreenBannerNotificationLabel;
@property(nonatomic) __weak NSTextField *msgNotificationLabel; // @synthesize msgNotificationLabel=_msgNotificationLabel;
- (void).cxx_destruct;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(readonly, nonatomic) NSImage *toolbarItemImage;
@property(readonly, nonatomic) NSString *toolbarItemLabel;
@property(readonly, nonatomic) NSString *identifier;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) BOOL hasResizableHeight;
@property(readonly, nonatomic) BOOL hasResizableWidth;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

