//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScrollView.h"

@class NSProgressIndicator, NSView;

@interface MMRefreshableScrollView : NSScrollView
{
    NSProgressIndicator *m_topProgressIndicator;
    NSProgressIndicator *m_bottomProgressIndicator;
    NSView *m_headerView;
    NSView *m_footerView;
    unsigned long long m_refreshingSides;
    BOOL _scrollBackOnFinishLoading;
    unsigned long long _refreshableSides;
    unsigned long long _triggeredRefreshingSides;
    unsigned long long _activatedRefreshingSides;
    id <MMRefreshableScrollViewDelegate> _refreshableDelegate;
}

@property(nonatomic) __weak id <MMRefreshableScrollViewDelegate> refreshableDelegate; // @synthesize refreshableDelegate=_refreshableDelegate;
@property(nonatomic) unsigned long long activatedRefreshingSides; // @synthesize activatedRefreshingSides=_activatedRefreshingSides;
@property(nonatomic) unsigned long long triggeredRefreshingSides; // @synthesize triggeredRefreshingSides=_triggeredRefreshingSides;
@property(nonatomic) unsigned long long refreshableSides; // @synthesize refreshableSides=_refreshableSides;
@property(nonatomic) BOOL scrollBackOnFinishLoading; // @synthesize scrollBackOnFinishLoading=_scrollBackOnFinishLoading;
- (void).cxx_destruct;
- (void)scrollWheel:(id)arg1;
- (id)_newEdgeViewForSide:(unsigned long long)arg1 progressIndicator:(id)arg2;
- (id)bottomProgressIndicator;
- (id)topProgressIndicator;
- (id)contentView;
- (void)stopRefreshingSides:(unsigned long long)arg1;
@property(readonly, nonatomic) unsigned long long refreshingSides;
@property(readonly, nonatomic) NSView *footerView;
@property(readonly, nonatomic) NSView *headerView;

@end

