//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSearchField.h"

@interface MMSearchField : NSSearchField
{
    CDUnknownBlockType _didBecomeFirstResponderBlock;
    CDUnknownBlockType _canBecomFirstResponderBlock;
}

@property(copy, nonatomic) CDUnknownBlockType canBecomFirstResponderBlock; // @synthesize canBecomFirstResponderBlock=_canBecomFirstResponderBlock;
@property(copy, nonatomic) CDUnknownBlockType didBecomeFirstResponderBlock; // @synthesize didBecomeFirstResponderBlock=_didBecomeFirstResponderBlock;
- (void).cxx_destruct;
- (BOOL)becomeFirstResponder;
- (void)mouseDown:(id)arg1;

@end

