//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSearchResultItem.h"

@class NSString;

@interface MMSearchResultHeaderItem : MMSearchResultItem
{
    NSString *_title;
    unsigned long long _itemCount;
    unsigned long long _resultType;
}

+ (id)allItemWithCount:(unsigned long long)arg1 resultType:(unsigned long long)arg2;
+ (id)headerItemWithTitle:(id)arg1 itemCount:(unsigned long long)arg2 resultType:(unsigned long long)arg3;
@property(nonatomic) unsigned long long resultType; // @synthesize resultType=_resultType;
@property(nonatomic) unsigned long long itemCount; // @synthesize itemCount=_itemCount;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (id)identifier;

@end

