//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray;

@interface MMSpaceCleanerSelectSessionLogic : NSObject
{
    NSMutableArray *_displayedItems;
    NSMutableArray *_selectedItems;
    NSMutableArray *_deletedUserNames;
    unsigned long long _totalSpaceSize;
}

@property(nonatomic) unsigned long long totalSpaceSize; // @synthesize totalSpaceSize=_totalSpaceSize;
@property(retain, nonatomic) NSMutableArray *deletedUserNames; // @synthesize deletedUserNames=_deletedUserNames;
@property(retain, nonatomic) NSMutableArray *selectedItems; // @synthesize selectedItems=_selectedItems;
@property(retain, nonatomic) NSMutableArray *displayedItems; // @synthesize displayedItems=_displayedItems;
- (void).cxx_destruct;
- (void)unselectAllSessions;
- (void)selectAllSessions;
- (void)deleteSelectedSession:(id)arg1;
- (void)addSelectedSession:(id)arg1;
- (BOOL)isSessionSelected:(id)arg1;
- (void)clearSessionSpace:(id)arg1 rowItem:(id)arg2;
- (void)clearSpace;
- (void)setupSessionInfoList:(id)arg1;
- (void)resetLogicState;
- (id)init;

@end

