//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMView.h"

@class MMOutlineButton, MMOutlineCheckBoxButton, NSTextField, NSVisualEffectView;

@interface MMStickerPickerTipsView : MMView
{
    NSVisualEffectView *_visualEffectView;
    MMView *_barrierView;
    NSTextField *_titleLabel;
    NSTextField *_descriptionLabel;
    MMOutlineButton *_ignoreBtn;
    MMOutlineButton *_goToPrefsBtn;
    MMOutlineCheckBoxButton *_doNotRemindAgainCheckBox;
    CDUnknownBlockType _didDismissTipsViewBlock;
}

@property(copy, nonatomic) CDUnknownBlockType didDismissTipsViewBlock; // @synthesize didDismissTipsViewBlock=_didDismissTipsViewBlock;
@property(retain, nonatomic) MMOutlineCheckBoxButton *doNotRemindAgainCheckBox; // @synthesize doNotRemindAgainCheckBox=_doNotRemindAgainCheckBox;
@property(retain, nonatomic) MMOutlineButton *goToPrefsBtn; // @synthesize goToPrefsBtn=_goToPrefsBtn;
@property(retain, nonatomic) MMOutlineButton *ignoreBtn; // @synthesize ignoreBtn=_ignoreBtn;
@property(retain, nonatomic) NSTextField *descriptionLabel; // @synthesize descriptionLabel=_descriptionLabel;
@property(retain, nonatomic) NSTextField *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) MMView *barrierView; // @synthesize barrierView=_barrierView;
@property(retain, nonatomic) NSVisualEffectView *visualEffectView; // @synthesize visualEffectView=_visualEffectView;
- (void).cxx_destruct;
- (void)onIgnoreButtonClicked:(id)arg1;
- (void)onGoToPrefsButtonClicked:(id)arg1;
- (void)onDoNotRemindAgainCheckBoxClicked:(id)arg1;
- (void)setupSubViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

