//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "RBLPopoverBackgroundView.h"

@interface MMSuggestionPopoverBackgrounView : RBLPopoverBackgroundView
{
    id <MMSuggestionPopoverBackgrounViewDelegate> _delegate;
}

@property(nonatomic) __weak id <MMSuggestionPopoverBackgrounViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)sizeForBackgroundViewWithContentSize:(struct CGSize)arg1 popoverEdge:(unsigned int)arg2;

@end

