//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class NSAttributedString, NSButton, NSString, NSTextField;

@interface MMSwizzleTrafficLightWindowController : NSWindowController
{
    NSButton *_minButton;
    NSButton *_closeButton;
    NSButton *_zoomButton;
    NSTextField *_titleField;
    NSString *_windowTitle;
    NSAttributedString *_windowAttributedTitle;
}

@property(retain, nonatomic) NSAttributedString *windowAttributedTitle; // @synthesize windowAttributedTitle=_windowAttributedTitle;
@property(retain, nonatomic) NSString *windowTitle; // @synthesize windowTitle=_windowTitle;
@property(retain, nonatomic) NSTextField *titleField; // @synthesize titleField=_titleField;
@property(retain, nonatomic) NSButton *zoomButton; // @synthesize zoomButton=_zoomButton;
@property(retain, nonatomic) NSButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) NSButton *minButton; // @synthesize minButton=_minButton;
- (void).cxx_destruct;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)setTrafficLightsNeedDisplayWithHover:(BOOL)arg1;
- (void)layoutWindowTitle;
- (void)layoutTrafficLightButtons;
- (void)swizzleCoreUIPresentationStateMethod;
- (void)swizzleCoreUIStateMethod;
- (void)close;
- (void)dealloc;
- (void)windowDidLoad;

@end

