//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMDraggableWindowController.h"

@class MMOutlineButton, NSTextField, NSView;

@interface MMTechSupportWindowController : MMDraggableWindowController
{
    NSView *_bgContainer;
    NSTextField *_jietuTitle;
    NSTextField *_jietuDesc;
    MMOutlineButton *_jietuOfficalWebsite;
}

@property __weak MMOutlineButton *jietuOfficalWebsite; // @synthesize jietuOfficalWebsite=_jietuOfficalWebsite;
@property __weak NSTextField *jietuDesc; // @synthesize jietuDesc=_jietuDesc;
@property __weak NSTextField *jietuTitle; // @synthesize jietuTitle=_jietuTitle;
@property __weak NSView *bgContainer; // @synthesize bgContainer=_bgContainer;
- (void).cxx_destruct;
- (void)setupJietu;
- (void)windowDidLoad;

@end

