//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMTextMessageCellView.h"

@class NSImageView;

@interface MMVoipMessageCellView : MMTextMessageCellView
{
    unsigned int _voipInviteType;
    id <VoipMessageCellViewDelegate> _voipMessageCellViewDelegate;
    NSImageView *_voipIconImageView;
}

+ (void)cellViewRectsForTableItem:(id)arg1 constrainedToWidth:(double)arg2 leftPadding:(double)arg3 bounds:(struct CGRect *)arg4 bubble:(struct CGRect *)arg5 text:(struct CGRect *)arg6 translation:(struct CGRect *)arg7 brand:(struct CGRect *)arg8;
@property(retain, nonatomic) NSImageView *voipIconImageView; // @synthesize voipIconImageView=_voipIconImageView;
@property(nonatomic) unsigned int voipInviteType; // @synthesize voipInviteType=_voipInviteType;
@property(nonatomic) __weak id <VoipMessageCellViewDelegate> voipMessageCellViewDelegate; // @synthesize voipMessageCellViewDelegate=_voipMessageCellViewDelegate;
- (void).cxx_destruct;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (BOOL)draggingEnabled;
- (void)setChoosable:(BOOL)arg1;
- (BOOL)makeMakeMultipleSelectUnavailable;
- (BOOL)allowChoose;
- (BOOL)alwaysDisableMessageTextViewSelectableProperty;
- (void)drawRect:(struct CGRect)arg1;
- (void)populateWithMessage:(id)arg1;
- (void)prepareForReuse;
- (id)initWithFrame:(struct CGRect)arg1;

@end

