//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WeNoteParagraphInfo;

@protocol MMVoiceAttachmentViewDelegate <NSObject>
- (void)startPlayVoiceAnyway:(WeNoteParagraphInfo *)arg1 lastPlayTime:(double)arg2;
- (void)startPlayVoice:(WeNoteParagraphInfo *)arg1 lastPlayTime:(double)arg2;
@end

