//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface MMWebSearchResultDataItem : NSObject
{
    BOOL _isInitial;
    unsigned int _date;
    NSString *_desc;
    NSString *_docID;
    NSString *_docUrl;
    unsigned long long _newsType;
    NSString *_source;
    NSString *_thumbUrl;
    NSString *_title;
    NSString *_shareString;
}

@property(nonatomic) BOOL isInitial; // @synthesize isInitial=_isInitial;
@property(retain, nonatomic) NSString *shareString; // @synthesize shareString=_shareString;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *thumbUrl; // @synthesize thumbUrl=_thumbUrl;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(nonatomic) unsigned long long newsType; // @synthesize newsType=_newsType;
@property(retain, nonatomic) NSString *docUrl; // @synthesize docUrl=_docUrl;
@property(retain, nonatomic) NSString *docID; // @synthesize docID=_docID;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(nonatomic) unsigned int date; // @synthesize date=_date;
- (void).cxx_destruct;

@end

