//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMSwizzleTrafficLightWindowController.h"

#import "NSWindowDelegate.h"
#import "WeChatSearchProtocol.h"

@class MMWebSearchViewController, NSString;

@interface MMWebSearchWindowController : MMSwizzleTrafficLightWindowController <NSWindowDelegate, WeChatSearchProtocol>
{
    MMWebSearchViewController *_webSearchVC;
}

@property(retain, nonatomic) MMWebSearchViewController *webSearchVC; // @synthesize webSearchVC=_webSearchVC;
- (void).cxx_destruct;
- (void)performSearchAction;
- (BOOL)windowShouldClose:(id)arg1;
- (void)orderFrontWindow;
- (void)closeWindowAnimated:(BOOL)arg1;
- (void)showWindowAnimated:(BOOL)arg1 keyWord:(id)arg2;
- (void)windowDidLoad;
- (id)initWithWindowNibName:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

