//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "AccountServiceExt.h"
#import "MMCGIDelegate.h"
#import "MMService.h"

@class NSMutableArray, NSString;

@interface MMWebSearchDataMgr : MMService <MMCGIDelegate, AccountServiceExt, MMService>
{
    BOOL _isWebSearching;
    NSString *_keyWord;
    unsigned long long _sortType;
    NSMutableArray *_searchResults;
    NSMutableArray *_suggestionResults;
    CDUnknownBlockType _searchCompletionBlock;
    CDUnknownBlockType _suggestionCompletionBlock;
    NSString *_searchId;
    unsigned long long _offset;
    unsigned long long _isInitialSearch;
    unsigned long long _searchBeginTime;
    unsigned long long _suggestionBeginTime;
}

+ (void)LazyRegisterExtension;
@property(nonatomic) unsigned long long suggestionBeginTime; // @synthesize suggestionBeginTime=_suggestionBeginTime;
@property(nonatomic) unsigned long long searchBeginTime; // @synthesize searchBeginTime=_searchBeginTime;
@property(nonatomic) unsigned long long isInitialSearch; // @synthesize isInitialSearch=_isInitialSearch;
@property(nonatomic) unsigned long long offset; // @synthesize offset=_offset;
@property(retain, nonatomic) NSString *searchId; // @synthesize searchId=_searchId;
@property(copy, nonatomic) CDUnknownBlockType suggestionCompletionBlock; // @synthesize suggestionCompletionBlock=_suggestionCompletionBlock;
@property(copy, nonatomic) CDUnknownBlockType searchCompletionBlock; // @synthesize searchCompletionBlock=_searchCompletionBlock;
@property(retain, nonatomic) NSMutableArray *suggestionResults; // @synthesize suggestionResults=_suggestionResults;
@property(retain, nonatomic) NSMutableArray *searchResults; // @synthesize searchResults=_searchResults;
@property(nonatomic) BOOL isWebSearching; // @synthesize isWebSearching=_isWebSearching;
@property(nonatomic) unsigned long long sortType; // @synthesize sortType=_sortType;
@property(retain, nonatomic) NSString *keyWord; // @synthesize keyWord=_keyWord;
- (void).cxx_destruct;
- (long long)compareCreateTime:(id)arg1 with:(id)arg2;
- (void)sortResultsWithCompletion:(CDUnknownBlockType)arg1;
- (void)parseSuggestionJsonString:(id)arg1;
- (void)parseSearchJsonString:(id)arg1;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (BOOL)doWebSearchSuggestionWithCompletion:(CDUnknownBlockType)arg1;
- (BOOL)doWebSearchWithCompletion:(CDUnknownBlockType)arg1 initSearch:(BOOL)arg2;
- (void)onUserLogout;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)destroy;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

