//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMAnimatedImageDecoder.h"

@class NSData, NSImage;

@interface MxGifAnimatedImageDecoder : MMAnimatedImageDecoder
{
    struct MxGifImage *m_gifImage;
    NSData *m_gifData;
    BOOL m_ignoreFirstSeek;
    BOOL m_hasDecodeOneLoop;
    BOOL m_isSingleFrame;
    int m_frameCount;
    NSImage *m_currentFrameImage;
    double m_currentFrameDuration;
    struct CGSize m_imageSize;
}

+ (void)updateMaxWidth:(unsigned int)arg1;
+ (int)frameCountForImageData:(id)arg1;
+ (double)frameDurationInSecondForDuration:(double)arg1;
- (BOOL)isSingleFrame;
- (BOOL)hasDecodeOneLoop;
- (struct CGSize)imageSize;
- (double)currentFrameDuration;
- (void).cxx_destruct;
- (BOOL)configDecoderWithGifData:(id)arg1;
- (void)setScale:(double)arg1;
- (int)frameCount;
- (int)currentFrameId;
- (id)currentFrameImage;
- (void)seekToNextFrame;
- (id)initWithData:(id)arg1;
- (void)dealloc;

@end

