//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSAttributedString.h"

@interface NSAttributedString (MMRichTextView)
- (unsigned long long)bulletAttachmentCount;
- (struct _NSRange)nextParagraphRangeFromTextRange:(struct _NSRange)arg1;
- (struct _NSRange)previousParagraphRangeFromTextRange:(struct _NSRange)arg1;
- (id)rangeOfParagraphsFromTextRange:(struct _NSRange)arg1;
- (struct _NSRange)firstParagraphRangeFromTextRange:(struct _NSRange)arg1;
@end

