//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (LagMonitor)
+ (void)load;
+ (id)__lagmonitor_dataWithContentsOfURL:(id)arg1;
+ (id)__lagmonitor_dataWithContentsOfFile:(id)arg1;
+ (id)__lagmonitor_dataWithContentsOfURL:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
+ (id)__lagmonitor_dataWithContentsOfFile:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
- (id)__lagmonitor_initWithContentsOfURL:(id)arg1;
- (id)__lagmonitor_initWithContentsOfFile:(id)arg1;
- (id)__lagmonitor_initWithContentsOfURL:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
- (id)__lagmonitor_initWithContentsOfFile:(id)arg1 options:(unsigned long long)arg2 error:(id *)arg3;
@end

