//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindow.h"

@interface NSWindow (MMHopAnimation)
- (void)doHopAnimationWithImage:(id)arg1 originRect:(struct CGRect)arg2 destinationRect:(struct CGRect)arg3 duration:(double)arg4 completion:(CDUnknownBlockType)arg5;
- (void)doHopAnimationWithImage:(id)arg1 originView:(id)arg2 destinationView:(id)arg3 duration:(double)arg4 completion:(CDUnknownBlockType)arg5;
- (void)doHopAnimationWithImage:(id)arg1 originRect:(struct CGRect)arg2 topTabIndex:(int)arg3 duration:(double)arg4 completion:(CDUnknownBlockType)arg5;
@end

