//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class SKBuiltinString_t;

@interface OpenQQMicroBlog : PBGeneratedMessage
{
    unsigned int hasMicroBlogUserName:1;
    SKBuiltinString_t *microBlogUserName;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetMicroBlogUserName:) SKBuiltinString_t *microBlogUserName; // @synthesize microBlogUserName;
@property(readonly, nonatomic) BOOL hasMicroBlogUserName; // @synthesize hasMicroBlogUserName;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

