//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface PacketBackupDataTagResponse : PBGeneratedMessage
{
    unsigned int hasBakChatName:1;
    unsigned int hasStartTime:1;
    unsigned int hasEndTime:1;
    unsigned int hasMsgDataId:1;
    NSString *bakChatName;
    long long startTime;
    long long endTime;
    NSString *msgDataId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetMsgDataId:) NSString *msgDataId; // @synthesize msgDataId;
@property(readonly, nonatomic) BOOL hasMsgDataId; // @synthesize hasMsgDataId;
@property(nonatomic, setter=SetEndTime:) long long endTime; // @synthesize endTime;
@property(readonly, nonatomic) BOOL hasEndTime; // @synthesize hasEndTime;
@property(nonatomic, setter=SetStartTime:) long long startTime; // @synthesize startTime;
@property(readonly, nonatomic) BOOL hasStartTime; // @synthesize hasStartTime;
@property(retain, nonatomic, setter=SetBakChatName:) NSString *bakChatName; // @synthesize bakChatName;
@property(readonly, nonatomic) BOOL hasBakChatName; // @synthesize hasBakChatName;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

