//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData, NSString;

@interface PacketAuthenticateRequest : PBGeneratedMessage
{
    unsigned int hasStep:1;
    unsigned int hasId:1;
    NSString *id_;
    unsigned int hasData:1;
    NSData *data_;
    unsigned int hasVersion:1;
    unsigned int hasType:1;
    unsigned int hasSupportExt:1;
    unsigned int hasNeedToken:1;
    int step;
    int version;
    int type;
    int supportExt;
    int needToken;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetNeedToken:) int needToken; // @synthesize needToken;
@property(readonly, nonatomic) BOOL hasNeedToken; // @synthesize hasNeedToken;
@property(nonatomic, setter=SetSupportExt:) int supportExt; // @synthesize supportExt;
@property(readonly, nonatomic) BOOL hasSupportExt; // @synthesize hasSupportExt;
@property(nonatomic, setter=SetType:) int type; // @synthesize type;
@property(readonly, nonatomic) BOOL hasType; // @synthesize hasType;
@property(nonatomic, setter=SetVersion:) int version; // @synthesize version;
@property(readonly, nonatomic) BOOL hasVersion; // @synthesize hasVersion;
@property(retain, nonatomic, setter=SetData:) NSData *data; // @synthesize data=data_;
@property(readonly, nonatomic) BOOL hasData; // @synthesize hasData;
@property(retain, nonatomic, setter=SetId:) NSString *id; // @synthesize id=id_;
@property(readonly, nonatomic) BOOL hasId; // @synthesize hasId;
@property(nonatomic, setter=SetStep:) int step; // @synthesize step;
@property(readonly, nonatomic) BOOL hasStep; // @synthesize hasStep;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

