//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSString;

@interface PreparePurchaseResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasBillNo:1;
    unsigned int hasTradeToken4TenPay:1;
    unsigned int hasPartner4TenPay:1;
    unsigned int hasSign4TenPay:1;
    BaseResponse *baseResponse;
    NSString *billNo;
    NSString *tradeToken4TenPay;
    NSString *partner4TenPay;
    NSString *sign4TenPay;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetSign4TenPay:) NSString *sign4TenPay; // @synthesize sign4TenPay;
@property(readonly, nonatomic) BOOL hasSign4TenPay; // @synthesize hasSign4TenPay;
@property(retain, nonatomic, setter=SetPartner4TenPay:) NSString *partner4TenPay; // @synthesize partner4TenPay;
@property(readonly, nonatomic) BOOL hasPartner4TenPay; // @synthesize hasPartner4TenPay;
@property(retain, nonatomic, setter=SetTradeToken4TenPay:) NSString *tradeToken4TenPay; // @synthesize tradeToken4TenPay;
@property(readonly, nonatomic) BOOL hasTradeToken4TenPay; // @synthesize hasTradeToken4TenPay;
@property(retain, nonatomic, setter=SetBillNo:) NSString *billNo; // @synthesize billNo;
@property(readonly, nonatomic) BOOL hasBillNo; // @synthesize hasBillNo;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

