//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface QContact : PBGeneratedMessage
{
    unsigned int hasUserName:1;
    unsigned int hasDisplayName:1;
    unsigned int hasExtInfoSeq:1;
    unsigned int hasImgUpdateSeq:1;
    unsigned int extInfoSeq;
    unsigned int imgUpdateSeq;
    NSString *userName;
    NSString *displayName;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetImgUpdateSeq:) unsigned int imgUpdateSeq; // @synthesize imgUpdateSeq;
@property(readonly, nonatomic) BOOL hasImgUpdateSeq; // @synthesize hasImgUpdateSeq;
@property(nonatomic, setter=SetExtInfoSeq:) unsigned int extInfoSeq; // @synthesize extInfoSeq;
@property(readonly, nonatomic) BOOL hasExtInfoSeq; // @synthesize hasExtInfoSeq;
@property(retain, nonatomic, setter=SetDisplayName:) NSString *displayName; // @synthesize displayName;
@property(readonly, nonatomic) BOOL hasDisplayName; // @synthesize hasDisplayName;
@property(retain, nonatomic, setter=SetUserName:) NSString *userName; // @synthesize userName;
@property(readonly, nonatomic) BOOL hasUserName; // @synthesize hasUserName;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

