//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSView.h"

@class NSColor, NSImage;

@interface RBLView : NSView
{
    struct {
        unsigned int clearsContextBeforeDrawing:1;
        unsigned int flipped:1;
        unsigned int clipsToBounds:1;
        unsigned int opaque:1;
    } _flags;
    NSColor *_backgroundColor;
    double _cornerRadius;
    NSImage *_contents;
}

+ (BOOL)doesCustomDrawing;
+ (void)initialize;
@property(retain, nonatomic) NSImage *contents; // @synthesize contents=_contents;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(retain, nonatomic) NSColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
- (void).cxx_destruct;
- (id)description;
- (BOOL)wantsUpdateLayer;
- (void)updateLayer;
- (void)setLayer:(id)arg1;
- (void)applyLayerProperties;
- (void)viewDidMoveToWindow;
- (void)viewDidMoveToSuperview;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
@property(nonatomic) BOOL clearsContextBeforeDrawing;
@property(getter=isFlipped) BOOL flipped;
@property(getter=isOpaque) BOOL opaque;
@property(nonatomic) BOOL clipsToBounds;

// Remaining properties
@property long long layerContentsRedrawPolicy; // @dynamic layerContentsRedrawPolicy;

@end

