//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, VoicePieceCtx;

@interface RegisterVoicePrintRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasStep:1;
    unsigned int hasVoiceTicket:1;
    unsigned int hasPieceData:1;
    unsigned int hasResId:1;
    unsigned int step;
    unsigned int voiceTicket;
    unsigned int resId;
    BaseRequest *baseRequest;
    VoicePieceCtx *pieceData;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetResId:) unsigned int resId; // @synthesize resId;
@property(readonly, nonatomic) BOOL hasResId; // @synthesize hasResId;
@property(retain, nonatomic, setter=SetPieceData:) VoicePieceCtx *pieceData; // @synthesize pieceData;
@property(readonly, nonatomic) BOOL hasPieceData; // @synthesize hasPieceData;
@property(nonatomic, setter=SetVoiceTicket:) unsigned int voiceTicket; // @synthesize voiceTicket;
@property(readonly, nonatomic) BOOL hasVoiceTicket; // @synthesize hasVoiceTicket;
@property(nonatomic, setter=SetStep:) unsigned int step; // @synthesize step;
@property(readonly, nonatomic) BOOL hasStep; // @synthesize hasStep;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

