//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSMutableArray, NSString;

@interface RemindItem : PBGeneratedMessage
{
    unsigned int hasRemindId:1;
    unsigned int hasCreateTime:1;
    unsigned int hasRemindTime:1;
    unsigned int hasFromUser:1;
    unsigned int hasToUserCount:1;
    unsigned int hasFlag:1;
    unsigned int hasContent:1;
    unsigned int remindId;
    unsigned int createTime;
    unsigned int toUserCount;
    unsigned int flag;
    unsigned long long remindTime;
    NSString *fromUser;
    NSMutableArray *mutableToUserListList;
    NSString *content;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetContent:) NSString *content; // @synthesize content;
@property(readonly, nonatomic) BOOL hasContent; // @synthesize hasContent;
@property(nonatomic, setter=SetFlag:) unsigned int flag; // @synthesize flag;
@property(readonly, nonatomic) BOOL hasFlag; // @synthesize hasFlag;
@property(retain, nonatomic) NSMutableArray *mutableToUserListList; // @synthesize mutableToUserListList;
@property(nonatomic, setter=SetToUserCount:) unsigned int toUserCount; // @synthesize toUserCount;
@property(readonly, nonatomic) BOOL hasToUserCount; // @synthesize hasToUserCount;
@property(retain, nonatomic, setter=SetFromUser:) NSString *fromUser; // @synthesize fromUser;
@property(readonly, nonatomic) BOOL hasFromUser; // @synthesize hasFromUser;
@property(nonatomic, setter=SetRemindTime:) unsigned long long remindTime; // @synthesize remindTime;
@property(readonly, nonatomic) BOOL hasRemindTime; // @synthesize hasRemindTime;
@property(nonatomic, setter=SetCreateTime:) unsigned int createTime; // @synthesize createTime;
@property(readonly, nonatomic) BOOL hasCreateTime; // @synthesize hasCreateTime;
@property(nonatomic, setter=SetRemindId:) unsigned int remindId; // @synthesize remindId;
@property(readonly, nonatomic) BOOL hasRemindId; // @synthesize hasRemindId;
- (void).cxx_destruct;
- (void)addToUserList:(id)arg1;
- (void)addToUserListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *toUserList; // @dynamic toUserList;
- (id)toUserListList;
- (id)init;

@end

