//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, SKBuiltinBuffer_t;

@interface RemindSyncRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasSelector:1;
    unsigned int hasKeyBuff:1;
    unsigned int selector;
    BaseRequest *baseRequest;
    SKBuiltinBuffer_t *keyBuff;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetKeyBuff:) SKBuiltinBuffer_t *keyBuff; // @synthesize keyBuff;
@property(readonly, nonatomic) BOOL hasKeyBuff; // @synthesize hasKeyBuff;
@property(nonatomic, setter=SetSelector:) unsigned int selector; // @synthesize selector;
@property(readonly, nonatomic) BOOL hasSelector; // @synthesize hasSelector;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

