//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@interface ResetPawInfo : PBGeneratedMessage
{
    unsigned int hasCreateTime:1;
    unsigned int hasIsReset:1;
    unsigned int hasId:1;
    unsigned int id_;
    unsigned int createTime;
    unsigned int isReset;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetId:) unsigned int id; // @synthesize id=id_;
@property(readonly, nonatomic) BOOL hasId; // @synthesize hasId;
@property(nonatomic, setter=SetIsReset:) unsigned int isReset; // @synthesize isReset;
@property(readonly, nonatomic) BOOL hasIsReset; // @synthesize hasIsReset;
@property(nonatomic, setter=SetCreateTime:) unsigned int createTime; // @synthesize createTime;
@property(readonly, nonatomic) BOOL hasCreateTime; // @synthesize hasCreateTime;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

