//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class SKBuiltinBuffer_t;

@interface ResourceCtx : PBGeneratedMessage
{
    unsigned int hasResId:1;
    unsigned int hasResData:1;
    unsigned int resId;
    SKBuiltinBuffer_t *resData;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetResData:) SKBuiltinBuffer_t *resData; // @synthesize resData;
@property(readonly, nonatomic) BOOL hasResData; // @synthesize hasResData;
@property(nonatomic, setter=SetResId:) unsigned int resId; // @synthesize resId;
@property(readonly, nonatomic) BOOL hasResId; // @synthesize hasResId;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

