//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSScroller.h"

@interface RFOverlayScroller : NSScroller
{
}

+ (double)zeroWidth;
+ (BOOL)isCompatibleWithOverlayScrollers;
- (void)fadeOut;
- (void)mouseMoved:(id)arg1;
- (void)mouseEntered:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)setFloatValue:(float)arg1;
- (void)drawKnobSlotInRect:(struct CGRect)arg1 highlight:(BOOL)arg2;
- (void)commonInitializer;
- (void)awakeFromNib;
- (id)initWithFrame:(struct CGRect)arg1;

@end

