//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, StatReportExtInfo, StatReportInfo;

@interface StatReportRequest : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasInfo:1;
    unsigned int hasExtInfo:1;
    BaseRequest *baseRequest;
    StatReportInfo *info;
    StatReportExtInfo *extInfo;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetExtInfo:) StatReportExtInfo *extInfo; // @synthesize extInfo;
@property(readonly, nonatomic) BOOL hasExtInfo; // @synthesize hasExtInfo;
@property(retain, nonatomic, setter=SetInfo:) StatReportInfo *info; // @synthesize info;
@property(readonly, nonatomic) BOOL hasInfo; // @synthesize hasInfo;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

