//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSMutableArray;

@interface StrategyTable : PBGeneratedMessage
{
    NSMutableArray *mutableStgintersList;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *mutableStgintersList; // @synthesize mutableStgintersList;
- (void).cxx_destruct;
- (void)addStginters:(id)arg1;
- (void)addStgintersFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *stginters; // @dynamic stginters;
- (id)stgintersList;
- (id)init;

@end

