//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface TrackPOIItem : PBGeneratedMessage
{
    unsigned int hasLatitude:1;
    unsigned int hasLongitude:1;
    unsigned int hasName:1;
    unsigned int hasAddr:1;
    double latitude;
    double longitude;
    NSString *name;
    NSString *addr;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetAddr:) NSString *addr; // @synthesize addr;
@property(readonly, nonatomic) BOOL hasAddr; // @synthesize hasAddr;
@property(retain, nonatomic, setter=SetName:) NSString *name; // @synthesize name;
@property(readonly, nonatomic) BOOL hasName; // @synthesize hasName;
@property(nonatomic, setter=SetLongitude:) double longitude; // @synthesize longitude;
@property(readonly, nonatomic) BOOL hasLongitude; // @synthesize hasLongitude;
@property(nonatomic, setter=SetLatitude:) double latitude; // @synthesize latitude;
@property(readonly, nonatomic) BOOL hasLatitude; // @synthesize hasLatitude;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

