//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface UIUtil : NSObject
{
}

+ (id)addEffect:(long long)arg1 toView:(id)arg2 blendingMode:(long long)arg3 maskView:(id)arg4;
+ (id)addEffect:(long long)arg1 toView:(id)arg2 blendingMode:(long long)arg3 maskType:(long long)arg4;
+ (id)addEffect:(long long)arg1 toView:(id)arg2 blendingMode:(long long)arg3 appearanceName:(id)arg4;
+ (id)addEffect:(long long)arg1 toView:(id)arg2 blendingMode:(long long)arg3 state:(long long)arg4;
+ (id)addEffect:(long long)arg1 toView:(id)arg2 blendingMode:(long long)arg3;
+ (id)addEffect:(long long)arg1 toView:(id)arg2;
+ (BOOL)supportVibrancy;

@end

