//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class LifePoiInfo, NSMutableArray;

@interface UxLifePoiItem : PBGeneratedMessage
{
    unsigned int hasPoi:1;
    unsigned int hasPoibitset:1;
    unsigned int poibitset;
    LifePoiInfo *poi;
    NSMutableArray *mutableReasonList;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetPoibitset:) unsigned int poibitset; // @synthesize poibitset;
@property(readonly, nonatomic) BOOL hasPoibitset; // @synthesize hasPoibitset;
@property(retain, nonatomic) NSMutableArray *mutableReasonList; // @synthesize mutableReasonList;
@property(retain, nonatomic, setter=SetPoi:) LifePoiInfo *poi; // @synthesize poi;
@property(readonly, nonatomic) BOOL hasPoi; // @synthesize hasPoi;
- (void).cxx_destruct;
- (void)addReasonFromArray:(id)arg1;
- (void)addReason:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *reason; // @dynamic reason;
- (id)reasonList;
- (id)init;

@end

