//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class LifeLocation;

@interface UxLifeGetFavPoiListReq : PBGeneratedMessage
{
    unsigned int hasLocation:1;
    LifeLocation *location;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetLocation:) LifeLocation *location; // @synthesize location;
@property(readonly, nonatomic) BOOL hasLocation; // @synthesize hasLocation;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

