//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray;

@interface UxLifeGetUserCommentPoiListResp : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasViewcount:1;
    unsigned int viewcount;
    BaseResponse *baseResponse;
    NSMutableArray *mutableCommentPoiListList;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetViewcount:) unsigned int viewcount; // @synthesize viewcount;
@property(readonly, nonatomic) BOOL hasViewcount; // @synthesize hasViewcount;
@property(retain, nonatomic) NSMutableArray *mutableCommentPoiListList; // @synthesize mutableCommentPoiListList;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addCommentPoiList:(id)arg1;
- (void)addCommentPoiListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *commentPoiList; // @dynamic commentPoiList;
- (id)commentPoiListList;
- (id)init;

@end

