//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class SKBuiltinBuffer_t;

@interface VoicePieceCtx : PBGeneratedMessage
{
    unsigned int hasStartPos:1;
    unsigned int hasPieceLen:1;
    unsigned int hasPieceFlag:1;
    unsigned int hasPieceData:1;
    unsigned int startPos;
    unsigned int pieceLen;
    unsigned int pieceFlag;
    SKBuiltinBuffer_t *pieceData;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetPieceData:) SKBuiltinBuffer_t *pieceData; // @synthesize pieceData;
@property(readonly, nonatomic) BOOL hasPieceData; // @synthesize hasPieceData;
@property(nonatomic, setter=SetPieceFlag:) unsigned int pieceFlag; // @synthesize pieceFlag;
@property(readonly, nonatomic) BOOL hasPieceFlag; // @synthesize hasPieceFlag;
@property(nonatomic, setter=SetPieceLen:) unsigned int pieceLen; // @synthesize pieceLen;
@property(readonly, nonatomic) BOOL hasPieceLen; // @synthesize hasPieceLen;
@property(nonatomic, setter=SetStartPos:) unsigned int startPos; // @synthesize startPos;
@property(readonly, nonatomic) BOOL hasStartPos; // @synthesize hasStartPos;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

