//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseRequest, NSString, SKBuiltinBuffer_t, VoipCmdList;

@interface VoipSyncReq : PBGeneratedMessage
{
    unsigned int hasBaseRequest:1;
    unsigned int hasFromUsername:1;
    unsigned int hasRoomId:1;
    unsigned int hasKeyBuf:1;
    unsigned int hasOpLog:1;
    unsigned int hasRoomKey:1;
    unsigned int hasSelector:1;
    unsigned int hasTimestamp64:1;
    int roomId;
    int selector;
    BaseRequest *baseRequest;
    NSString *fromUsername;
    SKBuiltinBuffer_t *keyBuf;
    VoipCmdList *opLog;
    long long roomKey;
    unsigned long long timestamp64;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetTimestamp64:) unsigned long long timestamp64; // @synthesize timestamp64;
@property(readonly, nonatomic) BOOL hasTimestamp64; // @synthesize hasTimestamp64;
@property(nonatomic, setter=SetSelector:) int selector; // @synthesize selector;
@property(readonly, nonatomic) BOOL hasSelector; // @synthesize hasSelector;
@property(nonatomic, setter=SetRoomKey:) long long roomKey; // @synthesize roomKey;
@property(readonly, nonatomic) BOOL hasRoomKey; // @synthesize hasRoomKey;
@property(retain, nonatomic, setter=SetOpLog:) VoipCmdList *opLog; // @synthesize opLog;
@property(readonly, nonatomic) BOOL hasOpLog; // @synthesize hasOpLog;
@property(retain, nonatomic, setter=SetKeyBuf:) SKBuiltinBuffer_t *keyBuf; // @synthesize keyBuf;
@property(readonly, nonatomic) BOOL hasKeyBuf; // @synthesize hasKeyBuf;
@property(nonatomic, setter=SetRoomId:) int roomId; // @synthesize roomId;
@property(readonly, nonatomic) BOOL hasRoomId; // @synthesize hasRoomId;
@property(retain, nonatomic, setter=SetFromUsername:) NSString *fromUsername; // @synthesize fromUsername;
@property(readonly, nonatomic) BOOL hasFromUsername; // @synthesize hasFromUsername;
@property(retain, nonatomic, setter=SetBaseRequest:) BaseRequest *baseRequest; // @synthesize baseRequest;
@property(readonly, nonatomic) BOOL hasBaseRequest; // @synthesize hasBaseRequest;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

