//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSMutableArray;

@interface VoipCompleteStatusList : PBGeneratedMessage
{
    unsigned int hasCount:1;
    unsigned int hasSeq:1;
    int count;
    unsigned int seq;
    NSMutableArray *mutableCompleteStatusList;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetSeq:) unsigned int seq; // @synthesize seq;
@property(readonly, nonatomic) BOOL hasSeq; // @synthesize hasSeq;
@property(retain, nonatomic) NSMutableArray *mutableCompleteStatusList; // @synthesize mutableCompleteStatusList;
@property(nonatomic, setter=SetCount:) int count; // @synthesize count;
@property(readonly, nonatomic) BOOL hasCount; // @synthesize hasCount;
- (void).cxx_destruct;
- (void)addCompleteStatus:(id)arg1;
- (void)addCompleteStatusFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *completeStatus; // @dynamic completeStatus;
- (id)completeStatusList;
- (id)init;

@end

