//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSData;

@interface VOIPRUDPCmd : PBGeneratedMessage
{
    unsigned int hasCmdType:1;
    unsigned int hasCmdBuffer:1;
    int cmdType;
    NSData *cmdBuffer;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetCmdBuffer:) NSData *cmdBuffer; // @synthesize cmdBuffer;
@property(readonly, nonatomic) BOOL hasCmdBuffer; // @synthesize hasCmdBuffer;
@property(nonatomic, setter=SetCmdType:) int cmdType; // @synthesize cmdType;
@property(readonly, nonatomic) BOOL hasCmdType; // @synthesize hasCmdType;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

