//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSSlider.h"

@interface WeNoteSlider : NSSlider
{
}

- (id)sliderCell;
- (id)initWithKnobImage:(id)arg1 minimumValueImage:(id)arg2 maximumValueImage:(id)arg3 delegate:(id)arg4;
- (id)initWithKnobImage:(id)arg1;
- (void)setNeedsDisplayInRect:(struct CGRect)arg1;

@end

