//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString, SKBuiltinBuffer_t;

@interface WTLoginImgReqInfo : PBGeneratedMessage
{
    unsigned int hasImgSid:1;
    unsigned int hasImgCode:1;
    unsigned int hasImgEncryptKey:1;
    unsigned int hasKsid:1;
    NSString *imgSid;
    NSString *imgCode;
    NSString *imgEncryptKey;
    SKBuiltinBuffer_t *ksid;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetKsid:) SKBuiltinBuffer_t *ksid; // @synthesize ksid;
@property(readonly, nonatomic) BOOL hasKsid; // @synthesize hasKsid;
@property(retain, nonatomic, setter=SetImgEncryptKey:) NSString *imgEncryptKey; // @synthesize imgEncryptKey;
@property(readonly, nonatomic) BOOL hasImgEncryptKey; // @synthesize hasImgEncryptKey;
@property(retain, nonatomic, setter=SetImgCode:) NSString *imgCode; // @synthesize imgCode;
@property(readonly, nonatomic) BOOL hasImgCode; // @synthesize hasImgCode;
@property(retain, nonatomic, setter=SetImgSid:) NSString *imgSid; // @synthesize imgSid;
@property(readonly, nonatomic) BOOL hasImgSid; // @synthesize hasImgSid;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

