//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class NSString;

@interface WxaSearchInfo : PBGeneratedMessage
{
    unsigned int hasH5Version:1;
    unsigned int hasSubType:1;
    unsigned int hasSessionId:1;
    unsigned int hasKeywordId:1;
    unsigned int hasWordingId:1;
    unsigned int hasSugPos:1;
    unsigned int h5Version;
    unsigned int subType;
    unsigned int sugPos;
    NSString *sessionId;
    NSString *keywordId;
    NSString *wordingId;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetSugPos:) unsigned int sugPos; // @synthesize sugPos;
@property(readonly, nonatomic) BOOL hasSugPos; // @synthesize hasSugPos;
@property(retain, nonatomic, setter=SetWordingId:) NSString *wordingId; // @synthesize wordingId;
@property(readonly, nonatomic) BOOL hasWordingId; // @synthesize hasWordingId;
@property(retain, nonatomic, setter=SetKeywordId:) NSString *keywordId; // @synthesize keywordId;
@property(readonly, nonatomic) BOOL hasKeywordId; // @synthesize hasKeywordId;
@property(retain, nonatomic, setter=SetSessionId:) NSString *sessionId; // @synthesize sessionId;
@property(readonly, nonatomic) BOOL hasSessionId; // @synthesize hasSessionId;
@property(nonatomic, setter=SetSubType:) unsigned int subType; // @synthesize subType;
@property(readonly, nonatomic) BOOL hasSubType; // @synthesize hasSubType;
@property(nonatomic, setter=SetH5Version:) unsigned int h5Version; // @synthesize h5Version;
@property(readonly, nonatomic) BOOL hasH5Version; // @synthesize hasH5Version;
- (void).cxx_destruct;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
- (id)init;

@end

