//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSUserNotificationCenterDelegate.h"

@class CNUserNotification, CNUserNotificationCenter;

@protocol CNUserNotificationCenterDelegate <NSUserNotificationCenterDelegate>

@optional
- (void)refuseVoipFromNotification;
- (void)acceptVoipFromNotification;
- (void)userNotificationCenter:(CNUserNotificationCenter *)arg1 didDeliverNotification:(CNUserNotification *)arg2;
- (void)userNotificationCenter:(CNUserNotificationCenter *)arg1 didActivateNotification:(CNUserNotification *)arg2;
- (BOOL)userNotificationCenter:(CNUserNotificationCenter *)arg1 shouldPresentNotification:(CNUserNotification *)arg2;
@end

