//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSWindowController.h"

@class CNUserNotification, CNUserNotificationBannerButton, NSDictionary, NSImageView, NSTextField, NSTimer;

@interface CNUserNotificationBannerController : NSWindowController
{
    NSDictionary *_userInfo;
    CNUserNotification *_userNotification;
    CDUnknownBlockType _bannerActivationHandler;
    double _labelWidth;
    unsigned long long _informativeTextLineBreakMode;
    double _calculatedButtonWidth;
    BOOL _hasActionButton;
    struct CGSize _bannerSize;
    struct CGSize _bannerImageSize;
    struct CGSize _buttonSize;
    BOOL _animationIsRunning;
    id <CNUserNotificationCenterDelegate> _delegate;
    NSTextField *_title;
    NSTextField *_subtitle;
    NSTextField *_informativeText;
    NSImageView *_bannerImageView;
    CNUserNotificationBannerButton *_actionButton;
    CNUserNotificationBannerButton *_otherButton;
    NSTimer *_dismissTimer;
}

@property(retain) NSTimer *dismissTimer; // @synthesize dismissTimer=_dismissTimer;
@property BOOL animationIsRunning; // @synthesize animationIsRunning=_animationIsRunning;
@property(retain) CNUserNotificationBannerButton *otherButton; // @synthesize otherButton=_otherButton;
@property(retain) CNUserNotificationBannerButton *actionButton; // @synthesize actionButton=_actionButton;
@property(retain, nonatomic) NSImageView *bannerImageView; // @synthesize bannerImageView=_bannerImageView;
@property(retain, nonatomic) NSTextField *informativeText; // @synthesize informativeText=_informativeText;
@property(retain, nonatomic) NSTextField *subtitle; // @synthesize subtitle=_subtitle;
@property(retain, nonatomic) NSTextField *title; // @synthesize title=_title;
@property(retain) id <CNUserNotificationCenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)mouseUp:(id)arg1;
- (double)informativeTextHeightForWidth:(double)arg1;
- (void)configureNotificationBannerConstraints;
- (void)configureNotificationBannerButtons;
- (void)configureNotificationBannerTexts;
- (void)configureNotificationBannerImage;
- (void)configureNotificationBannerWindow;
- (id)labelWithidentifier:(id)arg1 attributedTextValue:(id)arg2 superView:(id)arg3;
- (void)prepareNotificationBanner;
- (void)calculateBannerPositions;
- (void)timedBannerDismiss:(id)arg1;
- (void)adjustTextFieldAttributes;
- (void)otherButtonAction;
- (void)actionButtonAction;
- (void)dismissBanner;
- (void)presentBannerDismissAfter:(double)arg1;
- (void)presentBanner;
- (id)initWithNotification:(id)arg1 delegate:(id)arg2 usingActivationHandler:(CDUnknownBlockType)arg3;

@end

