//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray;

__attribute__((visibility("hidden")))
@interface GetContactResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasContactCount:1;
    int retMemoizedSerializedSize;
    unsigned int contactCount;
    BaseResponse *baseResponse;
    NSMutableArray *mutableContactListList;
    NSMutableArray *mutableRetList;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSMutableArray *mutableRetList; // @synthesize mutableRetList;
@property(retain, nonatomic) NSMutableArray *mutableContactListList; // @synthesize mutableContactListList;
@property(nonatomic, setter=SetContactCount:) unsigned int contactCount; // @synthesize contactCount;
@property(readonly, nonatomic) BOOL hasContactCount; // @synthesize hasContactCount;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addRetFromArray:(id)arg1;
- (void)addRet:(int)arg1;
- (void)addContactList:(id)arg1;
- (void)addContactListFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *ret; // @dynamic ret;
- (id)retList;
@property(retain, nonatomic) NSMutableArray *contactList; // @dynamic contactList;
- (id)contactListList;
- (id)init;

@end

