//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray, NSString, SKBuiltinBuffer_t;

__attribute__((visibility("hidden")))
@interface GetPOIListResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasListCount:1;
    unsigned int hasOpCode:1;
    unsigned int hasIsEnd:1;
    unsigned int hasBuff:1;
    unsigned int hasUrl:1;
    unsigned int hasLogoUrl:1;
    unsigned int hasText:1;
    unsigned int hasOpenId:1;
    unsigned int listCount;
    unsigned int opCode;
    unsigned int isEnd;
    BaseResponse *baseResponse;
    NSMutableArray *mutablePoilistList;
    SKBuiltinBuffer_t *buff;
    NSString *url;
    NSString *logoUrl;
    NSString *text;
    NSString *openId;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic, setter=SetOpenId:) NSString *openId; // @synthesize openId;
@property(readonly, nonatomic) BOOL hasOpenId; // @synthesize hasOpenId;
@property(retain, nonatomic, setter=SetText:) NSString *text; // @synthesize text;
@property(readonly, nonatomic) BOOL hasText; // @synthesize hasText;
@property(retain, nonatomic, setter=SetLogoUrl:) NSString *logoUrl; // @synthesize logoUrl;
@property(readonly, nonatomic) BOOL hasLogoUrl; // @synthesize hasLogoUrl;
@property(retain, nonatomic, setter=SetUrl:) NSString *url; // @synthesize url;
@property(readonly, nonatomic) BOOL hasUrl; // @synthesize hasUrl;
@property(retain, nonatomic, setter=SetBuff:) SKBuiltinBuffer_t *buff; // @synthesize buff;
@property(readonly, nonatomic) BOOL hasBuff; // @synthesize hasBuff;
@property(nonatomic, setter=SetIsEnd:) unsigned int isEnd; // @synthesize isEnd;
@property(readonly, nonatomic) BOOL hasIsEnd; // @synthesize hasIsEnd;
@property(nonatomic, setter=SetOpCode:) unsigned int opCode; // @synthesize opCode;
@property(readonly, nonatomic) BOOL hasOpCode; // @synthesize hasOpCode;
@property(retain, nonatomic) NSMutableArray *mutablePoilistList; // @synthesize mutablePoilistList;
@property(nonatomic, setter=SetListCount:) unsigned int listCount; // @synthesize listCount;
@property(readonly, nonatomic) BOOL hasListCount; // @synthesize hasListCount;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addPoilist:(id)arg1;
- (void)addPoilistFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *poilist; // @dynamic poilist;
- (id)poilistList;
- (id)init;

@end

