//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSRegularExpression;

__attribute__((visibility("hidden")))
@interface MessageTextFormatter : NSObject
{
    NSRegularExpression *_emojiScannerRegexp;
    NSRegularExpression *_hyperlinkScannerRegexp;
    NSRegularExpression *_emailScannerRegexp;
    NSMutableArray *_emoticonMatchDicArray;
    NSMutableDictionary *_emoticonWordsByLanguage;
    NSArray *_englishEmoticonTokens;
    NSArray *_chineseEmoticonTokens;
    NSMutableDictionary *_emoticonStringCaches;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableDictionary *emoticonStringCaches; // @synthesize emoticonStringCaches=_emoticonStringCaches;
@property(retain, nonatomic) NSArray *chineseEmoticonTokens; // @synthesize chineseEmoticonTokens=_chineseEmoticonTokens;
@property(retain, nonatomic) NSArray *englishEmoticonTokens; // @synthesize englishEmoticonTokens=_englishEmoticonTokens;
@property(retain, nonatomic) NSMutableDictionary *emoticonWordsByLanguage; // @synthesize emoticonWordsByLanguage=_emoticonWordsByLanguage;
@property(retain, nonatomic) NSMutableArray *emoticonMatchDicArray; // @synthesize emoticonMatchDicArray=_emoticonMatchDicArray;
@property(retain, nonatomic) NSRegularExpression *emailScannerRegexp; // @synthesize emailScannerRegexp=_emailScannerRegexp;
@property(retain, nonatomic) NSRegularExpression *hyperlinkScannerRegexp; // @synthesize hyperlinkScannerRegexp=_hyperlinkScannerRegexp;
@property(retain, nonatomic) NSRegularExpression *emojiScannerRegexp; // @synthesize emojiScannerRegexp=_emojiScannerRegexp;
- (void).cxx_destruct;
- (id)QQEmoticonImageForRepresentationalString:(id)arg1;
- (id)allQQEmoticonWordsForCurrentLocale;
- (id)allQQEmoticonWordsForLanguage:(id)arg1;
- (void)setupScanner;
- (void)_addEmoticonArray:(id)arg1 regexpTokens:(id)arg2 emoticonMatchDicArray:(id)arg3;
- (id)_emoticonAttributeStringWith:(id)arg1 emojiSize:(id)arg2 useCoreText:(BOOL)arg3;
- (id)dataArrayFromAttributedString:(id)arg1;
- (id)stringFromAttributedString:(id)arg1;
- (id)editHyperlinksWithAttributedString:(id)arg1 shouldFormatEmail:(BOOL)arg2;
- (id)editFontSizeWithAttributedString:(id)arg1 sizeAdjustments:(unsigned long long)arg2 extraAttrs:(id)arg3;
- (id)editQQEmojiWithAttributedString:(id)arg1 originalText:(id)arg2 specifiedEmojiSize:(id)arg3 useCoreText:(BOOL)arg4;
- (id)attributedStringFromString:(id)arg1 withFormattingOptions:(id)arg2;
- (id)attributedStringFromString:(id)arg1;
- (id)init;

@end

