//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCContactData;

__attribute__((visibility("hidden")))
@interface MMChatBackupSessionPickRow : NSObject
{
    BOOL _chosen;
    WCContactData *_contact;
    unsigned long long _totalSize;
}

@property(nonatomic) unsigned long long totalSize; // @synthesize totalSize=_totalSize;
@property(nonatomic) BOOL chosen; // @synthesize chosen=_chosen;
@property(retain, nonatomic) WCContactData *contact; // @synthesize contact=_contact;
- (void).cxx_destruct;

@end

