//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "LocalAreaNetworkServerDelegate.h"
#import "MMCGIDelegate.h"
#import "MMChatBackupBasicLogicDelegate.h"

@class LocalAreaNetworkServer, MMChatBackupBackupLogic, MMChatBackupBasicLogic, MMChatBackupRecoverLogic, MMChatLogProtoHandler, MMTimer, NSString;

__attribute__((visibility("hidden")))
@interface MMChatBackupServerLogic : NSObject <LocalAreaNetworkServerDelegate, MMChatBackupBasicLogicDelegate, MMCGIDelegate>
{
    BOOL m_bServerLogicStop;
    BOOL m_bStartConnect;
    BOOL m_bPrepareStart;
    BOOL m_bStartTransfer;
    LocalAreaNetworkServer *m_networkHandler;
    MMChatLogProtoHandler *m_protoHandler;
    MMChatBackupBasicLogic *m_processLogic;
    long long m_backupAndRecoverType;
    MMTimer *m_transferSpeedTimer;
    MMTimer *m_connectClientTimer;
    MMTimer *m_transferClientTimer;
    BOOL m_bDone;
    MMChatBackupBackupLogic *backupLogic;
    MMChatBackupRecoverLogic *recoverLogic;
    id <MMChatBackupServerLogicDelegate> _serverLogicDelegate;
}

@property(nonatomic) __weak id <MMChatBackupServerLogicDelegate> serverLogicDelegate; // @synthesize serverLogicDelegate=_serverLogicDelegate;
- (void).cxx_destruct;
- (void)processOnMainThreadCurrentSession:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)processCurrentSession:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)processOnMainThreadNotifyCode:(unsigned long long)arg1;
- (void)processNotifyCode:(unsigned long long)arg1;
- (void)onBasicProgresssCurrentSession:(unsigned long long)arg1 totalSession:(unsigned long long)arg2;
- (void)onBasicLogicNotifyEvent:(unsigned long long)arg1;
- (BOOL)onBasicLogicSendData:(id)arg1;
- (void)onDisconnect;
- (void)onConnected;
- (void)onReciveData:(id)arg1 andLength:(unsigned int)arg2;
- (void)sendHeartBeatRequestWithAck:(unsigned long long)arg1;
- (void)sendHeartBeatResponseWithAck:(unsigned long long)arg1;
- (BOOL)sendCommandResponseWithCommand:(int)arg1;
- (BOOL)sendData:(id)arg1;
- (void)p_processHeartBeatResponseData:(id)arg1;
- (void)p_processHeartBeatRequestData:(id)arg1;
- (void)p_processCancelRequestData:(id)arg1;
- (void)p_processCommandResponseData:(id)arg1;
- (void)p_processCommandRequestData:(id)arg1;
- (void)p_processAuthenticateRequestData:(id)arg1;
- (void)processSvrIDRequest:(id)arg1;
- (void)p_dataProcess:(id)arg1 andLength:(unsigned int)arg2;
- (void)OnResponseCGI:(BOOL)arg1 sessionId:(unsigned int)arg2 cgiWrap:(id)arg3;
- (void)getConnectInfo:(id)arg1;
- (void)getQRCodeWithIP:(id)arg1 Port:(unsigned short)arg2 WifiName:(id)arg3 TotalSize:(unsigned long long)arg4;
- (void)resetTransferConnectTimer;
- (void)checkTransferConnect;
- (void)checkTransferSpeed;
- (void)checkConnectWithClient;
- (void)startConnect;
- (void)sendCancelRequest;
- (void)cancelLogic;
- (void)stopWorkLogic;
- (void)startWorkLogic;
- (void)stopServerLogic;
- (void)startServerLogic;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

