//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface MMContactCardData : NSObject
{
    unsigned int _certFlag;
    unsigned int _sex;
    NSString *_userName;
    NSString *_aliasName;
    NSString *_nickName;
    NSString *_avatarUrl;
    NSString *_province;
    NSString *_city;
    NSString *_signature;
    NSString *_country;
}

+ (id)dataWithXMLString:(id)arg1;
@property(retain, nonatomic) NSString *country; // @synthesize country=_country;
@property(nonatomic) unsigned int sex; // @synthesize sex=_sex;
@property(nonatomic) unsigned int certFlag; // @synthesize certFlag=_certFlag;
@property(retain, nonatomic) NSString *signature; // @synthesize signature=_signature;
@property(retain, nonatomic) NSString *city; // @synthesize city=_city;
@property(retain, nonatomic) NSString *province; // @synthesize province=_province;
@property(retain, nonatomic) NSString *avatarUrl; // @synthesize avatarUrl=_avatarUrl;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *aliasName; // @synthesize aliasName=_aliasName;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void).cxx_destruct;
- (BOOL)isOfficialAccount;
- (BOOL)isGroup;
- (id)displayName;
- (id)displayUserName;
- (id)friendContact;
- (BOOL)isContactAlreadyAdded;
- (id)description;

@end

