//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WCDataBase, WCDataBaseTable;

__attribute__((visibility("hidden")))
@interface MMEmoticonDB : NSObject
{
    WCDataBase *_database;
    WCDataBaseTable *_packagesTable;
    WCDataBaseTable *_emoticonsTable;
    WCDataBaseTable *_captionsTable;
}

- (void).cxx_destruct;
- (BOOL)deletePackageWithPackageId:(id)arg1;
- (BOOL)deletePackage:(id)arg1;
- (BOOL)deleteEmoticonAndCaptions:(id)arg1;
- (BOOL)insertOrUpdateEmoticonRow:(id)arg1;
- (id)emoticonRowsForPackageId:(id)arg1;
- (id)downloadedPackIDs;
- (id)downloadedPacks;
- (BOOL)insertOrUpdatePackageRow:(id)arg1;
- (id)insertPackageFromStoreInfo:(id)arg1;
- (id)packageWithId:(id)arg1;
- (BOOL)createTable;
- (void)recreateDb;
- (id)init;

@end

