//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "AccountServiceExt.h"
#import "JNWCollectionViewDataSource.h"
#import "JNWCollectionViewDelegate.h"
#import "JNWCollectionViewGridLayoutDelegate.h"
#import "JNWCollectionViewListLayoutDelegate.h"
#import "MMFavoriteItemViewerWindowDelegate.h"
#import "MMFavoritesDetailCellDelegate.h"
#import "MMFavoritesMgrExt.h"
#import "MMPreviewPanelDataSource.h"
#import "MMPreviewPanelDelegate.h"
#import "NSDraggingSource.h"
#import "NSSearchFieldDelegate.h"
#import "NSTextFieldDelegate.h"

@class MMDivider, MMDraggingOverlayView, MMFavoriteCollectionView, MMFavoritesCollectionData, MMPreviewPanel, MMSessionPickerWindow, MMTimer, MMWindowHandleView, NSArray, NSString, NSTextField, NSView;

__attribute__((visibility("hidden")))
@interface MMFavoriteDetailViewContoller : MMViewController <JNWCollectionViewDelegate, JNWCollectionViewDataSource, JNWCollectionViewGridLayoutDelegate, JNWCollectionViewListLayoutDelegate, MMFavoritesDetailCellDelegate, NSTextFieldDelegate, NSDraggingSource, MMFavoritesMgrExt, MMFavoriteItemViewerWindowDelegate, AccountServiceExt, NSSearchFieldDelegate, MMPreviewPanelDelegate, MMPreviewPanelDataSource>
{
    NSArray *_cellsBeingDragged;
    id <MMFavoriteDetailViewContollerDelegate> _delegate;
    MMFavoriteCollectionView *_collectionView;
    unsigned long long _currentLayoutStyle;
    MMWindowHandleView *_headerView;
    NSTextField *_titleTextField;
    MMDivider *_divider;
    MMDraggingOverlayView *_draggingOverlayView;
    id _mouseDraggedEvent;
    MMFavoritesCollectionData *_data;
    MMSessionPickerWindow *_sessionPickerWindow;
    MMTimer *_timer;
    unsigned long long _lastCalledSearchTime;
    NSString *_searchingString;
    NSView *_noSearchResultView;
    MMPreviewPanel *_previewPanel;
    NSArray *_allPreviewItems;
}

@property(retain, nonatomic) NSArray *allPreviewItems; // @synthesize allPreviewItems=_allPreviewItems;
@property(retain, nonatomic) MMPreviewPanel *previewPanel; // @synthesize previewPanel=_previewPanel;
@property(nonatomic) __weak NSView *noSearchResultView; // @synthesize noSearchResultView=_noSearchResultView;
@property(retain, nonatomic) NSString *searchingString; // @synthesize searchingString=_searchingString;
@property(nonatomic) unsigned long long lastCalledSearchTime; // @synthesize lastCalledSearchTime=_lastCalledSearchTime;
@property(retain, nonatomic) MMTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) MMSessionPickerWindow *sessionPickerWindow; // @synthesize sessionPickerWindow=_sessionPickerWindow;
@property(retain, nonatomic) MMFavoritesCollectionData *data; // @synthesize data=_data;
@property(retain, nonatomic) id mouseDraggedEvent; // @synthesize mouseDraggedEvent=_mouseDraggedEvent;
@property(retain, nonatomic) MMDraggingOverlayView *draggingOverlayView; // @synthesize draggingOverlayView=_draggingOverlayView;
@property(retain, nonatomic) MMDivider *divider; // @synthesize divider=_divider;
@property(retain, nonatomic) NSTextField *titleTextField; // @synthesize titleTextField=_titleTextField;
@property(retain, nonatomic) MMWindowHandleView *headerView; // @synthesize headerView=_headerView;
@property(nonatomic) unsigned long long currentLayoutStyle; // @synthesize currentLayoutStyle=_currentLayoutStyle;
@property(nonatomic) __weak MMFavoriteCollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <MMFavoriteDetailViewContollerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)handleCellUpdateNotification;
- (void)previewPanelDidClose:(id)arg1;
- (id)previewPanel:(id)arg1 shareContentAtIndex:(long long)arg2;
- (id)previewPanel:(id)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewPanel:(id)arg1;
- (struct CGRect)previewPanel:(id)arg1 sourceFrameOnScreenForPreviewItem:(id)arg2;
- (unsigned long long)previewIndexForFavItem:(id)arg1;
- (void)favoritesMgrDidUpdatedItemWithLocalID:(unsigned int)arg1;
- (void)favoritesMgrDidUpdateTags:(id)arg1 forItemLocalID:(unsigned int)arg2;
- (void)favoritesMgrDidUpdatedItemsWtihLocalIDArray:(id)arg1;
- (void)favoritesMgrDidRemoveItemWithFavIDs:(id)arg1;
- (void)favoritesMgrDidAddItems:(id)arg1;
- (void)_exportFileItems:(id)arg1;
- (void)_downloadSelectedFiles;
- (void)_shareItemsAtIndexPaths:(id)arg1;
- (void)_actuallyDeleteItems:(id)arg1;
- (void)_deleteItems:(id)arg1;
- (void)paste:(id)arg1;
- (void)_copyFavoritesItems:(id)arg1;
- (BOOL)control:(id)arg1 textView:(id)arg2 doCommandBySelector:(SEL)arg3;
- (void)clearSearch;
- (void)doSearch;
- (void)searchWithKeyword:(id)arg1;
@property(readonly, nonatomic) BOOL isSearching;
- (void)draggingSession:(id)arg1 endedAtPoint:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (id)_selectedItems;
- (void)cellDragged:(id)arg1 dragEvent:(id)arg2 originalPosition:(struct CGPoint)arg3;
- (void)_contextMenuShowSourceDebugTool;
- (void)_contextMenuShowXML:(id)arg1;
- (void)_contextMenuDelete:(id)arg1;
- (void)_contextMenuCopy:(id)arg1;
- (void)_contextMenuOpen:(id)arg1;
- (void)_contextMenuExport:(id)arg1;
- (void)_contextMenuShare:(id)arg1;
- (void)closedContextMenuFromCell:(id)arg1;
- (void)openedContextMenuFromCell:(id)arg1 fromButton:(BOOL)arg2;
- (id)contextMenuForCell:(id)arg1 forEvent:(id)arg2;
- (void)keyDown:(id)arg1;
- (void)windowDidColsed:(id)arg1;
- (id)nextViewerFavoritesItem:(id)arg1 needAsSameKind:(BOOL)arg2;
- (id)previousViewerFavoritesItem:(id)arg1 needAsSameKind:(BOOL)arg2;
- (struct CGRect)originScreenRectForAnimationForWindow:(id)arg1;
- (double)getListRowHeightWithIndexPath:(id)arg1 andWidthConstrain:(double)arg2;
- (double)collectionView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (double)collectionView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (BOOL)isAlertItemDataDownloading:(id)arg1;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionViewGotMouseUpNotInCell:(id)arg1 needAsSameKind:(BOOL)arg2;
- (void)collectionViewGotMouseDownNotInCell:(id)arg1 needAsSameKind:(BOOL)arg2;
- (void)openItems:(id)arg1;
- (void)collectionView:(id)arg1 didDoubleClickItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 mouseUpInItemAtIndexPath:(id)arg2 cell:(id)arg3;
- (void)ensurePreviewPanelClose;
- (void)collectionView:(id)arg1 mouseUpInItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 mouseDownInItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didScrollToItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didDeselectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldDeselectItemAtIndexPath:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (BOOL)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (BOOL)shouldShowSectionHeader;
- (id)collectionView:(id)arg1 viewForSupplementaryViewOfKind:(id)arg2 inSection:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (id)getCollectionViewCellIdWithIndexPath:(id)arg1;
- (unsigned long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (id)getCollectionView;
- (void)downloadThumbnailWithIndexPath:(id)arg1;
- (void)delayDownloadThumbnailWithIndexPath:(id)arg1;
- (void)_saveSelectedItems;
- (void)scrollToLatest:(BOOL)arg1;
- (void)scrollToBottomAnimated:(BOOL)arg1;
- (void)scrollToTopAnimated:(BOOL)arg1;
- (void)scrollToItem:(id)arg1;
- (void)reloadData;
- (void)setupDraggingOverlayView;
- (void)registerCollectionViewCell;
- (void)customHeaderViewColor;
- (void)_setupHeaderView;
- (void)_setupCollectionViewLayout;
- (void)_setupCollectionView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

