//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "IMMSessionMgrExt.h"
#import "IMessageExt.h"
#import "MMService.h"

@class MMFriendRequestDataCollection, NSString;

__attribute__((visibility("hidden")))
@interface MMFriendRequestMgr : MMService <IMessageExt, IMMSessionMgrExt, MMService>
{
    MMFriendRequestDataCollection *_friendRequestDataCollection;
}

+ (void)lazyRegisterExtension;
@property(retain, nonatomic) MMFriendRequestDataCollection *friendRequestDataCollection; // @synthesize friendRequestDataCollection=_friendRequestDataCollection;
- (void).cxx_destruct;
- (void)AskSessionByUserName:(id)arg1 isHandled:(char *)arg2;
- (void)onRecivedContactVerifyMsg:(id)arg1;
- (void)sendVerifyUserRequestWithUserName:(id)arg1 opCode:(int)arg2 verifyMsg:(id)arg3 ticket:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)deleteFriendRequestWithFriendRequestData:(id)arg1;
- (void)acceptFriendRequestWithFriendRequestData:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)acceptFriendRequestWithPushContact:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)addNewFriendWithContact:(id)arg1 verifyMsg:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)addNewFriendWithContact:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (unsigned long long)calculateUnreadRequestSum;
- (void)clearUnreadFriendRequestCount;
- (id)friendRequests;
- (void)saveFriendRequestData;
- (void)loadFriendRequestData;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

