//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSTableCellView.h"

#import "IGroupMgrExt.h"
#import "NSDraggingSource.h"
#import "NSMenuDelegate.h"
#import "NSSharingServiceDelegate.h"
#import "NSSharingServicePickerDelegate.h"

@class MMButton, MMMessageCellAvatarView, MMMessageTableItem, MMView, NSButton, NSImage, NSMenu, NSProgressIndicator, NSString, NSTextField, NSTrackingArea;

__attribute__((visibility("hidden")))
@interface MMMessageCellView : NSTableCellView <NSDraggingSource, NSMenuDelegate, IGroupMgrExt, NSSharingServicePickerDelegate, NSSharingServiceDelegate>
{
    NSImage *_savedDraggingImage;
    NSTrackingArea *_mainTrackingArea;
    NSMenu *_menuFromContextMenuButton;
    BOOL _highlighted;
    BOOL _showGroupChatNickName;
    BOOL _isBeingDragged;
    int _accessoryType;
    id <MMMessageCellViewDelegate> _delegate;
    MMMessageCellAvatarView *_avatarImgView;
    MMView *_contentView;
    NSTextField *_groupChatNickNameLabel;
    MMButton *_checkbox;
    double _hasTopPadding;
    MMMessageTableItem *_messageTableItem;
    NSProgressIndicator *_waitingProgressIndicatorAccessory;
    NSButton *_errorIndicatorAccessory;
    NSButton *_contextMenuButton;
    NSButton *_saveToFavoritesButton;
    struct CGPoint _mouseDownLocation;
}

+ (BOOL)isChoosingMode;
+ (int)getChoosablePaddingLeft;
+ (double)cellHeightWithMessage:(id)arg1 constrainedToWidth:(double)arg2;
+ (Class)cellViewSubclassForMessage:(id)arg1;
+ (id)cellViewWithMessage:(id)arg1;
+ (id)cellIdentifierWithMessage:(id)arg1;
@property(nonatomic) struct CGPoint mouseDownLocation; // @synthesize mouseDownLocation=_mouseDownLocation;
@property(retain, nonatomic) NSButton *saveToFavoritesButton; // @synthesize saveToFavoritesButton=_saveToFavoritesButton;
@property(retain, nonatomic) NSButton *contextMenuButton; // @synthesize contextMenuButton=_contextMenuButton;
@property(retain, nonatomic) NSButton *errorIndicatorAccessory; // @synthesize errorIndicatorAccessory=_errorIndicatorAccessory;
@property(retain, nonatomic) NSProgressIndicator *waitingProgressIndicatorAccessory; // @synthesize waitingProgressIndicatorAccessory=_waitingProgressIndicatorAccessory;
@property(readonly, nonatomic) BOOL isBeingDragged; // @synthesize isBeingDragged=_isBeingDragged;
@property(nonatomic) BOOL showGroupChatNickName; // @synthesize showGroupChatNickName=_showGroupChatNickName;
@property(retain, nonatomic) MMMessageTableItem *messageTableItem; // @synthesize messageTableItem=_messageTableItem;
@property(nonatomic) double hasTopPadding; // @synthesize hasTopPadding=_hasTopPadding;
@property(retain, nonatomic) MMButton *checkbox; // @synthesize checkbox=_checkbox;
@property(nonatomic) int accessoryType; // @synthesize accessoryType=_accessoryType;
@property(nonatomic) BOOL highlighted; // @synthesize highlighted=_highlighted;
@property(retain, nonatomic) NSTextField *groupChatNickNameLabel; // @synthesize groupChatNickNameLabel=_groupChatNickNameLabel;
@property(retain, nonatomic) MMView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) MMMessageCellAvatarView *avatarImgView; // @synthesize avatarImgView=_avatarImgView;
@property(nonatomic) __weak id <MMMessageCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (BOOL)notMoveFar:(id)arg1;
- (void)reshowChosenStyle;
- (void)resetChosenStyle;
- (void)checkboxToggle;
- (void)setIsChosenStyle:(BOOL)arg1;
- (void)setChoosable:(BOOL)arg1;
- (void)OnModifyGroupMemberContact:(id)arg1;
- (void)contextMenuButtonAction:(id)arg1;
- (BOOL)showsSaveToFavoritesButton;
- (BOOL)showsContextMenuButton;
- (struct CGRect)rectForSaveToFavoritesButton;
- (struct CGRect)rectForContextMenuButton;
- (void)handleNewTextSize;
- (struct CGRect)rectForAccessory:(int)arg1;
- (void)resendMessage;
- (void)setErrorIndicatorAccessoryToolTip:(id)arg1;
- (void)layoutAccessories;
- (void)menuDidClose:(id)arg1;
- (void)menuWillOpen:(id)arg1;
- (BOOL)makeMakeMultipleSelectUnavailable;
- (BOOL)allowMultipleSelect;
- (BOOL)makeDeleteUnavailable;
- (BOOL)makeSaveAsUnavailable;
- (BOOL)makeAddToFavoritesUnavailable;
- (BOOL)makeForwardUnavailable;
- (BOOL)makeCopyMenuUnavailable;
- (BOOL)allowShareExtension;
- (BOOL)allowAddToFavorites;
- (BOOL)allowForward;
- (BOOL)allowCopy;
- (BOOL)allowContextMenuForEvent:(id)arg1;
- (void)contextMenuDidClose:(id)arg1;
- (void)contextMenuWillOpen:(id)arg1;
- (void)_contextMenuShowSourceDebugTool;
- (id)sharingServicePicker:(id)arg1 sharingServicesForItems:(id)arg2 proposedSharingServices:(id)arg3;
- (void)contextMenuShareExtension:(id)arg1;
- (id)contentForSharing;
- (void)contextMenuMultipleSelectMessage;
- (void)contextMenuFavorites;
- (void)contextMenuResendMessage;
- (void)contextMenuForward;
- (void)contextMenuDelete;
- (void)contextMenuCopy:(BOOL)arg1;
- (void)contextMenuCopy;
- (void)contextMenuRecall;
- (void)itemAction;
- (id)contextMenuCommonItems;
- (id)validRequestorForSendType:(id)arg1 returnType:(id)arg2;
- (BOOL)writeSelectionToPasteboard:(id)arg1 types:(id)arg2;
- (id)buildShareExtensionMenuItem;
- (id)contextMultipleSelectMenu;
- (id)contextMenu;
- (id)menuForEvent:(id)arg1;
- (id)contextMenuCustomItemsForPosition:(unsigned long long)arg1;
- (void)writeIntoPasteboard:(id)arg1 orItem:(id)arg2 provideDataForType:(id)arg3;
- (void)draggingSession:(id)arg1 endedAtPoint:(struct CGPoint)arg2 operation:(unsigned long long)arg3;
- (void)draggingSession:(id)arg1 movedToPoint:(struct CGPoint)arg2;
- (void)draggingSession:(id)arg1 willBeginAtPoint:(struct CGPoint)arg2;
- (unsigned long long)draggingSession:(id)arg1 sourceOperationMaskForDraggingContext:(long long)arg2;
- (void)mouseUp:(id)arg1;
- (void)mouseDown:(id)arg1;
- (void)mouseDragged:(id)arg1;
- (struct CGRect)draggingFrameForEvent:(id)arg1;
- (id)bubbleImage;
- (id)generatePasteboardItem;
- (id)draggingImage;
- (BOOL)acceptsFirstMouse:(id)arg1;
- (id)draggablePasteboardTypes;
- (BOOL)draggingEnabled;
- (BOOL)eventIsInsideClickableArea:(id)arg1;
- (struct CGRect)clickableArea;
@property(readonly, nonatomic) BOOL isGroupChat;
- (void)_updateContextMenuButtonVisibilityFromMousePosition;
- (void)mouseMoved:(id)arg1;
- (void)mouseExited:(id)arg1;
- (void)mouseEntered:(id)arg1;
@property(readonly, nonatomic) double topPadding;
- (double)_avatarPosX;
- (void)populateWithMessage:(id)arg1;
- (void)prepareForReuse;
- (void)setWaitingProgressIndicatorAccessoryHidden:(BOOL)arg1;
- (void)setNeedsDisplay;
- (void)updateTrackingAreas;
- (void)drawRect:(struct CGRect)arg1;
- (BOOL)allowChoose;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

