//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMMessageCellView, MMMessageTableItem, NSEvent;

@protocol MMMessageCellViewDelegate <NSObject>
- (void)messageCellViewNeedsReload:(MMMessageCellView *)arg1;
- (void)messageCellView:(MMMessageCellView *)arg1 needreload:(NSEvent *)arg2;
- (void)messageCellView:(MMMessageCellView *)arg1 gotMisdirectedKeyDown:(NSEvent *)arg2;
- (void)messageCellViewDidStartForwardMessageCommand:(MMMessageCellView *)arg1;
- (void)messageCellView:(MMMessageCellView *)arg1 didUpdatePreviewContentWithItem:(MMMessageTableItem *)arg2;
- (void)messageCellView:(MMMessageCellView *)arg1 didDoubleClickOnAvatarWithItem:(MMMessageTableItem *)arg2;
- (void)messageCellView:(MMMessageCellView *)arg1 didClickOnAvatarWithItem:(MMMessageTableItem *)arg2;
- (void)messageCellViewNeedsHeightRecalculated:(MMMessageCellView *)arg1;
- (void)messageCellView:(MMMessageCellView *)arg1 showDetailWindowWithItem:(MMMessageTableItem *)arg2;
@end

