//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSString, Reachability;

__attribute__((visibility("hidden")))
@interface MMNetService : MMService <MMService>
{
    BOOL m_isReachable;
    BOOL _m_lastIsReachable;
    int _m_lastNetStatus;
    Reachability *m_reach;
    id <MMNetServiceDelegate> m_delegate;
}

@property int m_lastNetStatus; // @synthesize m_lastNetStatus=_m_lastNetStatus;
@property BOOL m_lastIsReachable; // @synthesize m_lastIsReachable=_m_lastIsReachable;
@property id <MMNetServiceDelegate> m_delegate; // @synthesize m_delegate;
@property BOOL m_isReachable; // @synthesize m_isReachable;
@property(retain, nonatomic) Reachability *m_reach; // @synthesize m_reach;
- (void).cxx_destruct;
- (int)CurrentQQUin;
- (int)CurrentWeixinUin;
- (id)CurrentUserName;
- (BOOL)OnHeadBeatCGIResponse:(const struct AutoBuffer *)arg1;
- (BOOL)GetHeartBeatRequestData:(struct AutoBuffer *)arg1 reqCmdId:(int *)arg2 respCmdId:(int *)arg3;
- (BOOL)IsAuthOK;
- (BOOL)MakeSureAuth;
- (BOOL)IsNetworkReachable;
- (void)SessionTimeout;
- (void)onServiceClearData;
- (void)onServiceInit;
- (void)dealloc;
- (id)init;
- (void)mmnetNotifyStatus:(int)arg1;
- (void)reachabilityChange:(id)arg1;
- (BOOL)checkIsReachable;
- (void)clearReachability;
- (void)configReachability;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

