//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMViewController.h"

#import "MMOAMessageMgrExt.h"
#import "NSTabViewDelegate.h"
#import "NSTableViewDataSource.h"

@class MMView, NSString, NSTableView, NSTextField;

__attribute__((visibility("hidden")))
@interface MMOAViewController : MMViewController <NSTabViewDelegate, NSTableViewDataSource, MMOAMessageMgrExt>
{
    NSTableView *_tableView;
    MMView *_placeholderView;
    NSTextField *_placeholderLabel;
}

@property(retain, nonatomic) NSTextField *placeholderLabel; // @synthesize placeholderLabel=_placeholderLabel;
@property(retain, nonatomic) MMView *placeholderView; // @synthesize placeholderView=_placeholderView;
@property(retain, nonatomic) NSTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)OAMesageMgrDidReceiveNewMessageItems:(id)arg1;
- (void)tableViewSelectionDidChange:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (double)tableView:(id)arg1 heightOfRow:(long long)arg2;
- (long long)numberOfRowsInTableView:(id)arg1;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

