//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSViewController.h"

#import "EmoticonDownloadMgrExt.h"
#import "EmoticonMgrExt.h"
#import "MASPreferencesViewController.h"
#import "NSTableViewDataSource.h"
#import "NSTableViewDelegate.h"

@class NSArray, NSImage, NSSegmentedControl, NSString, NSTableView;

__attribute__((visibility("hidden")))
@interface MMPreferencesStickerStoreController : NSViewController <MASPreferencesViewController, NSTableViewDataSource, NSTableViewDelegate, EmoticonDownloadMgrExt, EmoticonMgrExt>
{
    NSTableView *_stickersTable;
    NSSegmentedControl *_tabBar;
    NSArray *_loadedStickerStorePacks;
    NSArray *_loadedMyStickers;
}

@property(retain, nonatomic) NSArray *loadedMyStickers; // @synthesize loadedMyStickers=_loadedMyStickers;
@property(retain, nonatomic) NSArray *loadedStickerStorePacks; // @synthesize loadedStickerStorePacks=_loadedStickerStorePacks;
@property(retain, nonatomic) NSSegmentedControl *tabBar; // @synthesize tabBar=_tabBar;
@property(nonatomic) __weak NSTableView *stickersTable; // @synthesize stickersTable=_stickersTable;
- (void).cxx_destruct;
- (void)installedStickerPacksChanged;
- (void)downloadForStoreItem:(id)arg1 changedState:(long long)arg2 progress:(double)arg3;
- (void)deleteStickerPack:(id)arg1;
- (void)downloadStickerPack:(id)arg1;
- (id)tableView:(id)arg1 viewForTableColumn:(id)arg2 row:(long long)arg3;
- (long long)numberOfRowsInTableView:(id)arg1;
- (id)activeContent;
- (void)tabChanged:(id)arg1;
- (void)viewWillAppear;
- (void)viewDidLoad;
@property(readonly, nonatomic) NSImage *toolbarItemImage;
@property(readonly, nonatomic) NSString *toolbarItemLabel;
@property(readonly, nonatomic) NSString *identifier;
- (void)dealloc;
- (id)initWithNibName:(id)arg1 bundle:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly, nonatomic) BOOL hasResizableHeight;
@property(readonly, nonatomic) BOOL hasResizableWidth;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

