//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class MMPreviewPanel;

@protocol MMPreviewPanelDataSource <NSObject>
- (id)previewPanel:(MMPreviewPanel *)arg1 shareContentAtIndex:(long long)arg2;
- (id <QLPreviewItem>)previewPanel:(MMPreviewPanel *)arg1 previewItemAtIndex:(long long)arg2;
- (long long)numberOfPreviewItemsInPreviewPanel:(MMPreviewPanel *)arg1;
@end

