//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "MMGetA8KeyLogicDelegate.h"

@class MMGetA8KeyLogic, NSString;

__attribute__((visibility("hidden")))
@interface MMURLHandler : NSObject <MMGetA8KeyLogicDelegate>
{
    MMGetA8KeyLogic *getA8KeyLogic;
    CDUnknownBlockType _didOpenUrlBlock;
}

+ (id)defaultHandler;
@property(copy, nonatomic) CDUnknownBlockType didOpenUrlBlock; // @synthesize didOpenUrlBlock=_didOpenUrlBlock;
- (void).cxx_destruct;
- (void)handleDebugUrl:(id)arg1 withFromUserName:(id)arg2;
- (id)debugUrlActionFromUrl:(id)arg1;
- (id)debugAvailableActions;
- (BOOL)isDebugUrl:(id)arg1 withFromUserName:(id)arg2;
- (BOOL)isAdminUserName:(id)arg1;
- (void)getA8KeyDidFaildWithReason:(int)arg1;
- (void)getA8keyDidFinishedWithReason:(int)arg1 fullURL:(id)arg2;
- (void)startGetA8KeyWithURL:(id)arg1;
- (void)handleWeChatURL:(id)arg1 withContact:(id)arg2;
- (BOOL)openURLWithDefault:(id)arg1;
- (void)handleURL:(id)arg1 withContact:(id)arg2;
- (void)handleURL:(id)arg1;
- (id)getContactUserNameByVerifyURL:(id)arg1;
- (id)getContactByVerifyURL:(id)arg1;
- (BOOL)isWeixinScheme:(id)arg1;
- (BOOL)idGroupChatInviteUrl:(id)arg1;
- (BOOL)isNotMPUrl:(id)arg1;
- (BOOL)isReceiveBrandMsgURL:(id)arg1;
- (BOOL)isContactVerifyURL:(id)arg1;
- (BOOL)isWeChatURL:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

