//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface NSObject (A2BlockDelegate)
+ (void)bk_registerDynamicDelegateNamed:(id)arg1 forProtocol:(id)arg2;
+ (void)bk_registerDynamicDelegateNamed:(id)arg1;
+ (void)bk_registerDynamicDataSourceNamed:(id)arg1;
+ (void)bk_registerDynamicDelegate;
+ (void)bk_registerDynamicDataSource;
+ (void)bk_linkProtocol:(id)arg1 methods:(id)arg2;
+ (void)bk_linkDelegateMethods:(id)arg1;
+ (void)bk_linkDataSourceMethods:(id)arg1;
+ (const CDStruct_0348af7d *)bk_delegateInfoForProtocol:(id)arg1;
+ (id)bk_delegateInfoByProtocol:(BOOL)arg1;
- (id)bk_ensuredDynamicDelegateForProtocol:(id)arg1;
- (id)bk_ensuredDynamicDelegate;
@end

