//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSError, NSImage, SDWebImageDownloader;

@protocol SDWebImageDownloaderDelegate <NSObject>

@optional
- (void)imageDownloader:(SDWebImageDownloader *)arg1 didFailWithError:(NSError *)arg2;
- (void)imageDownloader:(SDWebImageDownloader *)arg1 didFinishWithImage:(NSImage *)arg2;
- (void)imageDownloaderDidFinish:(SDWebImageDownloader *)arg1;
@end

