//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PBGeneratedMessage.h"

@class BaseResponse, NSMutableArray, NSString, SnsBufferUrl;

__attribute__((visibility("hidden")))
@interface SnsUploadResponse : PBGeneratedMessage
{
    unsigned int hasBaseResponse:1;
    unsigned int hasStartPos:1;
    unsigned int hasTotalLen:1;
    unsigned int hasClientId:1;
    unsigned int hasBufferUrl:1;
    unsigned int hasThumbUrlCount:1;
    unsigned int hasId:1;
    unsigned long long id_;
    unsigned int hasType:1;
    unsigned int startPos;
    unsigned int totalLen;
    unsigned int thumbUrlCount;
    unsigned int type;
    BaseResponse *baseResponse;
    NSString *clientId;
    SnsBufferUrl *bufferUrl;
    NSMutableArray *mutableThumbUrlsList;
}

+ (id)parseFromData:(id)arg1;
@property(nonatomic, setter=SetType:) unsigned int type; // @synthesize type;
@property(readonly, nonatomic) BOOL hasType; // @synthesize hasType;
@property(nonatomic, setter=SetId:) unsigned long long id; // @synthesize id=id_;
@property(readonly, nonatomic) BOOL hasId; // @synthesize hasId;
@property(retain, nonatomic) NSMutableArray *mutableThumbUrlsList; // @synthesize mutableThumbUrlsList;
@property(nonatomic, setter=SetThumbUrlCount:) unsigned int thumbUrlCount; // @synthesize thumbUrlCount;
@property(readonly, nonatomic) BOOL hasThumbUrlCount; // @synthesize hasThumbUrlCount;
@property(retain, nonatomic, setter=SetBufferUrl:) SnsBufferUrl *bufferUrl; // @synthesize bufferUrl;
@property(readonly, nonatomic) BOOL hasBufferUrl; // @synthesize hasBufferUrl;
@property(retain, nonatomic, setter=SetClientId:) NSString *clientId; // @synthesize clientId;
@property(readonly, nonatomic) BOOL hasClientId; // @synthesize hasClientId;
@property(nonatomic, setter=SetTotalLen:) unsigned int totalLen; // @synthesize totalLen;
@property(readonly, nonatomic) BOOL hasTotalLen; // @synthesize hasTotalLen;
@property(nonatomic, setter=SetStartPos:) unsigned int startPos; // @synthesize startPos;
@property(readonly, nonatomic) BOOL hasStartPos; // @synthesize hasStartPos;
@property(retain, nonatomic, setter=SetBaseResponse:) BaseResponse *baseResponse; // @synthesize baseResponse;
@property(readonly, nonatomic) BOOL hasBaseResponse; // @synthesize hasBaseResponse;
- (void).cxx_destruct;
- (void)addThumbUrls:(id)arg1;
- (void)addThumbUrlsFromArray:(id)arg1;
- (id)mergeFromCodedInputStream:(id)arg1;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (BOOL)isInitialized;
@property(retain, nonatomic) NSMutableArray *thumbUrls; // @dynamic thumbUrls;
- (id)thumbUrlsList;
- (id)init;

@end

